### PR TITLE
Overrode `+` operator for UnifiedResponse object

### PR DESCRIPTION
**Pull request by yudhik11**
Issue #2141

### CODE REVIEW

**Comment by Cadair** [comment]
wow, that really is that simple isn't it?! 🎉 

This is going to need a whole raft of tests to make sure it dosen't have any weird side effects.

Thanks!

**Comment by yudhik11** [comment]
`from sunpy.net import Fido, attrs as a
import astropy.units as u

result1 = Fido.search(a.Time('2012/3/4', '2012/3/6'), a.Instrument('aia'),
        a.Wavelength(171*u.angstrom) | a.Wavelength(94*u.angstrom))

result2 = Fido.search(a.Time('2012/3/4', '2012/3/6'), a.Instrument('aia'),
        a.Wavelength(171*u.angstrom) )

result3 = Fido.search(a.Time('2012/3/4', '2012/3/6'), a.Instrument('aia'),
        a.Wavelength(94*u.angstrom))

print result1
print result2
print result3
print result2+result3
print type(result1) ,  type(result2+result3)
net = result2+result3
assert result1 ==  net, "Problem"`
This assertion is True, so what all testcases do I need to make

**Comment by Punyaslok** [comment]
@Cadair I think some potential issues need to be addressed :

- What happens when lists have common entries are common ?
- So its just blind concat of lists ? What about the timestamp of entries ?
- What about a+a ?

**Comment by Cadair** [comment]
@Punyaslok Valid points,

So the list holds the `QueryResponse` objects not the actual results themselves, so the timestamps and all the client info is persisted in this simple implementation.

Doing a full de-dupe on the results would probably be a good usability improvement. As I can see people getting repeat files by mistake like this.
I guess the easiest way of doing that would just be to iterate over all the response objects if they are the same type and check that the results don't match. Of course, it might be nicer if there was a way of doing set-like operations on the results objects for things like this.

**Comment by Cadair** [comment]
@yudhik11 I think this needs some unit tests of it's own, so that we are explicitly testing this behaviour and can make sure it keeps working as intended.

**Comment by yudhik11** [comment]
I looked into it and I got into the depth of responses I receive from fido_factory.py

I found out that each response can have collection of UnifiedResponses
```
Fido.search(a.Time('2012/3/4', '2012/3/5'), a.Instrument('aia'),
        a.Wavelength(171*u.angstrom) | a.Wavelength(94*u.angstrom))
```
results in
```
145 Results from the VSOClient:
   Start Time [1]       End Time [1]    Source Instrument   Type   Wavelength [2]
                                                                      Angstrom   
       str19               str19         str3     str3      str8      float64    
------------------- ------------------- ------ ---------- -------- --------------
2012-03-04 15:39:36 2012-03-04 15:49:25    SDO        AIA FULLDISK 171.0 .. 171.0
2012-03-04 04:09:36 2012-03-04 04:19:25    SDO        AIA FULLDISK 171.0 .. 171.0
2012-03-04 01:49:36 2012-03-04 01:59:25    SDO        AIA FULLDISK 171.0 .. 171.0
2012-03-04 20:09:36 2012-03-04 20:19:25    SDO        AIA FULLDISK 171.0 .. 171.0
2012-03-04 03:09:36 2012-03-04 03:19:25    SDO        AIA FULLDISK 171.0 .. 171.0
2012-03-04 08:39:36 2012-03-04 08:49:25    SDO        AIA FULLDISK 171.0 .. 171.0
....
145 Results from the VSOClient:
   Start Time [1]       End Time [1]    Source Instrument   Type   Wavelength [2]
                                                                      Angstrom   
       str19               str19         str3     str3      str8      float64    
------------------- ------------------- ------ ---------- -------- --------------
2012-03-04 05:39:26 2012-03-04 05:49:15    SDO        AIA FULLDISK   94.0 .. 94.0
2012-03-04 15:29:26 2012-03-04 15:39:15    SDO        AIA FULLDISK   94.0 .. 94.0
2012-03-04 04:19:26 2012-03-04 04:29:15    SDO        AIA FULLDISK   94.0 .. 94.0
2012-03-04 17:19:26 2012-03-04 17:29:15    SDO        AIA FULLDISK   94.0 .. 94.0
...
```
in each Response list, there is again a bunch of UnifiedResponse list 
```
145 Results from the VSOClient:
   Start Time [1]       End Time [1]    Source Instrument   Type   Wavelength [2]
                                                                      Angstrom   
       str19               str19         str3     str3      str8      float64    
------------------- ------------------- ------ ---------- -------- --------------
2012-03-04 15:39:36 2012-03-04 15:49:25    SDO        AIA FULLDISK 171.0 .. 171.0
2012-03-04 04:09:36 2012-03-04 04:19:25    SDO        AIA FULLDISK 171.0 .. 171.0
2012-03-04 01:49:36 2012-03-04 01:59:25    SDO        AIA FULLDISK 171.0 .. 171.0
2012-03-04 20:09:36 2012-03-04 20:19:25    SDO        AIA FULLDISK 171.0 .. 171.0
2012-03-04 03:09:36 2012-03-04 03:19:25    SDO        AIA FULLDISK 171.0 .. 171.0
2012-03-04 08:39:36 2012-03-04 08:49:25    SDO        AIA FULLDISK 171.0 .. 171.0
```
and each of the response
```
2012-03-04 15:39:36 2012-03-04 15:49:25    SDO        AIA FULLDISK 171.0 .. 171.0
```

looks like 
```
(QueryResponseBlock){
   size = 3376200.0
   instrument = "AIA"
   extra = 
      (Extra){
         flags = "S"
      }
   info = "AIA level 1, 4096x4096 [51 records] [0 eclipse] [0 darks] [1.193 to 2.000 exposure] [100.00 avg. percentd]"
   physobs = "intensity"
   fileid = "aia__lev1:171:1110037200:1110037799"
   extent = 
      (Extent){
         type = "FULLDISK"
         length = "4096"
         width = "4096"
      }
   wave = 
      (Wave){
         waveunit = "Angstrom"
         wavemin = "171"
         wavetype = "NARROW"
         wavemax = "171"
      }
   source = "SDO"
   time = 
      (Time){
         end = "20120305154925"
         start = "20120305153925"
      }
   provider = "JSOC"
 }
```
printing the same response again and again the attributes were jumbled but the values were same, so how am I supposed to compare responses and implementing the set thing will be impossible for me without first figuring out this issue.

Also, I cannot hardcode the attributes as they are different for different Fido query.

**Pull request closed without merging**
