### PR TITLE
Updated offset_frame.py and frames.py.

### PR DESCRIPTION
**Pull request by agneet42**
Removed Documentation error in offset_frame.py and set default representation as SphericalRepresentation in frames.py

### CODE REVIEW

**Comment by Cadair** [comment]
Looks like this needs some extra work: https://travis-ci.org/sunpy/sunpy/jobs/218608327#L1074

**Comment by agneet42** [comment]
@Cadair, yes. I noticed. representation.py has a SphericalWrap180Representation. There's no definition of  SphericalWrapRepresentation. Do I make all the changes in the subsequent places wherever it is mentioned?

**Comment by Cadair** [comment]
@agneet42 oh, my bad it should be `SphericalRepresentation`.

**Comment by Cadair** [comment]
@nabobalis backport me!

**Pull request merged**
