### PR TITLE
Fix round-tripping of hgs-hgc dateobs attribute for wcsaxes

### PR DESCRIPTION
**Pull request by Cadair**

### CODE REVIEW

**Comment by Cadair** [comment]
@nabobalis This will need back-porting

**Comment by nabobalis** [comment]
Description please.

**Comment by raphaelattie** [comment]
@Cadair (hey it's Wall-E) Thanks for submitting this!

**Comment by nabobalis** [comment]
@Cadair you wanted to add tests? Otherwise I will merge and backport.

**Pull request merged**
