### PR TITLE
Update mailmap and zenodo.json for 3.0

### PR DESCRIPTION
**Pull request by dstansby**

### CODE REVIEW

**Comment by dstansby** [comment]
👋 hello new contributors! I am updating the list of authors for the zenodo entry (see https://zenodo.org/record/3779284 for a previous example). I have mentioned you because you are a new contributor since sunpy 2.1.

If you would like, please leave a comment below with:

The preferred name you would like to be listed as
Your ORCID
Your affiliation

I will then manually add this to the information. Note that none of this is compulsory!

@yukienomiya @adwaitbhope @varunbankar @kc611 @Qtty @m11dedhia @ratuldas6 @samriddhi-dev @asinghgaba

**Comment by asinghgaba** [comment]
Hi @dstansby the details are as follows:
Name: Amarjit Singh Gaba
ORCID: 0000-0002-9505-0160
Affiliation: School of Mathematics, Cardiff University, Cardiff, Wales, UK

Thank you! 🙏🏻

**Comment by ratuldas6** [comment]
Hey @dstansby <https://github.com/dstansby>,

Thanks for the email. As requested, here are my details:
Name: Ratul Das
ORCID: 0000-0002-5845-9979
Affiliated to: National Institute of Science Education and Research,
Bhubaneswar, Odisha, India

Thanks and Regards
Ratul

**Comment by m11dedhia** [comment]
Hello @dstansby,

Here are my details:
1. Name : Megh Dedhia
2. ORCID : 0000-0002-5828-7679
3. Affliation : DJ Sanghvi College of Engineering, Mumbai University

Thank you.

**Comment by adwaitbhope** [comment]
Thanks @dstansby. Here are my details:
1. Name: Adwait Bhope
2. ORCID: 0000-0002-7133-8776
3. Affiliation: Savitribai Phule Pune University, Pune, India

**Comment by samriddhi-dev** [comment]
Hi @dstansby,
Preferred Name: Samriddhi Agarwal
ORCID:0000-0003-4497-1637
 Affiliation: Ryan International School, Bengaluru, Karnataka, India

**Comment by samriddhi-dev** [comment]
https://github.com/dstansby

**Comment by yukienomiya** [comment]
Hi @dstansby !
My details are:
Name: Yukie Nomiya
ORCID: 0000-0002-9572-6300
Affiliation: Sapienza University of Rome, Italy

Thank you :)

**Comment by kc611** [comment]
Hello @dstansby,

Here are my details:

Name : Kaustubh Chaudhari
ORCID : 0000-0003-1734-5075
Affliation : Indian Institute of Information Technology, Gwalior
Thank you.

**Review by Cadair — APPROVED** [review]

**Review by Cadair — CHANGES_REQUESTED** [review]
one sec

**Review by Cadair — APPROVED** [review]
Wanted to check the shortlog as that's what the release notes generator uses. I just fixed up a couple of names.

**Review by nabobalis — APPROVED** [review]

**Pull request merged**
