### PR TITLE
added list_samples() in _sample.py

### PR DESCRIPTION
**Pull request by swapsha96**
Addressing to issue #211 in which @khughitt mentioned to add new functions in `sunpy.data` to facilitate downloading sample data. `list_samples()` will help users to get list of all available samples. Now, the user can download specific file from this list using other functions(not added yet).

### CODE REVIEW

**Comment by swapsha96** [comment]
@dpshelio @Cadair Should continue working on other functions mentioned in issue #211?

**Comment by nabobalis** [comment]
Issue #211 is more about normalizing the sample data.

The extra items that khughitt wanted I am not sure we want or agreed on (before my time). Functionally we want is to download all the sample data and not just single files. So a list_sample function isn't really what I want in SunPy. On the last meeting we did discuss what we wanted but my memory is poor so I will have @Cadair see if he remembers.

**Comment by nabobalis** [comment]
It's a bit early to close this, I'd wait for @Cadair first to weigh in.

**Comment by swapsha96** [comment]
@nabobalis By mistake, I created this pull request from master instead of creating a new branch. The issue is still open so I guess this is no problem.

**Pull request closed without merging**
