### PR TITLE
[0.7] Composite map draw_limb and draw_grid

### PR DESCRIPTION
**Pull request by wafels**
Now take keyword arguments so line properties can be changed when using composite map

### CODE REVIEW

**Comment by Cadair** [comment]
not also master?

**Comment by wafels** [comment]
Master is coming...

**Comment by nabobalis** [comment]
Is the fix different for master?

**Comment by wafels** [comment]
yes - master uses wcsaxes_compat

**Comment by Cadair** [comment]
ah cool cool.

**Comment by wafels** [comment]
Turns out the EIT wave detection paper is doing what ehsteve wanted, which was to find bugs in sunpy.

**Comment by Cadair** [comment]
It's almost like using SunPy generates bug reports. Can't be having that.

**Comment by nabobalis** [comment]
*lack of users snarky comment*

**Comment by nabobalis** [comment]
The failure is astropy-dev. 
If there are no more corrections you want to make, it looks ready to me.

**Pull request merged**
