### PR TITLE
#2005 instantiating map with wcs

### PR DESCRIPTION
**Pull request by agneet42**
Changes made in map_factory.py

### CODE REVIEW

**Comment by agneet42** [comment]
@Cadair, I have added the wcs object. Could you review? Thanks.

**Comment by Cadair** [comment]
This is a duplicate of #2007

**Comment by agneet42** [comment]
@Cadair Do I need to make some changes then?

**Comment by Cadair** [comment]
@agneet42 you have both tried to address the same issue. You should work on something that someone else hasn't already picked up.

**Pull request closed without merging**
