### PR TITLE
Fix _pyana initialisation in Python 3

### PR DESCRIPTION
**Pull request by Cadair**
This enables pyana in Python 3 by making the module init compatible with both python 2 and python 3.

ping @nabobalis

### CODE REVIEW

**Comment by nabobalis** [comment]
Fancy! As long as it works. Still begs the issue if this should in core or on a sunkit package.

**Comment by Cadair** [comment]
@ayshih you know the most about this, you want to take a look?

**Comment by ayshih** [comment]
This PR looks fine to me.  Just some notes for posterity:
* As mentioned in a code comment, this fix is adapted from https://docs.python.org/2/howto/cporting.html
* Setting aside the issue of whether the ANA code should be in SunPy, supporting this extension has ancillary benefits of making sure we don't break something in our build/test environments and providing an example for any developer who wants to add something analogous.
* Way outside the scope of this PR: I'm fond of Cython, which would make the ANA code easier to support/review and automatically Python 2/3 compatible.

:+1:

**Comment by nabobalis** [comment]
I think Cython would be the end goal, looking very long term.

**Pull request merged**
