### PR TITLE
Remove 4.1 changelogs

### PR DESCRIPTION
**Pull request by dstansby**
Don't know what I managed to do with https://github.com/sunpy/sunpy/pull/6592, but here's a replacement with README.md not deleted.

### CODE REVIEW

**Comment by nabobalis** [comment]
Do we not need to update changelog.rst?

**Comment by dstansby** [comment]
Oh yeah, so we do, thanks for catching! I shall do it in this PR.

**Comment by Cadair** [comment]
The best way to do this in my experience has been to cherry-pick the render changelog commit from the release branch back onto main. Is that what you have done here?

That approach ensures two things: firstly that you get the rendered changelog and two that you only remove changelog fragments that were released in the major version in question.

**Comment by dstansby** [comment]
> The best way to do this in my experience has been to cherry-pick the render changelog commit from the release branch back onto main. Is that what you have done here?

No, it was not, thanks for catching and suggesting the Right Way to do it - new PR at https://github.com/sunpy/sunpy/pull/6609 with the cherry-picked commit

**Pull request closed without merging**
