### PR TITLE
[unidown]: FIDO API and JSOC support

### PR DESCRIPTION
**Pull request by Cadair**
This is a different attempt at an API following on from the discussion in #1315.

As it stands this implements the following:

```python

import sunpy.net.dataretriever as dr

results = dr.Fido.search(dr.Time('2012/1/1', '2012/1/2'), dr.Instrument('goes'))
files = dr.Fido.fetch(results, wait=True)
```

### CODE REVIEW

**Comment by Cadair** [comment]
This notebook gives some examples of the API.

http://nbviewer.ipython.org/gist/Cadair/cfc827e1222c94714caf

**Comment by ehsteve** [comment]
Should we remove the ability to use the attrs as parameters (i.e. Fido(a, b, c, d)) and only accept ``Fido(a & b & c)`` that would reinforce the strength of the using the attributes and would make it less confusing when wanting to generate a complex query (e.g. which one is correct ``Fido( a & b, c || d`` or Fido(a & b || c || d)?

I still think we should somehow just use TimeRange objects instead of Time.

**Comment by Cadair** [comment]
@ehsteve It's an interesting idea. Which I am not particularly opposed to.

Something I want to discuss at the meeting tonight is the level of backwards compatibility we want to maintain here, opinion on `&` vs `,` kinda falls back to this.

My favoured approach would be not to disable using `,` as a `&` operator (which iirc is now it works), but that we just change *all* the documentation to use `&` so that to the users that seems to be the correct way of doing it, like that it doesn't confuse anyone who is used to `,` and it means less code changes for us.

From a technical perspective I am not sure it would be that easy to enforce `&` over `,` because of the way I think the attr Walkers work. We would need someone who knows more about it to chime in on that though. @segfaulthunter @gunner272

**Comment by wafels** [comment]
Calling what is essentially understood as a sunpy timerange object 'Time'
in fido is annoying, and a little confusing.  Even renaming Time to
something else that implies a time range would be good.

**Comment by Cadair** [comment]
@wafels we could rename `Time` to `TimeRange` but then that has obvious implications inside SunPy, as they would be two separate objects. Also we should then rename `Wavelength` to `WavelengthRange` to be consistent, and it would spiral out of control from there.

As for the `Time` - `TimeRange` duality. Unless someone comes along and corrects me, the more I look into it the more impractical I think it is to allow `TimeRange` instead of `Time`. It would require grafting a very large amount of code (Think `__and__`, `__or__`, inheritance from `Attr` and `_Range`) from `sunpy.net` into `sunpy.time.timerange`. Would it be possible? Yes, it would. Would it make the API cleaner for the user? Maybe, I am left to be convinced that the current API is particularly confusing in reality. Would it make the code cleaner and easier to maintain in the future? Absolutely not. We were discussing at the end of the sprint about how we all were having to relearn parts of the `.net` code base, especially the attribute code, which is very smart, your suggestion requires that we import all that code into the `sunpy.time` module just to help users save 10 keystrokes per search. That is not worth the sacrifice in developer time, in my opinion.

**Comment by wafels** [comment]
would it be desirable to allow Time to accept an existing TimeRange object?

**Comment by Cadair** [comment]
@wafels it already can.

**Comment by segfaulthunter** [comment]
& or , has nothing to do with the Walker. The separate arguments are explicitly ANDed: https://github.com/sunpy/sunpy/blob/master/sunpy/net/vso/vso.py#L331

**Comment by Cadair** [comment]
Cool, so we could force `&` quite easily then, if we wanted to.

**Comment by segfaulthunter** [comment]
@Cadair as said, I think coercing to `Time` when & and | is not a good idea because that makes it confusing when you only give a TimeRange  to query.

**Comment by Cadair** [comment]
Back on the `,` vs `&` thing, as @segfaulthunter pointed out on IRC, using `,` is like brackets, as that expression is evaluated before it is passed into the `search` method. i.e.

Current API:
```python
dr.Fido.search(dr.Time(start, end), dr.Instrument('goes') | dr.Instrument('lyra'))
```

API with no support for `,`
```python
dr.Fido.search(dr.Time(start, end) & (dr.Instrument('goes') | dr.Instrument('lyra')))
```

Now which is clearer is probably a matter of personal opinion, but I am in favour of supporting both, with the latter being the 'main' way of doing it that all the docs show.

**Comment by Cadair** [comment]
This PR seemed to get general approval at the dev meeting. Most of the discussion was around the `,` syntax and the name `Fido`.

**Comment by ehsteve** [comment]
It was agreed that all docs would use one logical statement as input (no comma-separated list of parameters) but that functionality would still be available for advanced users.

**Comment by ehsteve** [comment]
:+1:

**Comment by wafels** [comment]
[image: :+1:]

**Pull request merged**
