### PR TITLE
Create north_offset_frame.py   Gallery Example Added

### PR DESCRIPTION
**Pull request by prateekiiest**
Gallery Example for North Offset Frame
issue #2064

### CODE REVIEW

**Comment by prateekiiest** [comment]
@Cadair , I want to understand the functionality of this example.
Why we need this?

**Comment by prateekiiest** [comment]
@Cadair , why is this failing?

**Comment by nabobalis** [comment]
This failure seems to be an online test issue. I will rekick travis for kicks.

**Comment by nabobalis** [comment]
Before this can be merged, there needs to be text to explain the purpose of the example and what it achieves. Co-ord transform is an opaque topic at times  and just the code alone is not enough.

**Comment by prateekiiest** [comment]
@nabobalis failing due to if block shifting?
The argument for int() can not be datetime

**Comment by nabobalis** [comment]
Unfortunately, the example needs more working through before it can be used in the gallery. It really needs someone who understands Frames and transforms to expand upon it.

**Pull request closed without merging**
