### PR TITLE
Clarify definition of map.dsun

### PR DESCRIPTION
**Pull request by dstansby**
It occurred to me that "the Sun" is technically not a point, so this should read "center of the Sun".

### CODE REVIEW

**Comment by Cadair** [comment]
>  "the Sun" is technically not a point

your approximations are weak :stuck_out_tongue:

**Comment by dstansby** [comment]
> > "the Sun" is technically not a point
> 
> your approximations are weak 😛

I know, but I have had to go a step further and consider the Sun as a perfectly round sphere.

**Comment by dstansby** [comment]
Woops, did not mean to close...

**Comment by nabobalis** [comment]
In the future a way for a bot to create a changelog entry from a commit message or title would be nice.

**Comment by dstansby** [comment]
Yes definitely... something that can automatically be done through a comment instead of having to faff around with the source code and git again would be great.

**Comment by Cadair** [comment]
Yeah I think we all had the same idea at the same time :laughing: 

I am about 95% of the way to having rewritten sunpy bot (based on big changes to Baldrick) would be easy enough to add a command to make a changelog entry I think.

**Pull request merged**
