### PR TITLE
Add reproject to rtd env

### PR DESCRIPTION
**Pull request by Cadair**

### CODE REVIEW

**Comment by dstansby** [comment]
Lets merge and see if it fixes things: https://readthedocs.org/projects/sunpy/builds/

**Comment by Cadair** [comment]
It did but:
```
generating gallery for generated/gallery/sunpy_other_packages... [100%] reprojection_aia_euvi_mosaic.py
Killed


Command killed due to excessive memory consumption
```
whoops!

**Comment by wtbarnes** [comment]
Same https://readthedocs.org/projects/aiapy/builds/9994608/. 

Will RTD increase the memory limit on the container?

**Comment by Cadair** [comment]
Probably if you ask nicely.

**Comment by dstansby** [comment]
It looks like the limit is 1GB RAM - the other thing to check would be that memory isn't building up in the background from previous examples for some reason.

**Comment by wtbarnes** [comment]
We're using full resolution, full disk images in the aiapy examples so I guess this is not too surprising. I've sent a nice email so we'll see what they say.

**Pull request merged**
