### PR TITLE
Parse time docstring trickery

### PR DESCRIPTION
**Pull request by Cadair**

### CODE REVIEW

**Comment by nabobalis** [comment]
LIKE MAGIC

**Comment by nabobalis** [comment]
https://4763-2165383-gh.circle-artifacts.com/0/root/project/docs/_build/html/api/sunpy.time.parse_time.html?highlight=parse_time#sunpy.time.parse_time

**Comment by nabobalis** [comment]
Only issue seems to be that  `– Time to parse.` isnt a new line?

**Comment by Cadair** [comment]
I guess that's because it's short?! I can't see any reason in the formatting why it should be any different to anything else.

**Comment by nabobalis** [comment]
Its its meant to be like that. its ok by me

**Pull request merged**
