### PR TITLE
add .cmap and .norm property to plot_settings

### PR DESCRIPTION
**Pull request by nitish705702**
#3624  # Description
 adding .cmap and .norm property to plot_settings

### CODE REVIEW

**Comment by nabobalis** [comment]
Hi @nitish705702, can you explain what the reasoning behind these changes? Are they meant to be in #3624?

**Comment by nitish705702** [comment]
yes ,  I explain what the reasoning behind these changes 
Replacing is require because Replaces up plot_settings in sunpy.map.mapbase, and adds up .cmap and .norm so as to provide for a cleaner and usable API.

**Comment by nabobalis** [comment]
> yes , I explain what the reasoning behind these changes
> Replacing is require because Replaces up plot_settings in sunpy.map.mapbase, and adds up .cmap and .norm so as to provide for a cleaner and usable API.

So are these changes undoing the changes in #3624 or fixing mistakes?

**Comment by nitish705702** [comment]
No sir ,it was fixing issues.

**Comment by nabobalis** [comment]
> No sir ,it was fixing issues 3841
> .

Unfortunately, the original issue (#3415) will be fixed by #3624 

I would suggest picking up another issue to fix and checking that there is not an open pull request for it.

**Pull request closed without merging**
