### PR TITLE
Fix transformations from HGS frames when representation is cartesian

### LINKED ISSUE #2632: Transformation between HGS and HPC fails when using Cartesian representation
Converting  a coordinate in Heliographic-Stonyhurst coordinates with a Cartesian representation to Helioprojective coordinates fails. E.g.,

```python
>>> import astropy.units as u
>>> import astropy.constants as const
>>> import sunpy.coordinates
>>> foo = SkyCoord(x=const.R_sun, y=0.*u.km, z=0.*u.km, 
                   frame='heliographic_stonyhurst', representation='cartesian')
>>> obs = sunpy.coordinates.ephemeris.get_earth()
>>> foo.transform_to(sunpy.coordinates.Helioprojective(observer=obs))
```
raises
```python traceback
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-46-77d08794e7f4> in <module>()
----> 1 foo.transform_to(sunpy.coordinates.Helioprojective(observer=obs))

~/anaconda/envs/synthesizar/lib/python3.6/site-packages/astropy/coordinates/sky_coordinate.py in transform_to(self, frame, merge_attributes)
    480         # Do the transformation, returning a coordinate frame of the desired
    481         # final type (not generic).
--> 482         new_coord = trans(self.frame, generic_frame)
    483 
    484         # Finally make the new SkyCoord object from the `new_coord` and

~/anaconda/envs/synthesizar/lib/python3.6/site-packages/astropy/coordinates/transformations.py in __call__(self, fromcoord, toframe)
   1312 
   1313             curr_toframe = t.tosys(**frattrs)
-> 1314             curr_coord = t(curr_coord, curr_toframe)
   1315 
   1316         # this is safe even in the case where self.transforms is empty, because

~/anaconda/envs/synthesizar/lib/python3.6/site-packages/astropy/coordinates/transformations.py in __call__(self, fromcoord, toframe)
    747 
    748     def __call__(self, fromcoord, toframe):
--> 749         res = self.func(fromcoord, toframe)
    750         if not isinstance(res, self.tosys):
    751             raise TypeError('the transformation function yielded {0} but '

~/anaconda/envs/synthesizar/lib/python3.6/site-packages/sunpy/coordinates/transformations.py in hgs_to_hcc(heliogcoord, heliocframe)
    186     # TODO: Revert this.
    187     from astropy.tests.helper import quantity_allclose
--> 188     hglon = heliogcoord.lon
    189     hglat = heliogcoord.lat
    190     r = heliogcoord.radius

~/anaconda/envs/synthesizar/lib/python3.6/site-packages/astropy/coordinates/baseframe.py in __getattr__(self, attr)
   1249             return val
   1250 
-> 1251         return self.__getattribute__(attr)  # Raise AttributeError.
   1252 
   1253     def __setattr__(self, attr, value):

AttributeError: 'HeliographicStonyhurst' object has no attribute 'lon'
```

However, adding an intermediate step to change to a spherical representation fixes this,

``` python
>>> (foo.transform_to('heliographic_stonyhurst')
        .transform_to(sunpy.coordinates.Helioprojective(observer=obs)))
```

### PR DESCRIPTION
**Pull request by wtbarnes**
Resolves #2632

### CODE REVIEW

**Comment by Cadair** [comment]
@wtbarnes looks good, can I please have a changelog entry and a regression test? :angel:

**Comment by Cadair** [comment]
Also are there any other transform functions that should have this done to them?

**Comment by wtbarnes** [comment]
Sure! Two questions:

1. Where should this go in the changelog? Looks like there isn't a 0.9.1 heading so should I just create a new one and add a Bug Fixes section?
2. By regression test, do you just mean add a test where an HGS frame in a cartesian representation is transformed to different frames?

**Comment by wtbarnes** [comment]
Also, looks like this fix needs to happen in the HGS<->HGC transformation as well. Oddly enough, seems whoever wrote that fixed it one place (`lat`), but not when accessing `lon` and `radius`...

**Comment by Cadair** [comment]
wrt the changelog let's get #2644 merged in first.

Yeah for the regression just a test to check that you can transform through with Cartesian representations at different points. (i.e. one for each change I assume)

**Comment by Cadair** [comment]
@wtbarnes I have merged #2644 so if you add a file to `changelog/` with the changelog entry in it. (Follow the instructions in the `README` in that folder).

**Comment by wtbarnes** [comment]
Ok added the changelog and tests. Let me know if you'd like to see more in the tests. I've basically just checked that a transform from cartesian and a transform from spherical yield the same results, for HGS->HCC, HGS->HPC, HGS->HGC.

**Comment by Cadair** [comment]
This looks great! Thanks a lot @wtbarnes !

**Comment by wtbarnes** [comment]
Wow all of the tests passed. How strange.

**Pull request merged**
