### PR TITLE
Decimal Carrington rotation of the central meridian

### PR DESCRIPTION
**Pull request by wafels**
This PR includes a function that calculates the Carrington rotation of the central meridian.  It is based on tim2carr.pro.  The existing Carrington rotation number function is not changed, but what this number actually refers to should be improved.

### CODE REVIEW

**Comment by Cadair** [comment]
Do we need two carrington rotation functions?

Also I do wonder about the copyright issues with translating code from SSW like this.

**Comment by wafels** [comment]
On Mon, Jan 25, 2016 at 4:08 PM, Stuart Mumford <notifications@github.com>
wrote:

> Do we need two carrington rotation functions?
>
It wasn't clear to me what the existing carrington rotation number refers
to precisely.  The new one is a bit clearer.  I think, though, we should
refer to another source that has an accurate and clear definition.


> Also I do wonder about the copyright issues with translating code from SSW
> like this.
>

I wonder about  that too.  And what about copying formulae from textbooks?

**Comment by Cadair** [comment]
> It wasn't clear to me what the existing carrington rotation number refers
> to precisely.  The new one is a bit clearer.  I think, though, we should
> refer to another source that has an accurate and clear definition.

I agree the new name makes it clearer what it is calculating, even if it is rather long. Do we however need to preserve the old implementation?

> I wonder about  that too.  And what about copying formulae from textbooks?

Solarsoft is tricky because the code is not licenced in anyway, so really we would need to contact the original author. Textbooks are ok because you are not "translating" the material, or copying it, just implementing the knowledge you obtain from reading it. (Not a laywer disclaimer)

**Comment by Cadair** [comment]
@wafels do you want to pick this up?

**Comment by wafels** [comment]
yes, let me start this up again.

**Comment by Cadair** [comment]
I am going to un-label this as it should be a clean implementation and PR #2186 might take care of it anyway

**Pull request closed without merging**
