### PR TITLE
Add the code of conduct to the documentation

### PR DESCRIPTION
**Pull request by Cadair**
So this adds the code of the conduct to the sphinx build. The downside is it adds a [recommonmark](https://github.com/rtfd/recommonmark) dependency to the sphinx build.

### CODE REVIEW

**Comment by Cadair** [comment]
Allows you to include markdown files in sphinx (docutils)

**Comment by nabobalis** [comment]
We could make the COC rst instead?

**Comment by Cadair** [comment]
We could but then if gh do do something with the code of conduct it won't work.

**Comment by wafels** [comment]
So this complicates our docs build so we can write stuff in two different formats?  Why not rewrite the code of conduct in to RST?  Why do we need .md and .rst files?

**Comment by nabobalis** [comment]
For astropy they have their Licence file in the head directory and it is RST and it is picked up. 

Should we also not do that?

**Comment by dpshelio** [comment]
yeah, I think gh has a good support for rst files. But I don't have any objection on this.

**Comment by nabobalis** [comment]
If we plan to add a dependency, can you update the docs requirements text please.

**Comment by nabobalis** [comment]
Also can you change MAINFEST.md to include the new changelog?

**Comment by nabobalis** [comment]
The CI will fail since I for some reason forgot we dont have a pip version of the theme yet.

**Comment by nabobalis** [comment]
Merge last

**Pull request merged**
