### PR TITLE
Correcting GOES 2 Operational time range

### PR DESCRIPTION
**Pull request by DanRyanIrish**
Hi guys,
This PR changes the start date of GOES 2 in _get_goes_sat_num() sunpy/lightcurve/sources/goes.py so data from 1980 can be read into GOESLightCurve object.

### CODE REVIEW

**Comment by Cadair** [comment]
@DanRyanIrish Could you backport this to the 0.5 branch. Also can you add a changelog entry and a test to make sure it works.

Thanks.

**Comment by DanRyanIrish** [comment]
@Cadair.  Sure.  How do I do that again?

**Comment by dpshelio** [comment]
:+1:

**Comment by DanRyanIrish** [comment]
For a list of dates in the period 1980-2014 for which the GOESLightCurve crashed when you try to create it, see Issue #1337.

**Comment by ehsteve** [comment]
@DanRyanIrish can you update this PR please?

**Comment by DanRyanIrish** [comment]
Sure @ehsteve.  I'll get on this tomorrow or over the weekend.

**Comment by ehsteve** [comment]
Cool. Thanks!

**Comment by Cadair** [comment]
:+1:

**Comment by wafels** [comment]
+1

**Comment by ehsteve** [comment]
:+1:

**Comment by Cadair** [comment]
Needs backporting

**Comment by DanRyanIrish** [comment]
Remind me how to do that again @Cadair.

**Comment by dpshelio** [comment]
@Cadair let's write that down on the docs... this is such a common question

**Comment by Cadair** [comment]
@dpshelio yeah there is an open issue for it assigned to me :s

**Comment by dpshelio** [comment]
@DanRyanIrish I've just made a PR with the documentation on how to do so #1608 
@Cadair I hope this helps to your assignations :stuck_out_tongue_closed_eyes:

**Pull request merged**
