### PR TITLE
Added tests for stereo sources

### PR DESCRIPTION
**Pull request by rupak0577**
Closes issue #1173

### CODE REVIEW

**Comment by Cadair** [comment]
please correct me if I am wrong but `HIMap` (https://github.com/sunpy/sunpy/blob/master/sunpy/map/sources/stereo.py#L72) is missing tests?

**Comment by rupak0577** [comment]
@Cadair yes, sorry but I was not sure about the fits file for HIMap.

**Comment by Cadair** [comment]
@rupak0577 Yes, it does seem like I have not added one. I will try and sort it out for you.

**Comment by Cadair** [comment]
superseded #1598

**Pull request closed without merging**
