### PR TITLE
Using urlsplit in scraper

### PR DESCRIPTION
**Pull request by abhijeetmanhas**
`urlsplit` used in scraper for `_ftpfileslist` and `filelist` function to make code more interpretable.

### CODE REVIEW

**Comment by abhijeetmanhas** [comment]
`ftp.cwd` seems giving error. Making changes accordingly.

**Comment by nabobalis** [comment]
I feel like a change like this needs some sort of extra test for the scrapper.

**Comment by abhijeetmanhas** [comment]
@nabobalis what particular functionality we need to check? I mean this is an internal change using an external library, there is already `test_ftp` function in `test_scraper.py`, which checks only length of the response, adding one more assert to check correctness of string of urls returned will be enough?

**Comment by nabobalis** [comment]
You said that `ftp.cwd` was giving errors, was that picked up by a test? 
If we change how we parse urls, we should make sure we check that the resulting url is still correct.

**Comment by abhijeetmanhas** [comment]
`ftp.cwd` was giving error before its correction commit because I initially passed wrong directory path to it. Now I have corrected it and it no longer gives error.  I checked the argument passed to it is exaclty same as that in master branch. 

So I guess just matching the final urls and returned by ftp and asserting they are as expected shall be enough.

**Comment by abhijeetmanhas** [comment]
> You said that `ftp.cwd` was giving errors, was that picked up by a test?
> If we change how we parse urls, we should make sure we check that the resulting url is still correct.

@nabobalis I have added test to check resulting url is correct. Any more changes?

**Comment by nabobalis** [comment]
Looks fine to me.

**Comment by nabobalis** [comment]
Thanks again @abhijeetmanhas

**Pull request merged**
