### PR TITLE
Added citation info to readme. 

### PR DESCRIPTION
**Pull request by nabobalis**
Fixes https://github.com/sunpy/sunpy/issues/5813

### CODE REVIEW

**Comment by ConorMacBride** [comment]
Do we want to add a link to the sidebar? https://github.blog/2021-08-19-enhanced-support-citations-github/

**Comment by nabobalis** [comment]
Yeah I can add that.

**Comment by nabobalis** [comment]
Found one.

**Comment by nabobalis** [comment]
I shoved the bibtex citation into https://citation-js.github.io/cff-generator/ to create the file.

**Comment by nabobalis** [comment]
The check_skip check is failing?

**Comment by ConorMacBride** [comment]
Yeah, I'm taking a look. I think the default git fetch may not be fetching enough.

**Comment by ConorMacBride** [comment]
Found the problem. GitHub now seem to be fetching with `--depth=1` by default. Should be able to override in the upstream template. (This should not be broken for PRs from forks as I run an extra git fetch for those already.)

**Review by dstansby — APPROVED** [review]

**Pull request merged**
