### PR TITLE
Doctest fixes

### PR DESCRIPTION
**Pull request by bsipocz**
What's better than spending the bank holiday with clearing up the holiday leftovers :) 

During the holidays I was thinking about a 🎄 🎁 in the  form of  doctest fixes, but at the end I didn't get very far with it, but probably it's still better to be submitted than hidden on my hard drive.

### CODE REVIEW

**Comment by Cadair** [comment]
@bsipocz Thanks for the PR!

 can you rebase to fix the CI please?

**Comment by bsipocz** [comment]
@Cadair - Done

**Comment by Cadair** [comment]
Thanks

**Comment by Cadair** [comment]
👍

**Pull request merged**
