### PR TITLE
Fix #2626 error on calling MapCube.plot()

### LINKED ISSUE #2626: Error when calling plot method on MapCube
Calling the plot method on a MapCube leads to an error and subsequently the animation can't be saved to a video a minimal script to reproduce error is below.

Python: 3.6
Matplotlib: 2.2.2
Astropy: 3.0.2
Sunpy: 0.9.0

```python 
from astropy import units as u

from sunpy.net import Fido, attrs as a
from sunpy.map import Map

results = Fido.search(a.Time('2013/07/06 09:30', '2013/07/06 09:31'), a.Instrument('aia'), a.Wavelength(171 * u.angstrom))
    
downloaded_files = Fido.fetch(results)

map_cube = Map(downloaded_files, cube=True)

ani = map_cube.plot()
# Crash here, stack trace below
#ani = map_cube.peek().get_animation() # This works but have progress bars cover axis
ani.save('test.mp4')
```

```python
TypeError                                 Traceback (most recent call last)
<ipython-input-18-ab15991fbba2> in <module>()
     12 ani = map_cube.plot()
     13 #ani = map_cube.peek().get_animation() # This works but have progress bars cover axis
---> 14 ani.save('test.mp4')

~/.virtualenvs/gen/lib/python3.6/site-packages/matplotlib/animation.py in save(self, filename, writer, fps, dpi, codec, bitrate, extra_args, metadata, extra_anim, savefig_kwargs)
   1193                 for anim in all_anim:
   1194                     # Clear the initial frame
-> 1195                     anim._init_draw()
   1196                 for data in zip(*[a.new_saved_frame_seq() for a in all_anim]):
   1197                     for anim, d in zip(all_anim, data):

~/.virtualenvs/gen/lib/python3.6/site-packages/matplotlib/animation.py in _init_draw(self)
   1748         # artists.
   1749         if self._init_func is None:
-> 1750             self._draw_frame(next(self.new_frame_seq()))
   1751
   1752         else:

~/.virtualenvs/gen/lib/python3.6/site-packages/matplotlib/animation.py in _draw_frame(self, framedata)
   1770         # Call the func with framedata and args. If blitting is desired,
   1771         # func needs to return a sequence of any artists that were modified.
-> 1772         self._drawn_artists = self._func(framedata, *self._args)
   1773         if self._blit:
   1774             if self._drawn_artists is None:

~/.virtualenvs/gen/lib/python3.6/site-packages/sunpy/map/mapcube.py in updatefig(i, im, annotate, ani_data, removes)
    206             if wcsaxes_compat.is_wcsaxes(axes):
    207                 im.axes.reset_wcs(ani_data[i].wcs)
--> 208                 wcsaxes_compat.default_wcs_grid(axes)
    209             else:
    210                 im.set_extent(np.concatenate((ani_data[i].xrange.value,

TypeError: default_wcs_grid() missing 2 required positional arguments: 'units' and 'ctypes'
```

### PR DESCRIPTION
**Pull request by samaloney**

### CODE REVIEW

**Comment by samaloney** [comment]
As this was a regression I should probably add a test as well? Even just ensuring the plot method can be called with out throwing an error?

**Comment by Cadair** [comment]
It seems our CI dosen't like saving mp4s: https://travis-ci.org/sunpy/sunpy/jobs/377301507#L2727

I wonder what's the lowest overhead way to save an animation? Can you save to gif?!

**Comment by samaloney** [comment]
Yea I notice that, ha trying to write to gif here at the moment will see how I get on. It's strange I get error when I try the plot command  in an interactive session but when I do the same in the test runner it doesn't fail the test 😕 

```
map_cube.plot()
plt.show()
plt.show()
Traceback (most recent call last):
  File "/Users/shane/.virtualenvs/sunpy-dev/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 388, in process
    proxy(*args, **kwargs)
  File "/Users/shane/.virtualenvs/sunpy-dev/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 228, in __call__
    return mtd(*args, **kwargs)
  File "/Users/shane/.virtualenvs/sunpy-dev/lib/python3.6/site-packages/matplotlib/animation.py", line 1026, in _start
    self._init_draw()
  File "/Users/shane/.virtualenvs/sunpy-dev/lib/python3.6/site-packages/matplotlib/animation.py", line 1750, in _init_draw
    self._draw_frame(next(self.new_frame_seq()))
  File "/Users/shane/.virtualenvs/sunpy-dev/lib/python3.6/site-packages/matplotlib/animation.py", line 1772, in _draw_frame
    self._drawn_artists = self._func(framedata, *self._args)
  File "/Users/shane/Projects/sunpydev/sunpy/map/mapcube.py", line 206, in updatefig
    wcsaxes_compat.default_wcs_grid(axes)
TypeError: default_wcs_grid() missing 2 required positional arguments: 'units' and 'ctypes'
```

**Comment by Cadair** [comment]
oh it's probably not calling `update` unless the save method actually finishes?

**Pull request merged**
