### PR TITLE
Fixed the default database URL to work on Windows

### LINKED ISSUE #1240: Fix default database url under windows.

### PR DESCRIPTION
**Pull request by ayshih**
Closes #1240

### CODE REVIEW

**Comment by Cadair** [comment]
is there not a urllib.urljoin or something?

**Comment by ayshih** [comment]
The problem is that the variable for the user's home directory can already have backslashes in it

**Comment by ayshih** [comment]
Rather, the output of `_get_home()`

**Comment by ayshih** [comment]
I'm closing this PR because the underlying bug appears to be a visual one with no actual impact.  I feel it's safer and cleaner to not modify the URL string if it's not necessary.

**Pull request closed without merging**
