### PR TITLE
Increases timeout for two tests

### LINKED ISSUE #2728: Increase the speed of some tests
# Background
On some platforms -- ARM with soft floating point (32 bit little endian, MIPS (32 and 64 bit, little and big big endian), I get the following error:
```
__________________________________ test_query __________________________________

LCClient = <sunpy.net.dataretriever.sources.goes.XRSClient object at 0xffdd5b4b50>

    @example(a.Time("2006-08-01", "2006-08-01"))
>   # This example tests a time range with a satellite jump and no overlap
    @example(a.Time("2009-11-30", "2009-12-3"))
    @given(goes_time())
    def test_query(LCClient, time):
E   Timeout: Ran out of time before finding a satisfying example for test_query. Only found 4 examples in 83.49s.

sunpy/net/dataretriever/tests/test_goes_ud.py:67: Timeout
----------------------------- Captured stderr call -----------------------------
hypothesis_temporary_module_9db9d383196d4b2cd045dddb4905a97c211288e7:67: HypothesisDeprecationWarning: Test took 41442.50ms to run. In future the default deadline setting will be 200ms, which will make this an error. You can set deadline to an explicit value of e.g. 41500 to turn tests slower than this into an error, or you can set it to None to disable this check entirely.
/usr/lib/python2.7/dist-packages/hypothesis/core.py:1002: HypothesisDeprecationWarning: Your tests are hitting the settings timeout (60.00s). This functionality will go away in a future release and you should not rely on it. Instead, try setting max_examples to be some value lower than 4 (the number of examples your test successfully ran here). Or, if you would prefer your tests to run to completion, regardless of how long they take, you can set the timeout value to hypothesis.unlimited.
  state.run()
---------------------------------- Hypothesis ----------------------------------
You can add @seed(302934307671667531413257853548643485645) to this test or run pytest with --hypothesis-seed=302934307671667531413257853548643485645 to reproduce this failure.
 1 failed, 1229 passed, 182 skipped, 34 deselected, 1 xfailed, 1 xpassed in 878.31 seconds 
```

The test happens (presumably) on a non-connected machine. However, these machines are relatively slow.

Full log (for MIPS 64 bit) [here](https://buildd.debian.org/status/fetch.php?pkg=sunpy&arch=mips64el&ver=0.9.2-1&stamp=1534372518&raw=0).

Other slow tests.
```
test_offline_fido(query)
test_fido_indexing(queries)
test_fido_iter(queries)
test_repr(query)
```

We also added (https://github.com/sunpy/sunpy/pull/2897)  `@settings(deadline=None, suppress_health_check=[HealthCheck.hung_test])` to several slow tests to allow them to pass.

# What we need

These tests to be either split up into smaller tests, or speed up the tests, or allow them to timeout properly.

### PR DESCRIPTION
**Pull request by nabobalis**
Should fix #2728

### CODE REVIEW

**Comment by Cadair** [comment]
This should probably have a misc changelog entry.

**Comment by olebole** [comment]
I just observed the problem in a few more cases: 
* `test_offline_fido(query)`
* `test_fido_indexing(queries)`
* `test_fido_iter(queries)`
* `test_repr(query)`

Since the problem appears in the setup, it would probably useful to increase the timeout there, not in the settings.

**Comment by nabobalis** [comment]
I used pytest-timeout instead now.

**Comment by Cadair** [comment]
pytest timeout wont help right? This is a hypothesis issue no?

**Comment by nabobalis** [comment]
Well it should increase the timeout for all tests probably. The timeout setting in hypothesis is going away.

**Comment by Cadair** [comment]
my point is the tests are not getting killed by pytest they are getting killed by hypothesis because it's taking too much time to generate inputs. I don't think this will help.

The "proper" solution I think is to try and improve the hypothesis strategies rather than just let them take forever :stuck_out_tongue:

**Comment by nabobalis** [comment]
Well nevermind then.

**Comment by Cadair** [comment]
I think the original patch would work fwiw.

**Comment by nabobalis** [comment]
Well its gone now. Never to come back.

**Pull request closed without merging**
