### PR TITLE
Remove un-used test data

### PR DESCRIPTION
**Pull request by dstansby**
xref https://github.com/sunpy/sunpy/issues/4823. This was done using the following script:

```python
from pathlib import Path
import subprocess

test_data_dir = Path('sunpy/data/test')
for child in test_data_dir.iterdir():
    if child.is_file():
        res = subprocess.run(["grep", "-r", f"'{child.name}'", "sunpy/"], capture_output=True)
        if not res.stdout:
            print(child)
            child.unlink()
```

### CODE REVIEW

**Review by nabobalis — APPROVED** [review]

**Comment by nabobalis** [comment]
Is that right?!

**Comment by dstansby** [comment]
It does seem like a lot! Lets see if the tests pass...

**Comment by dstansby** [comment]
😆 my original script was a bit too eager, I think this is more like it.

**Comment by nabobalis** [comment]
What did you change in the script?

**Comment by nabobalis** [comment]
Ah we have some database tests that use the test dir files, they just need updating.

**Comment by Cadair** [comment]
Can you modify the `.gitattributes` file so files with the `.fit` extension classify as binary? This diff show's it is missing.

**Review by Cadair — APPROVED** [review]

**Comment by dstansby** [comment]
> Can you modify the `.gitattributes` file so files with the `.fit` extension classify as binary? This diff show's it is missing.

It looks like `*fit` is already in `gitattributes.

**Pull request merged**
