### PR TITLE
modify memory-mapping arguments based on installed version of asdf

### PR DESCRIPTION
**Pull request by zacharyburnett**
## PR Description

follow-on to https://github.com/asdf-format/asdf/pull/1797
follow-on to #7737

### CODE REVIEW

**Comment by zacharyburnett** [comment]
waiting for #7740 for testing

**Comment by nabobalis** [comment]
Is it ok if I cherry pick this commit and add it to my PR? 

Since due to the correct asdf versions, it will fail without this patch?

**Comment by zacharyburnett** [comment]
> Is it ok if I cherry pick this commit and add it to my PR?
> 
> Since due to the correct asdf versions, it will fail without this patch?

sure, go ahead!

**Comment by nabobalis** [comment]
This has been cherry-picked into https://github.com/sunpy/sunpy/pull/7740

Thanks for fixing it!

**Pull request closed without merging**
