### PR TITLE
Issue#4768

### LINKED ISSUE #4768: You have to specify seconds on the time string arguments to a.Time now
I could have sworn you didn't used to have to do this.

### PR DESCRIPTION
**Pull request by abhishekpandey1880**
### Description
Added a time format of type `"2020/10/01T00:00"` in `TIME_FORMAT_LIST` array in `sunpy/time/time.py`

Fixes #4768

### CODE REVIEW

**Review by hayesla — APPROVED** [review]
Thanks @abhishekpandey1880 - it might be good to also add a small test here https://github.com/sunpy/sunpy/blob/master/sunpy/time/tests/test_time.py

**Comment by nabobalis** [comment]
Tests need adding to the attrs to make sure that `a.Time` works as intended.

**Review by nabobalis — CHANGES_REQUESTED** [review]
Tests are missing.

**Review by nabobalis — APPROVED** [review]

**Comment by dstansby** [comment]
This is a new feature that changes behaviour (parsing the format, instead of erroring), so I've removed 2.0 backport label.

**Comment by dstansby** [comment]
(p.s. thanks a lot for the PR!)

**Comment by abhishekpandey1880** [comment]
Is it hard to implement tests or I did something wrong?

**Comment by nabobalis** [comment]
> Is it hard to implement tests or I did something wrong?

No you did nothing wrong, what you added was 100% correct. I deemed this pull request important enough to complete for our upcoming release and I take over as a result. 

Sorry for the confusion! Please work on other issues!

**Pull request merged**
