### PR TITLE
theme broke the conf

### PR DESCRIPTION
**Pull request by nabobalis**
Fix for the doc build.

### CODE REVIEW

**Comment by nabobalis** [comment]
This will be broken on the 3.0/3.1 builds, but if we dont really plan to do a release, it wont matter.

**Comment by Cadair** [comment]
https://github.com/sunpy/sunpy/runs/6356705018?check_suite_focus=true#step:8:761 balls

**Comment by Cadair** [comment]
We should adjust the theme test build to build in parallel

**Comment by nabobalis** [comment]
For now, we pulled the theme version causing a problem and will do this again in future.

**Pull request closed without merging**
