### PR TITLE
makes map.plot use the mask property if present

### PR DESCRIPTION
**Pull request by wafels**
It is often handy to show maps with masked data, say NaNs or where certain limits are exceeded.  This pull request allows users to use the mask property of the sunpy map in the same way that matplotlib's imshow function does when given a masked numpy array.  See http://matplotlib.org/examples/pylab_examples/image_masked.html for an example of how to set the color table to show masked data.

### CODE REVIEW

**Comment by wafels** [comment]
the only failure is a sphinx error in sunpy/cython_version.py.

**Comment by Cadair** [comment]
:+1:

**Comment by Cadair** [comment]
This is pretty simple, can we have a review and then we can get it into 0.6.

Also @wafels changelog please.

**Comment by aringlis** [comment]
I tested this out on a few different solar image maps. Looks good to me :+1:

**Comment by Cadair** [comment]
Ok, to save @wafels doing it, I will rebase this and merge it manually.

**Comment by Cadair** [comment]
merged.

**Pull request closed without merging**
