### PR TITLE
resample hmi jp2 file

### PR DESCRIPTION
**Pull request by nabobalis**
The original file was by 410 by 410 so I made it 512 by 512, a nicer number we can all agree on.

Oh and made the WCS not be this:

old_hmi

It now looks like:

new_hmi

### CODE REVIEW

**Comment by nabobalis** [comment]
This brings up a test case, do we want to validate our test data via figure tests?

**Comment by nabobalis** [comment]
WE HAD THIS AS A FIGURE TEST AND WE NEVER NOTICED?

**Comment by wtbarnes** [comment]
Out of curiosity what did you do to fix the wcs? What was the problem?

**Comment by nabobalis** [comment]
I downloaded the original file from Helioviewer, opened it, resampled it and saved it out.

**Comment by wtbarnes** [comment]
Ah ok so our original file was just messed up somehow.

**Review by wtbarnes — APPROVED** [review]

**Pull request merged**
