### PR TITLE
Ran VACUUM command to shrink annotation_ppt sqlite database.

### LINKED ISSUE #1350: test_lyra.py uses annotation_ppt.db which is 7Mb in size.
This should be deleted.

### PR DESCRIPTION
**Pull request by aringlis**
This closes #1350. The database itself only contained a few entries, but had retained its original 7MB file size. Ran the VACUUM sqlite command to force-shrink the file.

### CODE REVIEW

**Comment by Cadair** [comment]
@aringlis what's the file size now?

**Comment by aringlis** [comment]
~3KB

**Comment by ayshih** [comment]
Whoa

**Comment by Cadair** [comment]
:+1:

**Pull request merged**
