### PR TITLE
Add more information to non-registration errors in AttrWalker

### PR DESCRIPTION
**Pull request by dstansby**
This needs test, but I'm opening it now so I don't forget it.

### CODE REVIEW

**Comment by dstansby** [comment]
Ready for review; if required I can add a changelog and/or test, but at test might be quite tricky...

**Comment by nabobalis** [comment]
You don't want this backported?

**Review by nabobalis — APPROVED** [review]

**Comment by dstansby** [comment]
🤷 I'm not too fussed

**Comment by nabobalis** [comment]
Just thinking if you wanted this to make dev easier on a released version for a client.

**Pull request merged**
