### PR TITLE
Modify sample_at_coords method to accept other interpolation methods

### PR DESCRIPTION
**Pull request by OussCHE**
I wrote a draft that might solve the issue #6827 . I saw that @ayshih  just added a new PR #6882 that modifies sample_at_coords(which I can add to the PR).

If you accept the draft, I will start writing the unit tests (and finally modify the examples)

### CODE REVIEW

**Comment by OussCHE** [comment]
I think I should modify some examples to account for the change of interpolation methods. I will also need to add tests for corner cases (when coordinate to sample is at at corners Pixel for example) . Would appreciate your feedback.

PS. I also tried to solve the merge conflict

**Comment by OussCHE** [comment]
pre-commit.ci autofix

**Comment by nabobalis** [comment]
If you can add unit tests, that would be great.

**Comment by tien-vo** [comment]
Hi, I'm interesting in picking this up again.

**Comment by nabobalis** [comment]
Sure go ahead @tien-vo

**Pull request closed without merging**
