### PR TITLE
Fix Travis Builds

### PR DESCRIPTION
**Pull request by nabobalis**
Fix deprecation warning for sphinx-gallery, stolen from [here](https://github.com/astropy/astropy/commit/5966e5ff10fd63419c85442b198a3250a5a38462).
Seems not to error locally, let us see if Travis agrees.  

Also, we have the occasional error on this:
```python

@example(a.Time("1983-05-01", "1983-05-02"))

E           ValueError: No operational GOES satellites on 1983-05-01 00:00:00
sunpy/net/dataretriever/sources/goes.py:55: ValueError
```
I'm not sure why it  fails but it isn't all the time, it seems random almost.
So my proposed fix would be marking that with a pytest decatator.
@pytest.mark.xfail(raises=ValueError).

What confuses me is the example date is after GOES 2 but before GOES 5 based on the goes_operational dictionary. #Abovemypaygrade

### CODE REVIEW

**Comment by nabobalis** [comment]
In addition, Pands 0.20.1 broke some code which I have also fixed.

**Comment by wafels** [comment]
This should be restarted as the fails were due to temporary VSO issues.  The pandas fixes are needed for recent PRs such as #2079

**Comment by nabobalis** [comment]
Looks like there are several online database test which are failing.

**Comment by wafels** [comment]
I think the pandas fix is important enough that we should release it ASAP
as the current version of sunpy does not work with the current version of
pandas shipped with anaconda.

The fail also points out that we should pay more attention to our
dependencies' deprecation warnings.

**Comment by nabobalis** [comment]
@wafels  I will be releasing a bugfix today hopefully. 

I will try to fix any warnings like that in a separate PR down the line.

**Pull request merged**
