### PR TITLE
Change default hek spatial region

### PR DESCRIPTION
**Pull request by wafels**
Changed the hektemplate file to expand the default search region for the HEK (so that CMEs show up without having to manually extend the spatial search), and to put the new number formatting style in the template file.  Used the hek_mkcls.py file to implement the changes.

### CODE REVIEW

**Comment by wafels** [comment]
Answers #1411

**Comment by Cadair** [comment]
:+1:

**Comment by ayshih** [comment]
:+1:

**Comment by Cadair** [comment]
manually pushed into 0.6

**Pull request merged**
