### PR TITLE
Show only headings in gallery sidebar

### LINKED ISSUE #4501: The gallery has no easy to read table of contents
https://docs.sunpy.org/en/stable/generated/gallery/index.html has no easy to read table of contents, listing each of the gallery sections. Ideally I think the table of contents in the LH sidebar shouldn't have links to the specific examples, but adding a table of contents at the top would also work.

### PR DESCRIPTION
**Pull request by Cadair**
fixes #4501

@dstansby is this what you had in mind?

### CODE REVIEW

**Comment by Cadair** [comment]
This is a little more hacky than I would have liked. With some modifications to the theme repo it might be able to be made better.

**Comment by nabobalis** [comment]
What would need changing the theme?

**Comment by wtbarnes** [comment]
I think there is overlap here with sunpy/sunpy-sphinx-theme#117

**Comment by dstansby** [comment]
Yes, this is what I had in mind. I think https://github.com/sunpy/sunpy-sphinx-theme/pull/117 might be a nicer solution though.

**Comment by Cadair** [comment]
I am not sure there is a one size fits all solution here, imo sunpy/sunpy-sphinx-theme#117 is too shallow for the dev guide. so i think we end up doing this either for the gallery and making sunpy/sunpy-sphinx-theme#117 depth 3 or we keep sunpy/sunpy-sphinx-theme#117 and then do this for code ref. either way it's a bit messy.

what I think might work is iterating here using this approach with the previews and the sections and then work out what the right pr to the gallery is.

**Comment by nabobalis** [comment]
I have copied this to the theme repo.

**Pull request closed without merging**
