### PR TITLE
changed all c3 to c2

### PR DESCRIPTION
**Pull request by resakra**
Changed all c3 to c2; including detector = a.Detector.c3 to detector = a.Detector.c2
To remove c3 from the file name, throw a warning of Untracked file/directory in visual studio code.

### CODE REVIEW

**Comment by nabobalis** [comment]
This looks good to me but could you also rename the example?

**Comment by ayshih** [comment]
Given the second line in the OP, I presume that @resakra doesn't know how to use `git mv` or the equivalent.

**Comment by nabobalis** [comment]
> Given the second line in the OP, I presume that @resakra doesn't know how to use `git mv` or the equivalent.

Ah woops, I missed that.

**Comment by nabobalis** [comment]
If you run:

`git mv examples/acquiring_data/downloading_lascoC3.py examples/acquiring_data/downloading_lascoC2.py' that should work.

**Review by nabobalis — APPROVED** [review]

**Comment by resakra** [comment]
Sure! 

> > Given the second line in the OP, I presume that @resakra doesn't know how to use `git mv` or the equivalent.
> 
> Ah woops, I missed that.

**Comment by resakra** [comment]
Oops! Did I unintentionally closed the pull request?

**Review by wtbarnes — APPROVED** [review]

**Comment by nabobalis** [comment]
Thanks @resakra!

**Comment by resakra** [comment]
Thank you all! It was my first contribution, really Happy!

**Pull request merged**
