### PR TITLE
Removed message from tools hek

### PR DESCRIPTION
**Pull request by nabobalis**
Fixes https://github.com/sunpy/sunpy/issues/6526

This was removed in 3.1.0 and we forgot to update the tools template, which I think needs to be deleted?

### CODE REVIEW

**Comment by dstansby** [comment]
Is this template still used? I tried running `tools/hek_mkcls.py` on this branch and it didn't seem to do anything.

**Comment by dstansby** [comment]
(sorry, I accidentally pressed close instead of comment...)

**Comment by nabobalis** [comment]
Honestly, I don't really recall how it works. 

I will delete it and see what happens and PR the results.

**Review by dstansby — APPROVED** [review]

**Comment by dstansby** [comment]
Merging this to get 4.1 out the door, can try and delete it in another PR

**Pull request merged**
