### PR TITLE
trying to revive coveralls report

### PR DESCRIPTION
**Pull request by dpshelio**
This is an attempt, still work in progress, to see whether we revive coveralls, which has been dead since Apr.

### CODE REVIEW

**Comment by Cadair** [comment]
@dpshelio can you rebase this to give it a kick up the whatsit?

**Comment by Cadair** [comment]
@dpshelio this wont work till the online build is passing. Something seems to have changed in one of the queries.

**Comment by dpshelio** [comment]
@Cadair #1591 should fix the online run, and then we could check whether this works.  However, I haven't found yet where the coverall files is created when running locally... Let's see if now it works.

**Comment by dpshelio** [comment]
This still requires to upload the coverage to coveralls...

**Comment by Cadair** [comment]
@dpshelio can you rebase this?

**Comment by dpshelio** [comment]
rebased... but I still thinks this needs to add something more - I have to figure it out...

**Comment by Cadair** [comment]
@dpshelio it is triggering coveralls, which is a start. Seems to be uploading a lot of nothing though.

**Comment by dpshelio** [comment]
@Cadair yeah, that's what was happening before, but now also app-veyour is not there...

**Pull request closed without merging**
