### PR TITLE
compositemap.py added a set_minmax_alpha function

### PR DESCRIPTION
**Pull request by abit2**
issue https://github.com/sunpy/sunpy/issues/1697 asked for the functionality where in the composite map max and min threshold of each layer can be set.

### CODE REVIEW

**Comment by abit2** [comment]
@dpshelio please review

**Comment by abit2** [comment]
error of Quantified code is for draw_grid function

**Comment by dpshelio** [comment]
@abit2 I probably confused you by saying that this is similar to the alpha setting. `vmin` and `vmax` in matplotlib do not change the alpha value (that's the transparency) but the min and max value used in the colour table, such that all the values about maximum (or below minimum) would look saturated.
To do this you need to save such properties inside each map so `plot` can pass it as a `params` when called.

**Comment by abit2** [comment]
@dpshelio so for red, blue, green tuple need to check all values with threshold and save the new data in a new tuple make a new layer and return
correct me if wrong??

**Comment by dpshelio** [comment]
@abit2 you don't need to go within each colour - play with [this `matplotlib` example](http://matplotlib.org/examples/pylab_examples/pcolor_demo.html) changing the `vmin` and `vmax` for each plot and you will understand what they do and what I mean.

**Comment by Cadair** [comment]
This needs updating due to #1906, please reopen if you push more commits

**Pull request closed without merging**
