### PR TITLE
Pathlib Functionalities added

### PR DESCRIPTION
**Pull request by darthgera123**
### Description

Added pathlib functionalities in files with testing. Need a review before i progress further. Also i have specifically not touched astropy_helper files since i have no ways of testing the changes there
Fixes issue #2822

### CODE REVIEW

**Comment by nabobalis** [comment]
@pep8speaks quiet 

I am not sure what has happened yet, but it seems your changes cause some problems with our tests.

**Comment by darthgera123** [comment]
yeah one change. i ll fix it. could you just check if the rest of the files are inline

**Comment by nabobalis** [comment]
So I have a few comments/suggestions.

First, you change to pathlib over os, you can remove the `import os` if it isn't used in a file.
Second, I thought the API for pathlib is `pathlib.Path(path).exists()` and not `pathlib.Path.exists(path)`.
Thirdly, I don't think we want to use the full import of `pathlib.Path`. `Path` should be enough, which would require changing the import a bit.  

The next stage after those comments would to be tackle the file input and output which might be a large job.

**Comment by darthgera123** [comment]
yeah that was the error there. I forgot to change the exists thing in one file. Actually i wanted to ask how to test my changes in files which dont have unit tests written for them like the entire astropy helpers sub module and other files

**Comment by nabobalis** [comment]
Ignore the astropy helpers sub module. We do not make any changes there. 

I do not just mean `exists`, I mean for any and all extra calls on pathlib. I think you got the API mixed up. 

What do you mean by test your changes specially? As I can see, so far the changes are just in our test files which means if they still run and pass, they are ok.

**Comment by darthgera123** [comment]
yes so for the files which dont have unit tests written how do i test my changes. Also in some files i had syntax errors or something(for testing) but the test didnt figure them. Lastly i would be grateful if you could point out where i have mixed up the calls Ill fix them all of them. Thanks

**Comment by nabobalis** [comment]
I also suggest undoing the changes to `ah_bootstrap.py`. I think but I would have to check but we need that to be python 2 compatible.  Just focus on files inside the sunpy folder for now. 

You mean unit tests for your current changes? As far as I can tell with a quick glance, the changes right now focus on our tests and as such if you just run them that should be enough.

If there are functions that lack unit tests that deal with input and output, we will have to write those. 

It happens every place you have done `Path.something`, those methods (`exists,is_dir` etc) should be called on the Path instance and not class.

**Comment by darthgera123** [comment]
sorry didnt notice the name. Thanks for the help. Ill make the remaining changes within a day or 2

**Comment by nabobalis** [comment]
That is fine, there is no rush!

**Comment by darthgera123** [comment]
@nabobalis  i am getting permission denied errors while running the tests. Could you please help me out

**Comment by darthgera123** [comment]
the errors are on os.remove

**Comment by nabobalis** [comment]
Permission denied? Could you expand on that?

**Comment by darthgera123** [comment]
sorry to bother but i fixed it. However could you please help me out on why my test is failing. Im not able to figure it out.

**Comment by nabobalis** [comment]
Well to start, you need to redo the rebase for this pull request. It seems to have picked up commits that do not belong here.

`git remote add upstream https://github.com/sunpy/sunpy.git`
`git remote update`
`git rebase -i upstream/master`

should clear it. 

Secondly, undo all the changes in `ah_bootstrap.py`, this file comes from outside and should not be changed unless it is necessary. The same goes for `setup.py`, this file should not be changed. 

Doing this should fix your test failures.

**Comment by darthgera123** [comment]
Thanks a lot

**Comment by nabobalis** [comment]
What are the commands you are running for the rebase/merging in master?

**Comment by darthgera123** [comment]
im using git rebase master on the first branch

**Comment by nabobalis** [comment]
Closed in favour of #2891

**Pull request closed without merging**
