### PR TITLE
run isort on the whole codebase

### PR DESCRIPTION
**Pull request by Cadair**
Thought it might be interesting to automatically sort all the imports, it sorts them by length then by alphabetically I think.

### CODE REVIEW

**Comment by nabobalis** [comment]
Looks ok.

**Comment by vn-ki** [comment]
Someone wants to break master. :laughing:

**Comment by nabobalis** [comment]
I wonder if this should be done after we have purged master of Py2.7 and all the extra imports and code. 

Maybe along side the PEP8 fixes too.

**Comment by nabobalis** [comment]
I think once we sort out master, @Cadair just reopen it and rebase onto master. I think the settings you came up with are what we want.

**Comment by Cadair** [comment]
hang on, let me open a PR with just the config, at least people can use it in their editors then.

**Pull request closed without merging**
