### PR TITLE
Instantiate Map with an array and a WCS object 

### PR DESCRIPTION
**Pull request by nitinkgp23**
This PR fixes issue #2005 

This is possible now :
```
import sunpy.map
from sunpy.data.sample import AIA_171_IMAGE
from astropy.wcs import WCS
from astropy.io import fits

wcs = WCS(AIA_171_IMAGE)
array = fits.getdata(AIA_171_IMAGE)

aia = sunpy.map.Map(array, wcs)
```

### CODE REVIEW

**Comment by nitinkgp23** [comment]
Can someone review and help me go ahead? I can successfully create a map object, but some data are lost while converting WCS object into header.

**Comment by wafels** [comment]
This capability needs a test in test_map_factory.py .

**Comment by Cadair** [comment]
This also needs to perform the reverse mapping from these three extra attributes that Map adds to WCS objects it returns: https://github.com/sunpy/sunpy/blob/master/sunpy/map/mapbase.py#L241

You need to lookup the code for those properties and then read those attributes (if they are present) into the metadata keys the map properties read them from.

**Comment by wafels** [comment]
Relatedly, see also #2278, #1832, #1549 and #1155 .

**Comment by Cadair** [comment]
I will re-open this and finish it up.

**Comment by himanshukgp** [comment]
Hello @Cadair   Is there something I can do in this issue ?

**Pull request closed without merging**
