### PR TITLE
Fix problem with regex and abbreviated months

### LINKED ISSUE #1619: get_url_for_time_range function in stereo.py in dataretriever not working correctly.
The following query:-

``` python
from sunpy.time.timerange import TimeRange
from sunpy.net.vso.attrs import Time, Instrument
from sunpy.net.dataretriever.client import QueryResponse
import sunpy.net.dataretriever.sources.stereo as stereo

LCClient = stereo.HETClient()
urls = LCClient._get_url_for_timerange(TimeRange('2008/12/01','2010/12/01'),'ahead', 15*u.min)

```

Should return a non-empty list of urls but instead returns an empty list. Possible problem stems from the implementation of scraper.py in sunpy.util. The scraper doesn't work as intended on http://www.srl.caltech.edu/STEREO/DATA/HET.

### PR DESCRIPTION
**Pull request by dpshelio**
Fix #1619 - also tests added for this situation

Also adds milliseconds to the possible patterns.

### CODE REVIEW

**Comment by bsipocz** [comment]
@dpshelio - Running this exact same branch on my fork passes the tests, so it may be just a fluke? https://travis-ci.org/bsipocz/sunpy/builds/148693630

Have you tried to restart that failing run?

**Comment by dpshelio** [comment]
Restarting failed run - though that particular run is failing in all the PR for the last... 12 days :(

**Comment by bsipocz** [comment]
Weird, it doesn't fail for me.

**Comment by dpshelio** [comment]
It worked now :) !!!!

**Comment by bsipocz** [comment]
Well, the good old trick (turn it off and on again) works often with travis ;)

**Comment by dpshelio** [comment]
@sunpy/sunpy-developers please, review, this is needed in some PRs in the unidown

**Pull request merged**
