### PR TITLE
Remove all usage of distutils as it is now deprecated

### PR DESCRIPTION
**Pull request by Cadair**
### Description

Fixes #<Issue Number>

### CODE REVIEW

**Comment by dstansby** [comment]
I'm guessing this is worth backporting? It does introduce a new runtime dependency though...

**Comment by Cadair** [comment]
We could get away without backporting it, but it's probably a good idea. It should be noted that astropy has also introduced this runtime dep as well.

**Review by dstansby — DISMISSED** [review]
Should probably add a changelog to notify users of the new dependency, even if it is likely that they already have it installed.

**Review by nabobalis — APPROVED** [review]
Changelog has been added.

**Comment by nabobalis** [comment]
Backported to 3.0 manually.

**Pull request merged**
