### PR TITLE
Changing doc builddir location

### PR DESCRIPTION
**Pull request by bsipocz**
As discussed in #1455 this PR changes the location of the builddir of the documentation.
At the end it was quite simple to move it without moving any of the source files, or changing which one is the sphinx root dir.
Would this need a changelog entry?

ping: @Cadair, @ehsteve

### CODE REVIEW

**Comment by bsipocz** [comment]
Moving the generated ``api`` dir brakes the links somehow. I don't exactly see why, so move that commit to a separate branch.
Anyway one can argue that there is logic keeping that directory under source as those generated ``rst`` files are sources, even though auto generated ones.

**Comment by Cadair** [comment]
@bsipocz Keeping the api folder is source is a good idea. Could you also rename `_build` to just `build` now it is not inside the source dir?

**Comment by bsipocz** [comment]
@Cadair - done

**Comment by Cadair** [comment]
A changelog entry would be great. Otherwise :+1:

**Comment by bsipocz** [comment]
@Cadair - Changelog added.

**Comment by Cadair** [comment]
@sunpy/sunpy-maintainers review please.

**Comment by dpshelio** [comment]
Looks good to me! :+1:  Thanks @bsipocz

**Pull request merged**
