### PR TITLE
[map_branch] Moved data methods on mapbase to deprecated mixins

### PR DESCRIPTION
**Pull request by hayesla**
Removed following data methods from mapbase and put it in deprecated mixins:
```
.ndim
.dtype
.std
.mean
.min
.max
.dimensions (encourage users to use .shape)
```

### CODE REVIEW

**Comment by DanRyanIrish** [comment]
Does anyone understand what's triggering [these warnings](https://github.com/sunpy/sunpy/actions/runs/8855574415/job/24320698766?pr=7592#step:10:1921) in the doc build?  The traceback is not very informative.

**Comment by DanRyanIrish** [comment]
And thanks to @nabobalis for fixing this PR.

**Comment by nabobalis** [comment]
Hopefully those doc fails are now fixed. I amend the last commit with the tweaks.

**Review by DanRyanIrish — APPROVED** [review]

**Comment by DanRyanIrish** [comment]
Thanks so much @hayesla and @nabobalis.  Merging this now!

**Pull request merged**
