### PR TITLE
Add a roll manuever aia image to the sample data

### PR DESCRIPTION
**Pull request by Cadair**

### CODE REVIEW

**Comment by Cadair** [comment]
I have already added the data to data.sunpy.org.

**Comment by ayshih** [comment]
Looks good, glad to have this for `rotate()` testing! :+1:

**Comment by ehsteve** [comment]
@ayshih sample files are not meant to be used for testing! If you really need that file it should go in the testing folder for sure.

**Comment by Cadair** [comment]
It's useful for manual testing. We probably should also add a version of it to the test data.

**Comment by ayshih** [comment]
Note that there already is a downsampled AIA test file with a non-zero `CROTA2` value – the angle is very small (0.02 degrees) because it's not from a roll maneuver – which should (in theory) be sufficient for unit tests.

I like this good-resolution file with a large `CROTA2` value to be in the sample files for testing by humans (i.e., someone wanting to see with their own eyes that SunPy does what it advertises) and for gallery generation.

**Comment by ehsteve** [comment]
:+1:

**Comment by wafels** [comment]
+1

**Pull request merged**
