### PR TITLE
Make the database FITS reader be FITS time compliant.

### PR DESCRIPTION
**Pull request by Cadair**
This is primarily a bug fix to make the database correctly read `DATE-BEG` and `DATE-END` as specified in the FITS Time spec http://adsabs.harvard.edu/abs/2015A%26A...574A..36R

It needed a little reworking of the FITS reader to make it respect the priorities as required by the standard. I also could not let the units import live.

### CODE REVIEW

**Comment by Cadair** [comment]
@Alex-Ian-Hamilton reported this, I would like him to test it before we merge.

**Comment by Cadair** [comment]
noooo not stale bot.

**Comment by dpshelio** [comment]
I gave my approval!!

**Comment by Cadair** [comment]
yeah but it also broke all the tests lol

**Pull request closed without merging**
