### PR TITLE
Attempt to correctly read observer locations for MDI and EIT

### LINKED ISSUE #2430: Map not recognizing EIT coordinates.
Something is messed up with the EIT map coordinates. The meta data and WCS looks OK at first glance, but the coordinate grid isn't being translated properly. 

`from sunpy.map import Map`
`eit=Map(sunpy.data.sample.EIT_195_IMAGE)`
`eit.peek()`

eit_example

### LINKED ISSUE #3040: MDI observer longitude not properly extracted from header
The MDI FITS header has the observer Carrington longitude under the keyword `OBS_L0` (and `L0`) rather than `CRLN_OBS`, so our code currently misses this information and assumes an Earth-based observer.  We shouldn't use this value blindly, however, because I have reasons to be skeptical about Carrington-longitude calculations.  The good news is that the FITS header *also* has the Earth Carrington longitude under the keyword `EARTH_L0`, and the *difference* of the two longitudes should be an accurate observer Stonyhurst longitude.

### PR DESCRIPTION
**Pull request by Cadair**
### Description

This is inspired by #3056 and conversations around it. This changes the SoHo sources so they do not actually modify the header, but implement the properties needed to override things.

Fixes #2430 and fixes #3040 

This now builds on #3115

### CODE REVIEW

**Comment by ehsteve** [comment]
See issue #3070.

**Comment by ayshih** [comment]
Need to fix this to use HeliocentricMeanEcliptic instead of HeliocentricTrueEcliptic for Astropy 3.2 (see #3066 and #3075)

**Comment by ayshih** [comment]
Your MDI implementation doesn't fix #3040.  It looks like you've put their value for Carrington longitude where the Stonyhurst longitude should go.

I believe our options are to trust their Carrington longitude (which I don't like because I can't match Stonyhurst-Carrington transformations exactly), we try to calculate a Stonyhurst longitude by subtracting two header values (which at first glance doesn't give accurate results), or we kludge it by saying that the Stonyhurst longitude is zero and document that kludge.

**Comment by Cadair** [comment]
@ayshih I went with the convert to stonyhurst approach. It seems the least kludgy? We already actually do that in mapbase by default: https://github.com/sunpy/sunpy/blob/master/sunpy/map/mapbase.py#L606 which is maybe something we might want to consider?! (HMI uses it as they don't have HGS in the header)

**Comment by ayshih** [comment]
I think you made the right choice, but it's an uncomfortable choice since I still don't trust HGC coordinates (see #2224).  For cross-reference purposes, #3057 contains my anxiety over HMI.

**Comment by Cadair** [comment]
I think this test fail might actually be real.

**Comment by Cadair** [comment]
@ayshih It seems that the distance for EIT isn't coming out right by doing this, which is causing the fails in the differential rotation code.

**Comment by ayshih** [comment]
@Cadair I've pushed the fix

**Comment by Cadair** [comment]
oh dear :woman_facepalming: oh dear oh dear oh dear.

**Pull request merged**
