### PR TITLE
Minimal example of OpenBLAS-associated matrix-multiplication bug on macOS

### PR DESCRIPTION
**Pull request by ayshih**
Extracted from #4293

### CODE REVIEW

**Comment by Cadair** [comment]
close?

**Comment by ayshih** [comment]
Most definitely should not be closed.  MacOS bug still present (29 out of 500 multiplications gave the wrong answer).  I still need to figure out how to winnow down the cause and/or shotgun report it.

**Comment by ayshih** [comment]
Even though the test run on this PR still has OpenBLAS pinned:
```
libopenblas               0.3.9                h3d69b6c_0    conda-forge
```
the test run for #4384 shows that this minimal test also still fails on the latest conda-forge build:
```
libopenblas               0.3.10          openmp_h63d9170_4    conda-forge
```

**Comment by ayshih** [comment]
Summary of tests:

### Pass
```
libopenblas               0.3.12          openmp_h54245bb_1    conda-forge
```
```
libopenblas               0.3.10               h0794777_0
```
(note that this build isn't a conda-forge build, so likely may not be built for multi-threading)
### Fail
```
libopenblas               0.3.10          openmp_h54245bb_5    conda-forge
```
```
libopenblas               0.3.10          openmp_h63d9170_4    conda-forge
```
```
libopenblas               0.3.9                h3d69b6c_0    conda-forge
```

**Pull request closed without merging**
