### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by nabobalis**
My attempt at fixing conda on azure.

### CODE REVIEW

**Comment by Cadair** [comment]
looks fine, but what's going on with `_sqlite3`?!

**Comment by nabobalis** [comment]
Oh i forgot about that. I will need to track that down before I can merge this.

**Comment by nabobalis** [comment]
I think someone broke the linux python 3.7 in the azure image.

**Comment by Cadair** [comment]
Yeah I found this: https://developercommunity.visualstudio.com/content/problem/598264/known-issue-azure-pipelines-images-missing-sqlite3.html

There is a work around described through a couple of comment clicks on that page.

**Comment by Cadair** [comment]
ok I have no idea what that fail is all about.

**Comment by nabobalis** [comment]
Thanks @Cadair

**Pull request merged**
