### PR TITLE
Fix gallery documentation links

### PR DESCRIPTION
**Pull request by dstansby**
This is most (maybe all?) of the broken documentation links in the gallery.

### CODE REVIEW

**Review by nabobalis — APPROVED** [review]

**Comment by slim-patchy** [comment]
Please unsubscribe me from all your mailing lists! I have left your org already

**Comment by slim-patchy** [comment]
@akirahirohito

**Comment by slim-patchy** [comment]
As I said, I am not a solar physics specialist

**Comment by slim-patchy** [comment]
You are banned from my world too

**Comment by slim-patchy** [comment]
For my husband

**Comment by nabobalis** [comment]
Do we want to backport this to 2.0 manually?

**Comment by dstansby** [comment]
🤷 it's not that important

**Pull request merged**
