### PR TITLE
removing instances of `sunpy as spy`

### PR DESCRIPTION
**Pull request by dpshelio**

### CODE REVIEW

**Comment by Cadair** [comment]
There was a reason for this. A raw `import sunpy` was breaking the automodapi documentation generator. It will be interesting to see if this bug is still there.

**Comment by dpshelio** [comment]
Uuuhh... I see, well, if this fails, then we should add a comment about that in there :)

**Comment by Cadair** [comment]
well the doc build seems to have worked so, it looks like it's good.

:+1:

**Comment by ehsteve** [comment]
@Cadair what is happening? I thought the standard was that two :+1: were needed for a PR to be accepted.

**Comment by dpshelio** [comment]
@ehsteve #1564 was approved by two people; which is the same than this but for 0.6

**Pull request merged**
