### PR TITLE
Firehose on the CI. 

### PR DESCRIPTION
**Pull request by nabobalis**
I see nothing but fire. 

To put out said fire, I removed one CI file.

### CODE REVIEW

**Comment by nabobalis** [comment]
`E   ImportError: cannot import name '_validate_lengths' from 'numpy.lib.arraypad' (/opt/conda/lib/python3.7/site-packages/numpy/lib/arraypad.py)`

Waiting for an upstream fix. That will plague the pip build until then.

**Comment by nabobalis** [comment]
It is time we turned off appy.

**Comment by nabobalis** [comment]
`ValueError: No online HELIO servers can be found.`
The Goes Time test failed. 
`docs/guide/acquiring_data/database.rst` also failed.

**Comment by dpshelio** [comment]
🤷 @nabobalis the 👨‍🚒

**Comment by Cadair** [comment]
Should we back port the hypothesis fixes?

**Comment by nabobalis** [comment]
OH PLEASE NO. 
WHY DO YOU MAKE ME REMEMBER 0.9

**Pull request merged**
