### PR TITLE
Changed fermi test values

### PR DESCRIPTION
**Pull request by aringlis**
@Cadair I changed the values in the Fermi tests - the file that was being downloaded had changed, which was why the values were different now.

When I run the test in isolation it passes, but when I run the sunpy test suite this one fails with the error:

    IOError: [Errno ftp error] 200 Type set to I

As far as I can understand this has something to do with FTP being set to passive mode - does that make sense to you?

### CODE REVIEW

**Comment by aringlis** [comment]
Just to clarify, it's ```test_detector_angles()``` that fails, which is doubly weird because the preceeding test ```test_download_weekly_pointing_file()``` uses the same download routine and passes.

**Comment by Cadair** [comment]
Seems to pass ok. (I cancelled the Mac build because it's taking forever). Why did the file it was downloading change?

**Comment by aringlis** [comment]
@Cadair the file change dates back to PR #1739 where the FTP site used for Fermi pointing files was updated. Prior to #1739 draft/planned pointing files were being downloaded instead of the actual final ones.

**Comment by Cadair** [comment]
:+1:

**Pull request merged**
