### PR TITLE
Handles Missing 'FILLVAL' Attribute in CDF Variables to Prevent TimeSeries Crash

### PR DESCRIPTION
**Pull request by Prtm2110**
## PR Description
Solves: #7565

### CODE REVIEW

**Comment by Prtm2110** [comment]
Writing the test for handling missing FILLVAL in CDF files is getting tricky. Can you point me in the right direction? Also, do I need to add unit test support for this?

**Comment by nabobalis** [comment]
> Writing the test for handling missing FILLVAL in CDF files is getting tricky. Can you point me in the right direction? 

If we can get the file or something similar as presented in the issue, we can test against that assuming it's a small file. Is that what you were having issues with?

>Also, do I need to add unit test support for this?

Can you clarify what you mean by unit test support?

**Comment by Prtm2110** [comment]
> If we can get the file or something similar as presented in the issue, we can test against that assuming it's a small file. Is that what you were having issues with?

Yes, I’ll work on it.

> Can you clarify what you mean by unit test support?

Sorry, I meant unit support.

**Comment by nabobalis** [comment]
> Sorry, I meant unit support.

Can you expand on this?

**Comment by Prtm2110** [comment]
> Can you expand on this?

```
WARNING: SunpyUserWarning: astropy did not recognize units of "eV/cm2-s-ster-eV". Assigning dimensionless units. If you think this unit should not be dimensionless, please raise an issue at https://github.com/sunpy/sunpy/issues [sunpy.io._cdf]
2024-09-09 00:33:10 - sunpy - WARNING: SunpyUserWarning: astropy did not recognize units of "eV/cm2-s-ster-eV". Assigning dimensionless units. If you think this unit should not be dimensionless, please raise an issue at https://github.com/sunpy/sunpy/issues
```

**Comment by nabobalis** [comment]
Thats not a problem, we should try to parse them in the future but I don't think we should worry about that in this PR.

**Comment by nabobalis** [comment]
Thanks for the PR @Prtm2110, I will close this for now, if you want to add unit tests for this, please reopen this and we can review it again

**Pull request closed without merging**
