### PR TITLE
Backport 5786 to 3.0

### PR DESCRIPTION
**Pull request by dstansby**
Backport #5786 to 3.0

### CODE REVIEW

**Comment by dstansby** [comment]
I'm pretty sure I got the merge conficts right, but don't have the motivation to work out what's going wrong in the tests, so someone else can fix it if they are motivated to get this backported.

**Comment by nabobalis** [comment]
I'll try to work thorugh it now.

**Comment by nabobalis** [comment]
So updating the map via `smap.meta.update(cd)` breaks the `.wcs` of the map.

**Comment by nabobalis** [comment]
I can't get the pc tests to pass with the same trick. Tho removing the trick, the test passes locally. I am quite confused.

**Pull request closed without merging**
