### PR TITLE
Update base Norh URL

### PR DESCRIPTION
**Pull request by nabobalis**
See if this works.

### CODE REVIEW

**Comment by exitflynn** [comment]
welp im beginning to think they might not have just announced a new URL yet, nothing of that sort comes up for the past year when you search `Nobeyama Radioheliograph  "ftp"`

**Comment by exitflynn** [comment]
i've figured out why this is still failing and it exposes an edge-case that is not accounted for in the Scraper, which would be of clients having `http`-baseurls and serving data in extension-less files. `_httpfilelist()` looks for URLs at a directory's webpage [ending with the same extension as the pattern](https://github.com/sunpy/sunpy/blob/main/sunpy/net/scraper.py#L290) (like `.fits`, etc) before parsing it further. This wasn't a problem before since the source was ftp then and it's straightforward to get a list of files in a directory. i could work on fixing this if it'd be more convenient that way, let me know!

**Review by ayshih — APPROVED** [review]
I think it'd be good to have a (trivial) changelog entry

**Comment by nabobalis** [comment]
Added the changelog.

**Comment by nabobalis** [comment]
Thanks for the review @ayshih

**Pull request merged**
