### PR TITLE
GOES: Fixes an issue where timestamps containing leap seconds could not be converted to Python datetimes

### PR DESCRIPTION
**Pull request by mariusgiger**
## PR Description

- Fixes an issue where timestamps containing leap seconds could not be converted to Python datetimes (XY is within a leap second but datetime does not support leap seconds) #5422
- Exposes GOES quality flags as it is not possible to decide whether a given value is faulty otherwise (refer to https://satdat.ngdc.noaa.gov/sem/goes/data/science/xrs/GOES_13-15_XRS_Science-Quality_Data_Readme.pdf)

Example of faulty values (See X class values):
download

### CODE REVIEW

**Comment by mariusgiger** [comment]
Likely conflicting with https://github.com/sunpy/sunpy/pull/5834

**Comment by hayesla** [comment]
Hi @mariusgiger - I haven't properly looked into this yet, but was this not fixed by https://github.com/sunpy/sunpy/pull/5915
 or is this another issue?

**Comment by mariusgiger** [comment]
> Hi @mariusgiger - I haven't properly looked into this yet, but was this not fixed by #5915 or is this another issue?

Hi @hayesla, thanks for writing back to me. Unfortunately, this did not fix it. The issue can be reproduced with the following example using Sunpy v4.0.1:

```
from sunpy import timeseries as ts
from sunpy.net import Fido
from sunpy.net import attrs as a

t_start = "2015-06-30 00:00"
t_end = "2015-07-01 00:00:00"
search_result = Fido.search(
                        a.Time(t_start, t_end), a.Instrument.xrs)
download_result = Fido.fetch(search_result)
goes_ts = ts.TimeSeries(download_result, concatenate=True)
df = goes_ts.to_dataframe()
print(df)
```

which will result in 

```
ValueError: Time (array(2015, dtype=int32), array(6, dtype=int32), array(30, dtype=int32), array(23, dtype=int32), array(59, dtype=int32), array(60, dtype=int32), array(965000, dtype=int32)) is within a leap second but datetime does not support leap seconds
```

I am not well versed in Astropy Times, so there might be a better way to drop/convert the leap seconds. 

Cheers,
Marius

**Review by dstansby — CHANGES_REQUESTED** [review]
Thanks for opening this PR. Sadly I don't think this is the right way to go - we shouldn't be dropping data from the file before returning it to the user! Unfortunately this means storing our data using not pandas, which there are plans to do, but it's a bit complicated which is why we haven't done it yet (see https://github.com/sunpy/sunpy/pull/5834 for work in progress)

**Comment by mariusgiger** [comment]
@dstansby thanks for the reply! I agree, however it is currently not working - so depending on when the refactoring is done, you might still want to consider to merge this. 

Regarding the second point, it would be great to have access to the quality flags in order to filter the timeseries by quality as there are quite a few corrupt data points.

**Comment by mariusgiger** [comment]
Ok thanks for the feedback - I have moved access to the quality flags to another PR #6260. @dstansby it would be great if `sunpy.timeseries.GenericTimeSeries.to_dataframe` would not fail in the future if the underlying Astropy TimeSeries contained leap seconds (for ease of use). Do you think this is achievable? Maybe a filtering mechanism as was proposed here could be used.

**Comment by nabobalis** [comment]
The issue here is not `to_dataframe`, it fails in the loading of the file. So we will need to patch that first. 

Then for `to_dataframe`, I think we need to add keyword that will allow a user to get dataframe out without leap seconds.

**Comment by nabobalis** [comment]
> @nabobalis yes sure this is the case currently, however in the future the file loading will no longer involve pandas if I got it correctly.

That is true, hopefully for 4.1
 
> Such a flag would be great 👍

We will make sure add such a flag for the refactor of timeseries.

**Comment by nabobalis** [comment]
I have what I hope is a solution to your problem @mariusgiger here: https://github.com/sunpy/sunpy/pull/6262 
Your example code now works.

It will take a few days for it to be reviewed and released in a bugfix release.

**Pull request closed without merging**
