### PR TITLE
Database changes to fix online build

### PR DESCRIPTION
**Pull request by Cadair**
Simple and effective.

### CODE REVIEW

**Comment by Cadair** [comment]
@sunpy/sunpy-developers review please.

**Comment by dpshelio** [comment]
:+1: this database is making me crazy... how come we are loosing flares?

**Comment by Cadair** [comment]
@dpshelio I have no idea, I think we need to re-write the test so that the test does the HEK query and then checks that the database adds the same number of entries as the HEK query retuned.

**Comment by dpshelio** [comment]
Well... I'm trying the same query with [QHEK](https://github.com/dmlabdmlab/QueryHEK) and I'm getting 0 results, so there's something wrong somewhere.
And if I do the same in [iSolSearch](https://www.lmsal.com/isolsearch?hek_query=https://www.lmsal.com/hek/her?cosec=2&&cmd=search&type=column&event_type=fl&event_region=all&event_coordsys=helioprojective&x1=-5000&x2=5000&y1=-5000&y2=5000&result_limit=120&event_starttime=2011-08-09T07:23:56&event_endtime=2011-08-09T07:24:00) I get 6... which are not in such time range.

In any case... the fact we are getting thousands is worrying...

**Comment by dpshelio** [comment]
All right, if I do a `temporalmode=strict` in [iSolSearch](https://www.lmsal.com/hek/her?cosec=2&&cmd=search&temporalmode=strict&type=column&event_type=fl&event_region=all&event_coordsys=helioprojective&x1=-5000&x2=5000&y1=-5000&y2=5000&result_limit=120&event_starttime=2011-08-09T07:23:56&event_endtime=2011-08-09T07:24:00&return=event_starttime,event_endtime) I get 0 like in QHEK

**Comment by Cadair** [comment]
@dpshelio That should probably be opened in a new issue. This we should merge so the build passes.

**Pull request merged**
