### PR TITLE
Adds support for np.datetime64 and strings with timezone info

### PR DESCRIPTION
**Pull request by ankitkmr**
This offers a solution to the issue #798

### CODE REVIEW

**Comment by ankitkmr** [comment]
@dpshelio Finally added support for np.datetime64 input which I guess the issue was about in the first place. Also added support for input strings with timezone information. Added Test Cases supported also solved the problem of possible multiple '-' in time_string

**Comment by dpshelio** [comment]
@ankitkmr why did you closed the other PR? You could have just updated it... Well, my comments from #1343 still apply here, e.g., there is repetition in the code that should be reduced.
The tests have to go in the tests files and using pytest. Check [SunPy's dev documentation](http://sunpy.readthedocs.org/en/latest/dev.html#testing) for more details on how to do it.  And please, update the pull request by updating the branch where you are doing the changes, not closing and opening a new one each time.

**Comment by ankitkmr** [comment]
@dpshelio Umm sorry I couldn't figure out back then that I could simply commit and update that PR in itself. It wont happen in future. As for the repetition check closely I changed the condition for '-' from '+' now we are 
<td class="blob-code blob-code-addition"><b class="add-line-comment octicon octicon-plus js-add-line-comment js-add-single-line-comment" data-path="sunpy/time/time.py" data-anchor="diff-e4d7773dc71c1ca30c1741901255ba37" data-position="35" data-line="207" role="button" aria-label="Add line comment"></b>+        <span class="pl-k">elif</span> <span class="pl-s"><span class="pl-pds">'</span>-<span class="pl-pds">'</span></span> <span class="pl-k">in</span> time_string[<span class="pl-c1">9</span>:] :</td>
 for '-' but time_string for '+'
And yeah I'll do the test cases sorry didn't know that thats how its supposed to be done !! in the meanwhile I made up the blog let me know if its ok !! 

http://home.iitk.ac.in/~ankitkmr/blog/

**Comment by ankitkmr** [comment]
@dpshelio  OK I condensed it even more I agree too much useless code there !! Oops..I added the tests as well according to the dev guide. They can be found in PR1345 (new PR) this I guess happened because I was committing to a new file.

**Comment by dpshelio** [comment]
No, they are not in a different pul request because you've made changes in different files, but because you made the changes in a different branch.  If you do it in the same branch you would see it here.
I would suggest you to close the new PR #1345 and cherrypick the commit you did into this branch `ankitkmr-patch-3`

So, probably you could do (I've not tested it):
```bash
$ git checkout ankitkmr-patch-3
$ git cherry-pick 1821096
$ git push 
```

**Comment by ankitkmr** [comment]
@dpshelio Done !!

**Comment by wafels** [comment]
As written, the code requires timedelta to be imported explicitly in order for this PR to pass.

**Comment by ankitkmr** [comment]
Thanks @wafels  just noticed that and added its import to the test_time.py file

**Pull request closed without merging**
