### PR TITLE
Warn when assuming CUNIT in map sources

### PR DESCRIPTION
**Pull request by dstansby**
I was taking a look at map sources and to see examples of fixing metadata, and it struck me that there should probably be a warning if anything is being assumed that isn't being cross checked against other present header keys.

### CODE REVIEW

**Comment by dstansby** [comment]
I updated this to cover all places where this is happening.

**Comment by Cadair** [comment]
I am not sure on this, I understand your logic, we are making assumptions about the metadata. However, isn't making assumptions about the metadata the entire point of the Map sources? In the AIA map we choose to read the position info from other keys, in the HMI map we fix something I think, to me this is the point, we know that if `INSTRUME = rhessi` then the units are missing but the file is in those units because that's what the documentation (lololol) for that data says it is?

**Comment by dstansby** [comment]
I would agree if there was some sort of cross check against other (non-standard) FITS keys, or an link to some documentation, but in all these cases the assumption is completely blind.

**Comment by Cadair** [comment]
We can't really check things which are non-standard reliably, and I am game for better documentation. I am not really in favour of throwing these warnings at the users when there is nothing they can do (or would want to do) to remove them. I think if we are not careful with warnings they will confuse new users and make users ignore the important ones we throw at them.

**Comment by Cadair** [comment]
I am not sure where the best place to document this is, maybe just in the docstrings for the sources?

**Pull request closed without merging**
