### PR TITLE
Fix database test

### PR DESCRIPTION
**Pull request by dstansby**
I'm not sure why this has changed remotely, but it has, so update the filename we test against.

### CODE REVIEW

**Comment by nabobalis** [comment]
I saw on some CI but sometimes it was passing and locally as well. I was quite confused.

**Review by nabobalis — APPROVED** [review]

**Comment by nabobalis** [comment]
The test failed with:

```
        # 2 entries from rhessi
>       assert entries[66].fileid.endswith("/metadata/catalog/hsi_obssumm_20120101_016.fits")
E       AssertionError: assert False
E        +  where False = <built-in method endswith of numpy.str_ object at 0x7f0f275d3d50>('/metadata/catalog/hsi_obssumm_20120101_016.fits')
E        +    where <built-in method endswith of numpy.str_ object at 0x7f0f275d3d50> = 'http://hessi.ssl.berkeley.edu/hessidata/metadata/catalog/hsi_obssumm_20120101_032.fits'.endswith
```

The test is sometimes returning the other file?

**Comment by dstansby** [comment]
Boooo. I've updated the test to check the part of the filename that isn't changing (but still contains a timestamp)

**Comment by dstansby** [comment]
🥳

**Pull request merged**
