### PR TITLE
Fix body spec in get_horizons_coord

### PR DESCRIPTION
**Pull request by dstansby**
Fixes https://github.com/sunpy/sunpy/issues/6550

### CODE REVIEW

**Review by ayshih — CHANGES_REQUESTED** [review]
Blocking until I interact with the JPL HORIZONS folks

**Comment by dstansby** [comment]
I definitely think it's a good idea to chat to JPL Horizons, but isn't making this clearer ("Sun" instead of "10") still a change worth making?

**Comment by dstansby** [comment]
Ah, just seen your comment on matrix:

>  ID# is intended to be the robust way to specify the body.

Is the issue with "Sun" that there's a possiblity that the meaning of "Sun" might change in the future, whereas the meaning of 10 won't change because it's a unique immutable ID?

**Comment by ayshih** [comment]
Not literally a change of meaning of "Sun", but rather the potential addition of other bodies to the database that results in the string "Sun" being an ambiguous identifier.

If it takes a while to get a satisfactory response from the HORIZONS folks, we'll make this change temporarily to restore functionality, but the final implementation should be the formal way to unambiguously specify the Sun, whatever that is.

**Comment by ayshih** [comment]
Closing this PR because the Horizons folks have fixed the bug on their side

**Pull request closed without merging**
