### PR TITLE
Propagate max_conn to fetch methods

### PR DESCRIPTION
**Pull request by dstansby**
Previously this wasn't handed, so for clients that created their own `Downloader` (e.g. JSOC) `max_conn` wasn't respected when passed to `Fido.fetch()`. Not sure what the best way is to add a test for this?

### CODE REVIEW

**Review by nabobalis — APPROVED** [review]

**Comment by nabobalis** [comment]
Looks like it broke.

**Comment by Cadair** [comment]
Doesn't Fido always pass a downloader object to the clients though? I don't think this is needed (or I am misunderstanding what's going on)

**Comment by dstansby** [comment]
Not sure what's really going on underneath, but these changes update the `fetch()` methods to conform to the signature of `BaseClient.fetch()`, which is probably a good thing anyway?

**Comment by dstansby** [comment]
Actual fix in https://github.com/sunpy/sunpy/pull/4567

**Pull request closed without merging**
