### PR TITLE
Removal of response_format keyword from VSOClient.search

### PR DESCRIPTION
**Pull request by nabobalis**
We created this as a workaround back in 2.1 days, in theory this was not public API but we never made that clear in anything.

### CODE REVIEW

**Review by dstansby — CHANGES_REQUESTED** [review]
This should get a deprecation period? Unless there's a very good reason not to do a deprecation?

**Comment by nabobalis** [comment]
> This should get a deprecation period? Unless there's a very good reason not to do a deprecation?

This was never intended to be user facing API. We introduced this when we adding a breaking change to the VSO client to allow the old behaviour but the old behaviour was only used in the hektovso client for reasons I do not remember.  

This removal changes nothing for any of users and for me that does not need a depreciation period. 

If others agree, I can add one but we should pull this out instead of going through the cycle.

**Comment by wtbarnes** [comment]
> This removal changes nothing for any of users and for me that does not need a depreciation period.

You're probably right, but unfortunately, we have no way to know if that is actually true and technically, this is public-facing API.

> If others agree, I can add one but we should pull this out instead of going through the cycle.

From a pragmatic point of view, I agree with you, but departing from our deprecation policy because it is convenient for us is worrying to me.

**Comment by nabobalis** [comment]
In that case, it will be easier for me to depreciate it in a new PR.

**Pull request closed without merging**
