### PR TITLE
FrameAttribute now just Attribute

### PR DESCRIPTION
**Pull request by nabobalis**
Astropy v2 broke SunPy

### CODE REVIEW

**Comment by Cadair** [comment]
FUN WITH LABELS

**Comment by nabobalis** [comment]
Yeah, well when I made the PR it added alot of labels. I also forgot how to use labels.

**Comment by nabobalis** [comment]
Figures test broke since they imported astropy v1.3 as its labelled stable right now.

**Comment by Cadair** [comment]
huhhh, the figure tests have an env file:  https://github.com/sunpy/sunpy/blob/master/sunpy/tests/figure_tests_env_2.7.yml#L11

**Comment by nabobalis** [comment]
I had no idea. That needs to be changed.

**Pull request merged**
