### PR TITLE
Tidy docstring for solar_rotate_coordinate

### PR DESCRIPTION
**Pull request by Cadair**
I noticed this example wasn't as clear as it could have been when I was looking at it because of #2706

### CODE REVIEW

**Comment by tiagopereira** [comment]
When you do

    from sunpy.physics.differential_rotation import solar_rotate_coordinate

`SkyCoord` becomes aware of the helioprojective frame, and it accepts `frame='helioprojective'` instead of `frame=frames.Helioprojective`. Is this behaviour expected to last? If so, you could remove one extra line with the import of `sunpy.coordinates.frame`.

**Comment by Cadair** [comment]
@tiagopereira for reasons I don't entirely agree with we made the decision to use the `frames.whatever` convention in the docs. iirc the main reason was to make the import explicit so that the frames would always be there. I wonder if @wafels or @ehsteve can remember more about the history of that choice.

**Comment by wafels** [comment]
I don't remember....

**Comment by ayshih** [comment]
My thoughts:

- Some import statement ought to be present to show explicit intent.  The casual coder would not have any reasonable expectation that importing `sunpy.physics.differential_rotation` would trigger the registration of SunPy's frames that live under `sunpy.coordinates`.  Even if that behavior is likely to persist indefinitely, we shouldn't take such shortcuts in documentation.
- Showing `frames.Helioprojective` makes it easier to teach others how to feed in SunPy frames with non-default settings (e.g., a non-Earth observer).
- Using `frames.Helioprojective` facilitates static code analysis because you (or an IDE) can trace it back to the explicit import statement that guarantees that the frame exists.

**Pull request merged**
