### PR TITLE
Provide millionths of solar hemisphere unit

### LINKED ISSUE #1851: Provide millionths of solar hemisphere units
a proportion of solar hemisphere is used broadly in sunspots and active regions size measurements. It would be good to include such capability as units within sunpy.

The conversions factors can be found in:
https://www.spaceweatherlive.com/en/help/how-do-you-determine-the-size-of-a-sunspot-region

### PR DESCRIPTION
**Pull request by Telomelonia**
## PR Description
Adds the millionths of solar hemisphere units in the `map` folder

Fixes #1851 

## TODOS
- [ ] changelog
- [ ] make an equivalency func

### CODE REVIEW

**Review by dstansby — CHANGES_REQUESTED** [review]
To start with, please could you update this so the pre-commit check passes? There's instructions on how to do this here: https://docs.sunpy.org/en/latest/dev_guide/contents/code_standards.html#formatting

**Comment by ayshih** [comment]
See https://github.com/sunpy/sunpy/issues/1851#issuecomment-1466646395 for how this PR needs to be modified

**Comment by Telomelonia** [comment]
pre-commit.ci autofix

**Comment by nabobalis** [comment]
Hi @Telomelonia, I am going to close this pull request. If you have time to come back to this, please reopen it.

**Pull request closed without merging**
