### PR TITLE
Fixes Documentation changes due to NumPy 1.14

### LINKED ISSUE #2394: New NumPy update breaks some of the documentation tests
NumPy v1.14.0 updates the way that arrays and numbers are printed to the terminal. As we use this alot in the documentation testing, we have a problem. 

Fixing this will mean running the documentation tests locally, checking the print out and changing the current results to the now expected results. Probably just to simpler to run the documentation code in a terminal and then copy and paste terminal output to the places it needs changing.

### PR DESCRIPTION
**Pull request by yashkgp**
Fixes #2394 
Due to NumPy 1.14 some of the doc tests fails . This PR tries to fix that.

### CODE REVIEW

**Comment by nabobalis** [comment]
The only issue I can see is the the addition of a file called `isuue1.txt`. This should be deleted.

**Comment by Cadair** [comment]
So this means that our doctests will have to be run on numpy >= 1.14 forever more?

I think I am fine with this.

**Comment by Cadair** [comment]
@yashkgp looks like you have a few more to catch: https://travis-ci.org/sunpy/sunpy/jobs/329122396

**Comment by yashkgp** [comment]
I have updated the changes required . Is there any issue with the `pytest` because when I ran the tests locally there were only 10 errors.

**Comment by nabobalis** [comment]
Looks like there are still 3 more.

**Comment by nabobalis** [comment]
@yashkgp Got just three more and we can merge this! 
```
- docs/code_ref/coordinates.rst:109 [doctest] docs/code_ref/coordinates.rst
- docs/guide/tour.rst:266 [doctest] docs/guide/tour.rst
- docs/guide/units-coordinates.rst:152 [doctest] docs/guide/units-coordinates.rst```

**Comment by Cadair** [comment]
@yashkgp If you merge master into this, you should be able to get the builds to pass. Giving you the honor of being the first person to fix the CI in 2018 😆

**Comment by yashkgp** [comment]
@Cadair Would be really honored to be first one to fix a CI in 2018. :laughing:

**Comment by Cadair** [comment]
@yashkgp you seem to still be two short of a perfect score: https://travis-ci.org/sunpy/sunpy/jobs/330429498#L1747

**Comment by nabobalis** [comment]
I wonder why more keep popping up as they get fixed.

**Comment by Cadair** [comment]
because doctests in the narrative docs are one long bit of code, so they fail on the first error. So as you fix them the ones further down the source fail.

**Comment by nabobalis** [comment]
Oh yeah thats how that works. Had to deal with that when I was doing the database doc tests.

**Comment by nabobalis** [comment]
One more! 
`/home/travis/build/sunpy/sunpy/docs/guide/units-coordinates.rst:212: DocTestFailure`

**Comment by Cadair** [comment]
@yashkgp have you got the tests running locally? It might take you some time to make it through the whole narrative docs just using Travis.

**Pull request merged**
