### PR TITLE
Plot directive 0 6 fix

### PR DESCRIPTION
**Pull request by ehsteve**
This PR removes all need for pre-rendered plots by using the plot directive throughout the docs.

### CODE REVIEW

**Comment by Cadair** [comment]
you have an error with one of the plot directives: https://travis-ci.org/sunpy/sunpy/jobs/70832901#L1678

**Comment by ehsteve** [comment]
@Cadair @ayshih @wafels ping

**Comment by Cadair** [comment]
:+1:

**Comment by Cadair** [comment]
Aside:
@ehsteve it looks like you need to add your new email address to github or reconfigure your local git install so it picks you up as author of the commits.

**Comment by ehsteve** [comment]
Would have to edit my commits. Not worth it right now.

**Comment by Cadair** [comment]
@ehsteve do they have any author info?? You could just rebase the branch (I think that would do it).

**Comment by ehsteve** [comment]
I think it just has a slightly different email is all.

**Comment by Cadair** [comment]
@ehsteve ok, in that case you can just add that email to your GH account, so that it connects the commits with your GH account.



fwiw, none of this in anyway should affect the review of this PR!

**Comment by ehsteve** [comment]
Thanks! Done.

**Comment by Cadair** [comment]
:D

**Comment by ehsteve** [comment]
@ayshih this needs to be approved and merged so that the other doc fixes can merge this ASAP.

**Comment by ayshih** [comment]
:+1:

**Pull request merged**
