### PR TITLE
Add an example gallery to the SunPy documentation.

### PR DESCRIPTION
**Pull request by Cadair**
This uses the sphinx-gallery package (which needs configuring).

A build preview is here: http://cadair-sunpy.readthedocs.org/en/gallery/auto_examples/index.html

### CODE REVIEW

**Comment by Cadair** [comment]
@adrn @kelle ping!

**Comment by Cadair** [comment]
@eteq

**Comment by adrn** [comment]
See astropy/astropy#4734 for my PR to astropy

**Comment by theaverageguy** [comment]
@Cadair The build is failing. What might be the reason?

**Comment by Cadair** [comment]
The build is failing due to a quirk of astropy-helpers. I have raised a PR there.

**Comment by dpshelio** [comment]
Sweet! :)

**Comment by Cadair** [comment]
@sunpy/sunpy-maintainers Review please!

**Comment by dpshelio** [comment]
It's a good starting point for our gallery :+1: from my point!

**Comment by wafels** [comment]
+1

**Pull request merged**
