### PR TITLE
Making spectra and net py3 compatible

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by Cadair** [comment]
Thanks @bsipocz !

It seems this has spawned an actual documentation warning.

**Comment by Cadair** [comment]
https://travis-ci.org/sunpy/sunpy/jobs/117851721#L1773

**Comment by bsipocz** [comment]
I almost finished ``net``, too, so will take care of the fails when that's done.

**Comment by Cadair** [comment]
Thanks!

**Comment by bsipocz** [comment]
@Cadair - This is all green and ready to go for now. I've added the py3 builds to the travis matrix with allowing them to fail, so we can see the overall progress.

**Comment by Cadair** [comment]
:+1:

**Comment by ayshih** [comment]
:+1:

**Comment by dpshelio** [comment]
Awesome! Thanks @bsipocz

**Pull request merged**
