### PR TITLE
Unskip non-reprojection examples

### PR DESCRIPTION
**Pull request by dstansby**
xref #4051 - these work fine locally for me.

### CODE REVIEW

**Comment by nabobalis** [comment]
Let's hope the CI agrees.

**Comment by nabobalis** [comment]
```
generating gallery for generated/gallery/plotting... [ 87%] solar_cycle_example.py 
Exception occurred:
 
  File "/root/project/.tox/build_docs/lib/python3.7/site-packages/matplotlib/axis.py", line 1576, in convert_units
 
    f'units: {x!r}') from e
 
matplotlib.units.ConversionError: Failed to convert value(s) to axis units: '2011-01-01'
 
```

Should unskip any others. If we hit memory limits on rtd, we can worry about that later.

**Comment by mbobra** [comment]
This works for me locally too. However, [this comment](https://github.com/sunpy/sunpy/pull/3765#issuecomment-582991873) in #3765 pointed out it fails the doc builds (even though I see it passed here). What was the problem?

**Comment by dstansby** [comment]
I un-un-skipped the solar cycle example, will try and fix that elsewhere

**Pull request merged**
