### PR TITLE
Put parse_time example in an example folder

### PR DESCRIPTION
**Pull request by dstansby**
It is currently by itself at the top: https://docs.sunpy.org/en/latest/generated/gallery/index.html , but probably should be in a folder.

### CODE REVIEW

**Comment by nabobalis** [comment]
Maybe Units and Coordinates?

**Comment by Cadair** [comment]
We could change timeseries to "time and time series"?!

**Comment by nabobalis** [comment]
Seems a bit forced but maybe?

**Comment by Cadair** [comment]
yeah or `Units, Coordinates and Times` might work better?

**Comment by nabobalis** [comment]
I prefer that myself. 
What about `Coordinates, Times and Units`?

**Comment by Cadair** [comment]
sure that does read nicer.

**Comment by nabobalis** [comment]
I forgot how gallery works out the section titles.

**Comment by dstansby** [comment]
I like the efficient decision making! Will update the location/folder title.

**Comment by nabobalis** [comment]
Screenshot from 2019-10-24 17-19-24
Looking good expect the cutoff on my vertical monitor.

**Comment by nabobalis** [comment]
On a larger side note that is even more unrelated to this PR,someone  should fix those online tests.

**Comment by nabobalis** [comment]
Thanks @dstansby

**Pull request merged**
