### PR TITLE
We do need pytest and forgot to pin astropy

### PR DESCRIPTION
**Pull request by nabobalis**
Final fix for RTD.

### CODE REVIEW

**Comment by wtbarnes** [comment]
🤞

**Comment by wtbarnes** [comment]
How should this be backported to fix the 1.0 and 1.1 docs builds?

**Comment by nabobalis** [comment]
I added this to the backport PRs.

**Comment by dstansby** [comment]
Why do we need pytest?

**Comment by nabobalis** [comment]
For this:

```
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunpy/conda/latest/lib/python3.8/site-packages/sunpy/io/special/asdf/extension.py", line 6, in <module>
    from .tags.coordinates import *  # noqa
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunpy/conda/latest/lib/python3.8/site-packages/sunpy/io/special/asdf/tags/coordinates/__init__.py", line 1, in <module>
    from .frames import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunpy/conda/latest/lib/python3.8/site-packages/sunpy/io/special/asdf/tags/coordinates/frames.py", line 5, in <module>
    from astropy.tests.helper import assert_quantity_allclose
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunpy/conda/latest/lib/python3.8/site-packages/astropy/tests/helper.py", line 14, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
```

**Comment by Cadair** [comment]
That should be an astropy object.

**Pull request merged**
