### PR TITLE
Update pandas plotting registration

### PR DESCRIPTION
**Pull request by dstansby**
This is the (probably relatively new??) proper way to register the pandas converters.

### CODE REVIEW

**Comment by nabobalis** [comment]
I added the backport for good measure.

**Comment by Cadair** [comment]
I think it's important to know what the minimum version of pandas this works with is.

**Comment by nabobalis** [comment]
Using git blame on pandas, it seems to be around since the plotting module was created which was 2 ish years ago.

**Comment by Cadair** [comment]
If we are now relying on a min version of pandas, we should update our deps to account for that.

**Comment by nabobalis** [comment]
We should.

**Pull request merged**
