### PR TITLE
Add codecov to travis

### PR DESCRIPTION
**Pull request by dstansby**
At the request of @Cadair, here is codecov. Will probably need an admin to create a codecov account.

### CODE REVIEW

**Comment by nabobalis** [comment]
@Cadair Don't fob off your plans to other people.

**Comment by nabobalis** [comment]
Should we replace the coveralls badge as well?

**Comment by Cadair** [comment]
I just pushed a couple of commits to try and make the build pass.

**Comment by dstansby** [comment]
I might need to add --cov to the testing argument to make this work, but lets see what happens...

**Comment by Cadair** [comment]
I messed up the astropy helpers update, so redid the commits. I am going to leave this alone for a while now lol.

**Pull request merged**
