### PR TITLE
[0.7] Backport of #2062

### PR DESCRIPTION
**Pull request by nabobalis**
This is a backport of #2062. 
For some reason parts of the 0.7.1 changelog were missing?!

### CODE REVIEW

**Comment by Cadair** [comment]
@nabobalis can you pull in the .pep8speaks.yml file from master to shut the bot up as well?

**Comment by Cadair** [comment]
MV

**Comment by nabobalis** [comment]
Done, forgot to CI skip. #ohwell

**Comment by Cadair** [comment]
@nabobalis can you pull in the part 2 of this as well now?

**Comment by nabobalis** [comment]
Will do.

**Pull request merged**
