### PR TITLE
CITATION.txt file added to sunpy

### PR DESCRIPTION
**Pull request by tdwilkinson**
In regards to pull request #1712, this is a citation file that is added to the sunpy files. Currently, it is a text file with information about citing sunpy, and does not print anything if called. I am willing to edit this if the developers would like more.

### CODE REVIEW

**Comment by dpshelio** [comment]
Thanks @tdwilkinson 
I think I would prefer it in markdown, so it's rendered properly within github, and the bibtex block could be highlighted.  Also, the website could take this file to build the site too.

**Comment by tdwilkinson** [comment]
I have updated this file to be .md instead of .txt. It contains all of the links in the initial pull requests.

**Comment by tdwilkinson** [comment]
A preview is available [here](https://github.com/tdwilkinson/sunpy/blob/master/CITATION.md).

**Comment by Cadair** [comment]
@tdwilkinson Can you remove the changes to spectrogram from this?

**Comment by tdwilkinson** [comment]
Hi! Yes, that was for another pull request I am looking into. I have removed my changes to spectrogram, and replaced my sunpy fork to match spectrogram.py in sunpy/spectra.

**Comment by ehsteve** [comment]
@tdwilkinson looks like the changes to spectrogram are still there. Easiest to create a new clean branch and just copy and paste in your citation file and PR that.

**Pull request closed without merging**
