### PR TITLE
Add HEEQ coordinate frame

### LINKED ISSUE #2433: Add HEEQ coordinates frame
Feature request for a heliocentric earth equatorial (HEEQ) coordinates frame. Essentially, this is a "de-tilted" HCC frame with the axes permuted such that the z-axis is aligned with the North Pole of solar rotation axis.

 For more details, see [Thompson (2006)](http://adsabs.harvard.edu/abs/2006A%26A...449..791T) and [Hapgood (1992)](http://adsabs.harvard.edu/abs/1992P%26SS...40..711H).

### PR DESCRIPTION
**Pull request by dstansby**
As part of my foray into astropy coordinates, I thought I'd fix #2433. This probably needs some more tests, and someone else to double check the rotation matrix that I took from http://adsabs.harvard.edu/abs/2006A%26A...449..791T

### CODE REVIEW

**Comment by ayshih** [comment]
Isn't HEEQ just a Cartesian representation of HGS (`HeliographicStonyhurst`)?  See section 2.1 in Thompson (2006).  If that's correct, the HEEQ<->HGS transformations are essentially trivial and would be an even simpler way to implement this coordinate frame.

**Comment by Cadair** [comment]
It's getting late and I have to get up at 4am for a flight.

However, if HEEQ is just Cartesian representation of HGS then we don't need a new frame for it, you just need to do `hgs.cartesian`.

**Comment by Cadair** [comment]
Oh also, if they are the same frame we should add a `RepresentationMapping` for Cartesian so you can easily construct and access HGS as a Cartesian system.

**Comment by Cadair** [comment]
From http://www.srl.caltech.edu/STEREO/docs/coordinate_systems.html :

HEEQ: Heliocentric Earth Equatorial. Z is the solar rotation axis, and X is in the plane containing the Z axis and Earth, at the intersection of the solar central meridian, and the heliographic equator. When converted to longitude and latitude, this is known as Stonyhurst heliographic coordinates.


Also, having another look over the section in Thompson, it looks to me like a straight spherical<>Cartesian transformation.

So, I am going to assume for the moment that they are the same, and review this PR under that assumption!

Firstly, as I already mentioned, we have this coordinate frame, Astropy coordinates separates out the representation of points in space from the frame used to align those points. So this is the HeliographicStonyhurst frame.

Having said that, we should make the HGS frame easier to use in Cartesian mode for people who want to call it HEEQ. This involves adding an entry in the frame_specific_representation_info dict in the HGS frame. Unless I am mistaken this will allow you to construct the frame like: HeliographicStonyhurst(x=, y=, z=) and allow you to access .x etc attributes on the frame even if it was constructed in spherical form.

Given that HGS is the same as HEEQ the transforms in this PR are effectively a different approach to the existing hcc_to_hgs functions. I think having them as dynamic matrix transforms is a a better idea, in terms of efficiency etc. So if we can validate that they are the same I would propose that we replace the existing ones with the ones in this PR.

Having said that, I don't think the approach you have taken with these transforms to HCC is correct. You appear to have assumed the observer is always the Earth. I think the B0 angle you are using needs to be the longitude angle between the earth and the observer, also you will need to take into account the angle of the observer above or below the solar equatorial plane. (Have a look at the existing HGS<>HCC transforms to see what I mean in terms of code).

Thanks for this PR dstansby, I hope the mind bending coordinates stuff doesn't scare you off!

**Comment by dstansby** [comment]
Thanks for all the rapid comments!

Is it worth having a separate HEEQ class so that all three (x,y,z) coordinates are required, instead of defaulting to the solar radius as the radial coordinate? There could just be a trivial transformation between HEEQ and HGS.

re. assuming the observer being the Earth, I thought by definition that the observer was always the Earth in both HEEQ and HGS?

**Comment by Cadair** [comment]
> Is it worth having a separate HEEQ class

I am *really* not in favour of this. We should work within the astropy framework, with PRs to astropy if needed to make this easy to use without adding a duplicate frame.

> so that all three (x,y,z) coordinates are required, instead of defaulting to the solar radius as the radial coordinate?

The HGS frame constructor will only default to solar radius if it is constructed in a way that leads it to being `UnitSpherical`. I.e. you only give it `lon`, `lat`. If we make it possible to construct with x,y,z then it won't do this, because it will be holding a Cartesian or Spherical representation not UnitSpherical.

> re. assuming the observer being the Earth, I thought by definition that the observer was always the Earth in both HEEQ and HGS?

Kinda, the HGS frame is observer independent (uses the Earth-equatorial line, solar north and the solar centre as it's reference points), but HCC isn't, so when transforming in or out of HCC you need to take the position of the observer relative to the Earth equatorial line in to account.

**Comment by Cadair** [comment]
@dstansby can you rebase / merge master into this, I did a bit of refactoring of coordinates in #2431

**Comment by dstansby** [comment]
Okay, this now has a changelog and has been rebased.

**Comment by Cadair** [comment]
@dstansby can you add some tests about instantiating this (both directly as a frame and with `SkyCoord`) so we can see what the UX looks like here? 

I can't remember what the behaviour of both the constructors are with respect to non-default representations.

Otherwise I think this looks great!

**Comment by ayshih** [comment]
Maybe I'm missing something, but contrary to the docstring, I can't seem to instantiate this through keyword arguments, either through directly calling the frame or through `SkyCoord`.  I have to feed a `CartesianRepresentation` into either constructor.

**Comment by Cadair** [comment]
@ayshih what about doing `representation='cartesian'`?

I did wonder if you could do this. I feel like you probably should be able to at least for `SkyCoord` OTOH, the `SkyCoord` constructor already requires years of study to master....

**Comment by ayshih** [comment]
Ah, okay, yes, passing `representation='cartesian'` works for either constructor.  A bit cumbersome...

**Comment by Cadair** [comment]
That looks like what we are stuck with for now, might be worth opening an issue on astropy about this.

**Comment by dstansby** [comment]
I've fixed the docstring, and added some simple tests to make sure the construction works for each case.

**Pull request merged**
