### PR TITLE
Finishing py3 porting

### PR DESCRIPTION
**Pull request by bsipocz**
This will the PR that contains the remaining py3 issues that didn't cause test failures, but may cause errors and headaches later.

First trying to fix the appveyor build (and thus need a PR as I can't do this on my fork), will ping people the PR is ready.

### CODE REVIEW

**Comment by bsipocz** [comment]
@Cadair - This is finished.

**Comment by bsipocz** [comment]
(Appveyor seem to be failing with some odd timeout-like error that is unrelated. We saw it in astropy as well, though didn't understand where it came from. Restarting didn't help (though before restart at least the py2.7 passed: https://ci.appveyor.com/project/sunpy/sunpy/build/0.7.1616).

**Comment by Cadair** [comment]
:+1:

**Comment by nabobalis** [comment]
:+1:

**Pull request merged**
