### PR TITLE
Made GenericMap.plot() arguments keyword only #7166

### PR DESCRIPTION
**Pull request by yeppAniket**
## PR Description
Made the GenericMap.plot() accept keywords only as arguments, As discussed in #7166 and #7163.

### CODE REVIEW

**Comment by nabobalis** [comment]
Thanks for the PR @yeppAniket.

For this to work, we have to add warnings first, this change can not happen without forewarning.
If you have a look at https://github.com/sunpy/sunpy/pull/6406/files for example, that will show you what you should add.

**Comment by yeppAniket** [comment]
> For this to work, we have to add warnings first, this change can not happen without forewarning. 
So I need to add a depreciation warning and update the changelog, right?

**Comment by nabobalis** [comment]
> > For this to work, we have to add warnings first, this change can not happen without forewarning.
> 
> So I need to add a depreciation warning and update the changelog, right?

Yes.

**Comment by yeppAniket** [comment]
> Yes.

from sunpy.util.exceptions import SunpyDeprecationWarning

def test_deprecated_positional_args(map_object, axes):
    with pytest.warns(SunpyDeprecationWarning, match=r"Pass annotate=True as keyword args"):
        map_object.plot(axes=axes, annotate=True)

    with pytest.warns(SunpyDeprecationWarning, match=r"Pass title='interpolation' as keyword args"):
        map_object.plot(axes=axes, title='interpolation')

    with pytest.warns(SunpyDeprecationWarning, match=r"Pass annotate=True, title='interpolation' as keyword args"):
        map_object.plot(axes=axes, annotate=True, title='interpolation')

    with pytest.warns(SunpyDeprecationWarning, match=r"Pass clip_interval=(lower, upper) as keyword args"):
        map_object.plot(axes=axes, clip_interval=(10, 90))

    with pytest.warns(SunpyDeprecationWarning, match=r"Pass autoalign='pcolormesh' as keyword args"):
        map_object.plot(axes=axes, autoalign='pcolormesh')
        
Something like this for the warnings?

**Comment by nabobalis** [comment]
Yeah, you do not need to test it for every keyword, one will be enough.

**Comment by nabobalis** [comment]
Superceded by https://github.com/sunpy/sunpy/pull/7419

**Pull request closed without merging**
