### PR TITLE
[0.9] travis fix?

### PR DESCRIPTION
**Pull request by nabobalis**
See if the 0.9 CI still works. 

TODO:

- [ ] Fix the rest of this

### CODE REVIEW

**Comment by nabobalis** [comment]
Online Fails seem to just be flaky issues. ALso the Python 2 on Travis is due to dependency resolution failing

**Comment by Cadair** [comment]
Where are we pinning numpy >= 1.17?

**Comment by nabobalis** [comment]
In 0.9, we aren't. Something else must be.

**Comment by Cadair** [comment]
I wonder if it's ci-helpers?

**Comment by Cadair** [comment]
https://github.com/astropy/ci-helpers/pull/419/files

I think we need to pin the numpy version to 1.16 for python 2 builds.

**Comment by nabobalis** [comment]
Ill pin it or something.

**Comment by nabobalis** [comment]
Travis Failure: ASTROPY_VERSION='lts' PYTHON_VERSION=3.5 

Another numpy depdency chain issue with conda. Should be ok to ignore.

**Pull request merged**
