### PR TITLE
update rtd config to remove legacy or deprecated options

### PR DESCRIPTION
**Pull request by nabobalis**
Need to wait for RTD to build to check.

### CODE REVIEW

**Review by Cadair — APPROVED** [review]

**Review by dstansby — CHANGES_REQUESTED** [review]
It looks like the `docs` requirements need updating to include `matplotlib`

**Comment by nabobalis** [comment]
> It looks like the `docs` requirements need updating to include `matplotlib`

Done.

**Comment by dstansby** [comment]
Then we should probably update docs, instead of leaving it as dev?

**Comment by nabobalis** [comment]
> Then we should probably update the docs requirements, instead of leaving it as dev?

Will do.

**Pull request merged**
