### PR TITLE
removes incorrect block indices from asdf test data

### PR DESCRIPTION
**Pull request by braingram**
## PR Description

Asdf is making some major updates to internal block reading and writing code (see [this PR](https://github.com/asdf-format/asdf/pull/1537) for the extensive changes).

One of the changes includes issuing a new warning when a file is opened which contains an incorrect block index. The block index is a small, optional YAML document at the end of an ASDF file that contains the offsets of each ASDF binary block within the ASDF file (see the [asdf-standard docs](https://asdf-standard.readthedocs.io/en/1.0.3/file_layout.html#block-index) for more details). Hand editing ASDF files can often lead to incorrect offsets in the block index. When asdf detects a block index that is incorrect (or if no block index is found) it ignores the block index and falls back to reading blocks sequentially starting with the first.

With sunpy main tested against the above asdf PR several tests are failing (see [here for the full log](https://github.com/asdf-format/asdf/actions/runs/5859350013/job/15885164355?pr=1537#step:10:1006)):
```
FAILED sunpy/sunpy/io/special/asdf/tests/test_genericmap.py::test_load_100_file_with_shift - asdf.exceptions.AsdfBlockIndexWarning: Invalid block index contents for block 0, fal...
FAILED sunpy/sunpy/io/special/asdf/tests/test_genericmap.py::test_load_100_file_with_no_shift - asdf.exceptions.AsdfBlockIndexWarning: Invalid block index contents for block 0, ...
==================================================================== 2 failed, 161 passed, 4 skipped in 58.33s 
```

This is due to 2 test files in the sunpy repository that contain block index offsets that are incorrect (see the changed files in this PR).

This PR deletes the invalid block index from each of these files.

### CODE REVIEW

**Comment by braingram** [comment]
It appears that pre-commit is modifying the data files. Perhaps `.pre-commit-config.yaml` could use an exclude line?:
```yaml
exclude: ".asdf"
```

**Comment by nabobalis** [comment]
Yeah, we need to add that to the precommit

**Comment by braingram** [comment]
Thanks! Would you like me to sneak that in here?

**Comment by nabobalis** [comment]
Yes please!

**Comment by nabobalis** [comment]
I wanted to run the devdeps test that requires a label plus reopening a PR. Sorry for the trouble.

**Review by nabobalis — APPROVED** [review]

**Comment by braingram** [comment]
Thanks! @nabobalis

**Pull request merged**
