### PR TITLE
Added test and fits file for HIMap

### PR DESCRIPTION
**Pull request by sudk1896**
Added fits file for HIMap in sunpy/data/test and correspondingly added a test_hi_source.py file.

### CODE REVIEW

**Comment by Cadair** [comment]
:+1: Thanks @sudk1896

**Comment by Cadair** [comment]
@sunpy/sunpy-developers review please.

**Comment by dpshelio** [comment]
:+1:  Great job @sudk1896

**Comment by sudk1896** [comment]
@dpshelio @Cadair  Mucho thanks ! I will be contributing more in a few days!

**Pull request merged**
