### PR TITLE
STEREO/SOHO Unidown

### PR DESCRIPTION
**Pull request by nabobalis**
Honestly, I have no idea.
Updated version of #1678
What changes need to be made for this to be added back? @Cadair @dpshelio 

Do we even want this anymore?

Current WIP:
- [ ] PEP8 Issues
- [ ] Timeseries Port
- [ ] Fido Port everythng
- [ ] Doctests

### CODE REVIEW

**Comment by Cadair** [comment]
> Do we even want this anymore?

Yes

**Comment by dpshelio** [comment]
I'll book some time before holidays to check into this.

**Comment by nabobalis** [comment]
Well Unless you want to do this, I was planning to look into this myself. But I wont stop you

**Comment by dpshelio** [comment]
We can do it together :)

**Pull request closed without merging**
