### PR TITLE
Travis, Conda and NumPy version

### PR DESCRIPTION
**Pull request by dpshelio**
This PR just makes sure that in travis, Conda does not update numpy when installing other packages.  I imagine for appveyour we need the same thing.

### CODE REVIEW

**Comment by dpshelio** [comment]
Now I've removed the latest update of the hashes as it seems they changed due to unnoticeable updates of NumPy on the conda environment.

AppVeyor is also updated accordingly.

NumPy 1.8.1 environment seems to fail due to a problem in numpy as a scimath is not available, though in the numpy manual seems it is...

Another way to solve this would be to, either update numpy versions on travis and appveyor, so we are sure we are testing the version we are testing is the same one.

**Comment by Cadair** [comment]
@dpshelio can we close this in favor of #1629 ??

**Comment by dpshelio** [comment]
wait... why do I have here commits that were not in this PR? have we done something weird?

**Comment by Cadair** [comment]
I don't know, but it doesn't matter right?

**Pull request closed without merging**
