### PR TITLE
Update zenodo.json for 2.1

### PR DESCRIPTION
**Pull request by dstansby**

### CODE REVIEW

**Comment by dstansby** [comment]
👋 hello new contributors! I am updating the list of authors for the zenodo entry (see https://zenodo.org/record/3779284 for a previous example). I have mentioned you because you are new or have moved in the list for the 2.0 release.

If you would like, please leave a comment below with:

    The preferred name you would like to be listed as
    Your ORCID
    Your affiliation

I will then manually add this to the information. Note that none of this is compulsory!

@johan12345 @chouhanaryan @SophieLemos @dipanshu231099 @kathivashkiv @dipanshu231099 @eteq @kots14 @platipo @resakra

**Comment by dipanshu231099** [comment]
>  hello new contributors! I am updating the list of authors for the zenodo entry (see https://zenodo.org/record/3779284 for a previous example). I have mentioned you because you are a new contributor since sunpy 2.0.
> 
> If you would like, please leave a comment below with:
> 
> ```
> The preferred name you would like to be listed as
> Your ORCID
> Your affiliation
> ```
> 
> I will then manually add this to the information. Note that none of this is compulsory!
> 
> @johan12345 @chouhanaryan @SophieLemos @dipanshu231099 @kathivashkiv @dipanshu231099 @eteq @kots14 @platipo @resakra

Name: Dipanshu Verma
ORCID: https://orcid.org/0000-0003-2461-5547
Affiliation: Indian Institute of Technology, Mandi

**Comment by johan12345** [comment]
Name: Johan L. Freiherr von Forstner
ORCID: https://orcid.org/0000-0002-1390-4776
Affiliation: Institut für Experimentelle und Angewandte Physik, University of Kiel, Germany

Thanks!

**Comment by kathivashkiv** [comment]
Name: Kateryna Ivashkiv

**Comment by chouhanaryan** [comment]
Name: Aryan Nitin Chouhan
ORCID: [https://orcid.org/0000-0001-8004-7586](https://orcid.org/0000-0001-8004-7586)
Affiliation: Dwarkadas J. Sanghvi College of Engineering, Mumbai

**Comment by chouhanaryan** [comment]
Name: Aryan Chouhan
ORCID: https://orcid.org/0000-0001-8004-7586
Affiliation: Dwarkadas J. Sanghvi College of Engineering, Mumbai
Thanks!

**Review by kakirastern — APPROVED** [review]

**Comment by kakirastern** [comment]
Looks good

**Comment by nabobalis** [comment]
I've merged a PR with a first time contributor.

**Comment by kots14** [comment]
> 👋 hello new contributors! I am updating the list of authors for the zenodo entry (see https://zenodo.org/record/3779284 for a previous example). I have mentioned you because you are a new contributor since sunpy 2.0.
> 
> If you would like, please leave a comment below with:
> 
> ```
> The preferred name you would like to be listed as
> Your ORCID
> Your affiliation
> ```
> 
> I will then manually add this to the information. Note that none of this is compulsory!
> 
> @johan12345 @chouhanaryan @SophieLemos @dipanshu231099 @kathivashkiv @dipanshu231099 @eteq @kots14 @platipo @resakra

Name : Koustav Ghosh

**Review by nabobalis — APPROVED** [review]

**Review by kakirastern — APPROVED** [review]

**Pull request merged**
