### PR TITLE
fixed wsdl parser bug

### PR DESCRIPTION
**Pull request by dstansby**
Pulled out of https://github.com/sunpy/sunpy/pull/4358/ to
- Make that PR more manageable
- Allow an easier backport

Fixes https://github.com/sunpy/sunpy/pull/4358

### CODE REVIEW

**Review by Cadair — APPROVED** [review]

**Comment by dstansby** [comment]
Hmm not sure what's going on here, the tests pass fine for me locally...

**Comment by Cadair** [comment]
They look like unrelated JSOC fails.

**Comment by dstansby** [comment]
Ummm pretty sure they were real helio test failures

**Comment by Cadair** [comment]
Yeah they were... all the checks tab was showing me was JSOC 500s tho... damn it.

**Pull request merged**
