### PR TITLE
Adding Sunpy specific warnings

### PR DESCRIPTION
**Pull request by bsipocz**
I think it is a bad idea to raise astropy warnings in sunpy, the package is large enough to deserve a proper subclass of warnings/errors.

### CODE REVIEW

**Comment by Cadair** [comment]
we use the astropy @deprecated decorator as well, perhaps we should have a shallow reimplementation of that which changes the default warning?

**Comment by bsipocz** [comment]
@Cadair - Something like this?

**Comment by Cadair** [comment]
That would do it! Thanks.

**Comment by bsipocz** [comment]
@Cadair - Be careful, the last pep8 commit masked the real CI status, which is still failing.

**Comment by Cadair** [comment]
yeah that's very broken!

**Comment by Cadair** [comment]
it's `util` not `utils`

**Comment by bsipocz** [comment]
Yes, I figured. Should be passing now.

**Comment by Cadair** [comment]
is it possible to squash warnings for all functions in a module? Because we are still using sunpy.wcs for parity checks with coordinates: https://github.com/sunpy/sunpy/blob/master/sunpy/coordinates/tests/test_transformations_comparision.py

I really need to re-write those tests as independent accuracy tests so I can remove sunpy.wcs.

**Comment by bsipocz** [comment]
@eteq @astrofrog @mhvk - What do you think about using a bot in astropy like pep8speaks above? It's less annoying than the coverall bots as it refreshes the comment after each commit.

**Comment by Cadair** [comment]
The pep8 bot is doing amazing things for the quality of our code base.

**Comment by mhvk** [comment]
Sounds good for astropy!

**Comment by nabobalis** [comment]
What was missing on this PR? 

I can merge in master and see if the builds pass?

**Comment by bsipocz** [comment]
@nabobalis - As I remember I couldn't make the decorator work at all (the custom exceptions should work obviously), so this became something I didn't have time for. 
Now it's rebased to retrigger CI, but I expect it to still fail. Overall I think it's a very bad practuce to merge anything like this into master and then try to deal with the issues there. Maintainers should have the access to push directly to feature branches (even rebasing and the force pushing it back), so things should be cleaned up in the PRs first.

**Comment by nabobalis** [comment]
@bsipocz Sorry I wasn't clear! I mean't merge master into this PR and see if CI passed. When I sent in the message I was in the process of doing that locally.

I got this error on my machine.

```python
    @deprecated("0.8.0", alternative="sunpy.map.GenericMap.pixel_to_data")
  File "/home/nabobalis/GitHub/sunpy/sunpy/util/decorators.py", line 26, in deprecated
    warnings.warn(w[0].message, SunpyDeprecationWarning)
IndexError: list index out of range
```
If you don't mind, I want to have a look into this!

**Comment by bsipocz** [comment]
@nabobalis - Sure, go ahead!

**Comment by nabobalis** [comment]
Closed by #2166 and until I can somehow come up with a better solution that what I did.

**Comment by bsipocz** [comment]
Lets close this as the part working was merged as part of #2166. For customizing the astropy deprecation decorator (rather than using a copy of it), I'll open a separate issue as a reminder.

**Pull request closed without merging**
