### PR TITLE
Update goes test files to be corrected truncated to preserve original format

### PR DESCRIPTION
**Pull request by hayesla**
## PR Description
For the previous GOES netcdf test files I truncated them to be under the size requirements for test files, however in doing this originally I pulled out some of the data not currently used in the XRSClient and also changed the metadata slightly compared to what typical files usually are. Hence its not a very good test file.

These two new files now are truncated bit preserve the metadata and also information that is currently not used in XRSClient but may be soon (such as the flags and the other then primary channel not provided by GOES16/17. 

For example, the old files only had:
old test files:
```python
>>> file17 = h5netcdf("goes_truncated_test_goes17.nc", "r")
>>> list(file17.variables)
['time', 'xrsa_flux', 'xrsb_flux']
```

new files:
```python
>>>  list(file17.variables)
['au_factor',
 'corrected_current_xrsa2',
 'corrected_current_xrsb2',
 'roll_angle',
 'time',
 'xrsa1_flags',
 'xrsa1_flux',
 'xrsa2_flags',
 'xrsa2_flux',
 'xrsa_flags',
 'xrsa_flux',
 'xrsa_primary_chan',
 'xrsb1_flags',
 'xrsb1_flux',
 'xrsb2_flags',
 'xrsb2_flux',
 'xrsb_flags',
 'xrsb_flux',
 'xrsb_primary_chan',
 'yaw_flip_flag']
```
## PR Checklist

- [ ] I have followed the guidelines in the [Contributing document](https://docs.sunpy.org/en/latest/dev_guide/contents/newcomers.html)
- [ ] Changes follow the coding style of this project
- [ ] Changes have been formatted and linted
- [ ] Changes pass pytest style unit tests (and `pytest` passes).
- [ ] Changes include any required corresponding changes to the documentation
- [ ] Changes have been rebased and squashed to the minimal number (typically 1) of relevant commits
- [ ] Changes have a descriptive commit message with a short title
- [ ] I have added a `Fixes #XXXX -` or `Closes #XXXX -` comment to auto-close the issue that your PR addresses

### CODE REVIEW

**Comment by hayesla** [comment]
ah bananas I made a mess of this - only meant to commit the test files

**Comment by hayesla** [comment]
just for reference the truncated file was generated using [NCO](http://nco.sourceforge.net)

`ncks -d time,0,600 sci_gxrs-l2-irrad_g15_d20131028_v0-0-0.nc goes_truncated_test_goes15.nc`

`ncks -d time,0,300 sci_xrsf-l2-flx1s_g17_d20201016_v2-1-0.nc goes_truncated_test_goes17.nc`

**Comment by dstansby** [comment]
Looks like some of the GOES tests are failing...

**Comment by hayesla** [comment]
ok - I think this is failing due to the same issue as #5920 - right @dstansby ?

**Comment by dstansby** [comment]
Yeah, I think so

**Review by dstansby — APPROVED** [review]

**Comment by dstansby** [comment]
CI is failing for many other reasons, but since the core tests are passing here I'm going to merge this in.

**Pull request merged**
