### PR TITLE
removed wavelnth keyword in meta desc of maps to avoid using non standard FITS keyword - nan

### PR DESCRIPTION
**Pull request by getsanjeev**
removed wavelnth (not in use currently) keyword in meta desc of Maps to avoid using non standard FITS keyword - nan for issue #2405

### CODE REVIEW

**Comment by wtbarnes** [comment]
I think the `'waveunit'` keyword should also be removed from the header. I'm pretty sure that `GenericMap` does not require this.

**Comment by getsanjeev** [comment]
@wtbarnes I was about to ask this. Okay I will remove those as well. Thank you!

**Comment by nabobalis** [comment]
So what is missing from this PR? Just a check to remove the keyword if it is present inside GenericMap?

**Comment by getsanjeev** [comment]
@nabobalis Actually removing 'waveunit' seems to be a good idea. I have not removed it yet because it does not represent a bug (as per label) and seems a little distant from this issue title (avoid NaNs). I think we can merge it for now. I would remove 'waveunit' in some refactor related issue (or would create one). What do you say?

**Comment by nabobalis** [comment]
I don't see the point in separating the two issues.

**Comment by nabobalis** [comment]
Regardless of the last issue, could you please add a changelog entry in `CHANGELOG.RST`? 

That would be needed before a merge.

**Comment by getsanjeev** [comment]
@nabobalis I have updated the changelog. Please have a look. My apologies if this is not what you asked for, I dont have a good idea about changelogs.

**Comment by nabobalis** [comment]
That looks fine to me.

**Comment by nabobalis** [comment]
Well I'll go ahead and merge this, @getsanjeev could you open a github issue on the other problem?

**Comment by nabobalis** [comment]
Thanks!

**Pull request merged**
