### PR TITLE
More reliably determine lon/lat from WCS

### PR DESCRIPTION
**Pull request by Cadair**
This was a bug found during some NDCube work, so I just copied the lat / lon
extraction out of astropy.

This ensures they are always extracted in the correct order.

@yashrsharma44

### CODE REVIEW

**Comment by nabobalis** [comment]
Azure didnt post?

**Comment by Cadair** [comment]
Well!

**Comment by nabobalis** [comment]
I can merge and hope?

**Comment by Cadair** [comment]
I rebased and it picked it up.

**Comment by nabobalis** [comment]
THE POWER OF THE REBASE

**Comment by nabobalis** [comment]
THE POWER OF THE REBASE

**Comment by nabobalis** [comment]
THANKS

**Comment by nabobalis** [comment]
Backported.

**Pull request merged**
