### PR TITLE
Added link to sunpy.org in docs

### PR DESCRIPTION
**Pull request by ehsteve**
This PR adds a link to sunpy.org to the main page of the documentation. This deals with #1517.

### CODE REVIEW

**Comment by ehsteve** [comment]
Credit to @souravsingh for pushing this forward.

**Comment by ehsteve** [comment]
Also removed outdated warning because Stuart asked me to.

**Comment by ayshih** [comment]
:+1:

**Comment by dpshelio** [comment]
:+1:

**Comment by ehsteve** [comment]
@Cadair!

**Comment by Cadair** [comment]
@ehsteve can you back port this as well?

**Pull request merged**
