### PR TITLE
Fix several DeprecationWarning: invalid escape sequence

### PR DESCRIPTION
**Pull request by BoboTiG**
### Description

Fixes all `DeprecationWarning: invalid escape sequence` :)

### CODE REVIEW

**Comment by BoboTiG** [comment]
Do you want me to open a new PR for flake8 fixes? They are not related to my changes but still I can do that work separately :)

**Comment by BoboTiG** [comment]
I was referring to the pep8 issues that @pep8speaks reported. I will open a new PR for those specific fixes.

**Comment by nabobalis** [comment]
I mean't the focus of the changes you've made in this PR?

Also I would be against a separate PR only for pep8 fixes.

**Comment by BoboTiG** [comment]
O OK :)

Changes in this PR are related to general Python code, not specifically about what the documentation build reported.
Those `DeprecationWarning`s are already converted to `SyntaxWarning`s in the current Python dev branch and will become `SyntaxError` in a near future version.

**Comment by BoboTiG** [comment]
OK for PEP8 fixes, will do in that PR.

About doc build: the number of such warnings went from 33 to 5. I need to track the last ones.

**Comment by BoboTiG** [comment]
OK, fixed all PEP8 errors. For errors reported from docstrings code, I did not want to break anything so I disabled checks using the `noqa` comment.

The 5 remaining invalid sequences was inside a `.rst` file. There is now no more such arning in the documenation build :)

**Comment by nabobalis** [comment]
Thank you very much @BoboTiG!

**Comment by BoboTiG** [comment]
My pleasure :)

**Pull request merged**
