### PR TITLE
Make Map use wcsaxes if support exists.

### PR DESCRIPTION
**Pull request by Cadair**
The idea of this is to add wcsaxes support once the coordinates package is merged. But, for 0.6, to make it optional.

### CODE REVIEW

**Comment by Cadair** [comment]
Ping @astrofrog

**Comment by astrofrog** [comment]
Nice! What will the user API look like? Can users do:

```
m = GenericMap(...)
plt.subplot(1,1,1,projection=m.wcs)
```

?

**Comment by Cadair** [comment]
@astrofrog You should be able to do this:

```python
m = Map()
im = m.plot()
```
which will give you an `AxesImage` object on a `WCSAxes` which will be the base plot. You can then do `ax = plt.gca()` to get the actual `WCSAxes` object.

*or* you can do this:
```python
m = Map()
ax = plt.subplot(1,1,1,projection=m.wcs)
im = m.plot([axes=ax]) # Should detect the current axes
```

Basically our `GenericMap.plot` method should be a functional replacement for `plt.imshow()` with some extra setup code hidden away.

You can also do:

```python
m = Map()
im = m.plot()
overlay = m.draw_grid()
```
which will draw a Helio Graphic coordinate grid and return the wcsaxes overlay object.

**Comment by Cadair** [comment]
I am going to close this until #1210 is merged, as it needs it.

**Pull request closed without merging**
