### PR TITLE
Solved the problem of leaving socket opened

### LINKED ISSUE #3930: We don't close VSO connections
When I run the some of the examples that call the VSO, I see this in the output in my terminal:

```
generating gallery for generated/gallery/acquiring_data... [100%] searching_vso.py                                                                                                             
/home/nabil/GitHub/sunpy/.tox/build_docs/lib/python3.8/site-packages/sphinx_gallery/gen_rst.py:692: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.103', 45712), raddr=('146.5.21.123', 80)>
  gc.collect()
/home/nabil/GitHub/sunpy/.tox/build_docs/lib/python3.8/site-packages/sphinx_gallery/gen_rst.py:692: ResourceWarning: unclosed <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.103', 45792), raddr=('146.5.21.123', 80)>
  gc.collect()
/home/nabil/GitHub/sunpy/.tox/build_docs/lib/python3.8/site-packages/sphinx_gallery/gen_rst.py:692: ResourceWarning: unclosed <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.103', 45790), raddr=('146.5.21.123', 80)>
  gc.collect()
```

We should find out where we aren't closing these connections and close them.

### PR DESCRIPTION
**Pull request by DShivansh**
Closed the session in the destructor of VSOClient thus solving the problem

Fixes #3930

### CODE REVIEW

**Comment by Cadair** [comment]
(I think this should be backportable to 1.0)

**Comment by Cadair** [comment]
I think you need to merge master in (or rebase) and fix up the warning checking.

**Comment by DShivansh** [comment]
should I rebase this branch to master? do you mean I need to change the test case that I have written?

**Comment by nabobalis** [comment]
Either rebase this or merge in master.

**Comment by nabobalis** [comment]
Thanks @DShivansh

**Pull request merged**
