### PR TITLE
Change download file format

### PR DESCRIPTION
**Pull request by dumindux**
Fix for #1171

### CODE REVIEW

**Comment by dpshelio** [comment]
It seems it works :) :+1: 
But maybe a test wouldn't hurt... ;)

**Comment by dumindux** [comment]
@dpshelio Right. I will add some tests :).

**Comment by dpshelio** [comment]
Beautiful! (and Travis is happy too!)

**Comment by Cadair** [comment]
:+1:

**Comment by rhewett** [comment]
Is there guaranteed to only have one

**Comment by Cadair** [comment]
@rhewett only one what?

**Comment by rhewett** [comment]
Sorry, mobile githubbing via email and I accidentally sent message rather than canceling the draft

**Pull request merged**
