### PR TITLE
Doc updates for #1490

### PR DESCRIPTION
**Pull request by aringlis**
To addresss #1490, updates to:

  - tour.rst
  - plotting.rst
  - roi.rst
  - time.rst
  - ssw.rst

### CODE REVIEW

**Comment by aringlis** [comment]
The Developer Guide looks fine to me, but someone else might want to take a look.

**Comment by aringlis** [comment]
What is the merge conflict here?

**Comment by Cadair** [comment]
donno, run a  `git merge upstream master`

**Comment by Cadair** [comment]
after you run `git fetch --all`

**Comment by aringlis** [comment]
Ok done - it's ok now.

**Comment by Cadair** [comment]
:+1:

**Comment by aringlis** [comment]
Ok, I added the necessary underlines (hopefully).

**Comment by ehsteve** [comment]
:+1:

**Comment by wafels** [comment]
+1

**Pull request merged**
