### PR TITLE
Cleanup EVE file parsing

### PR DESCRIPTION
**Pull request by dstansby**
This will fix at least some of the failing tests on master, which are due to a new pandas release (1.2.0).

- Only ever hand a file path to pandas, and not an open file, as this was causing some incorrect lines to be read in (this probably warrants a bugfix changelog entry)
- Clean up the date parsing logic so it's clearer and doesn't use a method no longer supported in pandas.

### CODE REVIEW

**Comment by nabobalis** [comment]
Warrants a backport to 2.0?

**Comment by slim-patchy** [comment]
Agreed

**Comment by dstansby** [comment]
Remote failing tests are a JSOC issue; the change in figure test images is because the x-label is now "Time" instead of "HHMM", which I think is an improvement.

**Review by nabobalis — APPROVED** [review]

**Comment by nabobalis** [comment]
Seems a remote data doctest has changed for JSOC.

**Review by akirahirohito — APPROVED** [review]
Looks good enough

**Pull request merged**
