### PR TITLE
Simplify solar cycle example

### PR DESCRIPTION
**Pull request by dstansby**
This should make it pass hopefully. I got rid of some of the complicated bits that were probably causing the test to fail, but this still shows how to plot the solar cycle from the sample data. To be honest we should probably replace this with how to download/plot current data, but for now this should be fine.

### CODE REVIEW

**Comment by nabobalis** [comment]
Do we have any left skipped examples now?

**Comment by nabobalis** [comment]
We also get 
```
/root/project/.tox/build_docs/lib/python3.7/site-packages/sunpy/timeseries/timeseriesbase.py:126: SunpyUserWarning: Using .data to access the dataframe is discouraged; use .to_dataframe() instead.
  "use .to_dataframe() instead.", SunpyUserWarning)
/
``` 
do we want to fix that?

**Comment by dstansby** [comment]
The reprojection ones are still skipped.

**Comment by nabobalis** [comment]
Should we just skip those?

**Comment by dstansby** [comment]
This is a quick fix to make the example run, so I'd rather not add anything new here.

**Comment by nabobalis** [comment]
I opened an issue here about that https://github.com/sunpy/sunpy/issues/4082

**Pull request merged**
