### PR TITLE
Bug in sunpy.time convert_time_str function

### PR DESCRIPTION
**Pull request by hayesla**
### Description
In sunpy.time.time.py the astropy.time.Time.strptime is called but this does not exist, it comes from an older version of sunpy when the time types were datetimes
 

Fixes #<Issue Number>

### CODE REVIEW

**Comment by nabobalis** [comment]
Hello @hayesla, do you have an example I can use to debug?

**Comment by Cadair** [comment]
This should exist as long as you have astropy 3.1 installed?

**Comment by hayesla** [comment]
Oh maybe that's the problem - updated my astropy and now seems to work

Was also just learning from @DanRyanIrish how to make pull request to SunPy

**Comment by DanRyanIrish** [comment]
Even if this isn't merged it's a good learning experience.  Also shows the value of opening a PR sooner rather than later.

**Comment by nabobalis** [comment]
Yeah, you want to see the older PRs that wafels or stevie have opened. 

Several times they commited sunpy into sunpy.

**Comment by Cadair** [comment]
Jack holds the dubious honor of being the only person to cause us to reset the master branch 😜😜

**Pull request closed without merging**
