### PR TITLE
Remove 4.0 changelog entries on main

### PR DESCRIPTION
**Pull request by dstansby**

### CODE REVIEW

**Review by ConorMacBride — COMMENTED** [review]
The readme was deleted also

**Comment by dstansby** [comment]
Woops, thanks for catching

**Review by nabobalis — APPROVED** [review]

**Comment by nabobalis** [comment]
I will approve but not merge.

**Comment by nabobalis** [comment]
> I am now confused about what we do with stuff merged and backported between now and 4.0 release. Perhaps the best way to do it is forward-port the commit where `towncrier` is run on 4.0 at release time?

This sounds like the easiest thing to do.

**Pull request closed without merging**
