### PR TITLE
make meta_keywords a dict

### PR DESCRIPTION
**Pull request by exitflynn**
## PR Description

makes the `sunpy.map.header_helper.meta_keywords()` a dict from the get-go, making it a copy of the `_map_meta_keywords` dict as discussed in #6562

### CODE REVIEW

**Comment by exitflynn** [comment]
i suppose we'd need a changelog for this right?

**Comment by nabobalis** [comment]
I need to check with @ayshih but this is public API, we can't remove the function without a deprecation cycle.

**Comment by ayshih** [comment]
Um...  What is the purpose for this dictionary?  Our codebase doesn't appear to use it; does any user?  Can we just remove it?  If it has a purpose, why does it live in `sunpy.map.header_helper`?  All questions I should pose in the original issue, I suppose.

**Comment by nabobalis** [comment]
So in that vein, should we just fix the fact it isn't copied and deprecate it? 

We can worry about if we need to keep it around in some form in the future?

**Comment by exitflynn** [comment]
whoops looks like i accidentally closed the PR by force-pushing ☠️🫣

**Pull request closed without merging**
