### PR TITLE
Updating astropy_helpers to v3.1

### PR DESCRIPTION
**Pull request by bsipocz**
~Do not merge yet, it's opened for testing and needs to be updated to point to the actual release when it's released.~

@Cadair  or @nabobalis: could you please check whether this doesn't mess up anything in the tests? It shouldn't, but would be nice to double check even on the passing builds.

### CODE REVIEW

**Comment by nabobalis** [comment]
Everything seems ok to me!

**Comment by bsipocz** [comment]
Great. But what is that failing travis? your new log output looks confusing, at least this late at night.

**Comment by nabobalis** [comment]
There are some servers that we require for our online tests that have been down for a while now. Those are the reason that Travis has failed. 

Has our log output changed?! I guess the way that tox reports it might have made it change.

**Comment by bsipocz** [comment]
yeah, it doesn't collect all failure to the bottom, and it's a bit too colourful :)

**Comment by nabobalis** [comment]
If I were to test astropy_helpers v2.0.x can I just checkout the branch or do I need a specific commit?

**Comment by bsipocz** [comment]
Merge away when passes, this now points to the release.

**Pull request merged**
