### PR TITLE
[unidown]: Start API work

### PR DESCRIPTION
**Pull request by Cadair**
This implements the following API:

```python

import sunpy.net.solardownloader as sdl

results = sdl.UnifiedDownloader(Time('2012/1/1', '2012/1/2'), Instrument('aia'), vso.Wave(17.1*u.nm))

files = sdl.UnifiedDownloader.get(results, wait=True)
```

### CODE REVIEW

**Comment by ehsteve** [comment]
@Cadair question for you. The point of using the `attrs` was that you can create logical combinations of them but here it seems like it is not possible. Unless we can make use of that then there is little point in using them and users will question why they can't just use.

```
results = sdl.UnifiedDownloader(['2012/1/1', '2012/1/2'], 'aia', 17.1*u.nm)
```
which is a far cleaner API.

**Comment by Cadair** [comment]
@ehsteve you can use logical combinations, or at least if not it's a bug.

```python
results = sdl.UnifiedDownloader(Time('2012/1/1', '2012/1/2'), Instrument('goes') | Instrument('noaa-indicies'))
```

should work, 

as should the more complex:

```python
results = sdl.UnifiedDownloader(Time('2012/1/1', '2012/1/2'), Instrument('lyra') | (Instrument('aia'), vso.Wave(171*u.AA)))
```

**Comment by ehsteve** [comment]
@Cadair also can get rid of the Time attr and just use TimeRange? As it is confusing that we have both.

**Comment by ehsteve** [comment]
Also here is my vote for the API

```python

from sunpy.net import DataRetriever as fido
results = fido.search(Time('2012/1/1', '2012/1/2'), Instrument('aia'), vso.Wave(17.1*u.nm))
files = fido.fetch(results)
```
`wait=True` should be on by default.

**Comment by wafels** [comment]
Federated Internet Data Obtainer = fido

**Comment by Cadair** [comment]
@ehsteve we should keep TimeRange and Time separate, as there is a lot of attr magic that would have to be included in TimeRange and it would get ugly. Time(mytimerange) is not the end of the world if you already have one, and Time(start, end) is simple when you don't.

I like FIDO, the API you have suggested isn't quite right though, it would be more like this:

```python
from sunpy.net import dataretriever as dr
results = dr.Fido.search(dr.Time('2012/1/1', '2012/1/2'), dr.Instrument('aia'), dr.vso.Wave(17.1*u.nm))
files = dr.Fido.fetch(results)
```

We need a submodule namespace to hold the attrs and the UnifiedDownloader, calling the instance of UnifiedDownloaderFactory `Fido` I am fine with.

**Pull request closed without merging**
