### PR TITLE
Use STEREO sample data in example gallery

### PR DESCRIPTION
**Pull request by dstansby**
Our doc build consistently fails on downloading STEREO data. I've added some new sample data here: https://github.com/sunpy/sample-data/pull/26, so hopefully this doesn't happen as often.

Part of fixing https://github.com/sunpy/sunpy/issues/3514 and https://github.com/sunpy/sunpy/issues/5632

### CODE REVIEW

**Comment by nabobalis** [comment]
Hmm:

```
ERROR: Failed to download STEREO_B_195_Jun2012 from all mirrors,the file will not be available. [sunpy.data._sample]
ERROR: Failed to download STEREO_A_195_Jun2012 from all mirrors,the file will not be available. [sunpy.data._sample]
```
I wonder why its having issues.

**Comment by dstansby** [comment]
Woops, I renamed the extensions in the sample data repo, and forgot to rename them here. Should be fixed now.

**Review by nabobalis — APPROVED** [review]

**Comment by nabobalis** [comment]
The examples look good to me.

**Review by Cadair — COMMENTED** [review]
Well I never submitted this comment.

I think we should make these keys all caps.

**Comment by Cadair** [comment]
Also as we backported this we should probably have mentioned the new sample data files in the changelog, as now if people import our sample data in their scripts they are getting new files downloaded when they update to the next bugfix.

**Comment by nabobalis** [comment]
> Also I would argue that adding sample data didn't really fall under the intention of the "docfix" label and this should have had two reviews, but whatever.

We added the sample data in the sample data repo, adding it to sunpy isn't a two person review.

**Pull request merged**
