### PR TITLE
Add fallback if lasco has a 0 bunit in the jp2

### PR DESCRIPTION
**Pull request by nabobalis**
Lasco JP2 provided to us from the HV has the following header:

```
<meta>
<fits>
<SIMPLE>1</SIMPLE>
<BITPIX>16</BITPIX>
<NAXIS>2</NAXIS>
<NAXIS1>1024</NAXIS1>
<NAXIS2>1024</NAXIS2>
<FILENAME>23940050.fts</FILENAME>
<FILEORIG>230618_003528.img</FILEORIG>
<DATE>2023/06/18 00:39:32.591</DATE>
<DATE_OBS>2023/06/18</DATE_OBS>
<TIME_OBS>00:36:07.390</TIME_OBS>
<P1COL>20</P1COL>
<P1ROW>1</P1ROW>
<P2COL>1043</P2COL>
<P2ROW>1024</P2ROW>
<VERSION>2</VERSION>
<EXPTIME>25.1919</EXPTIME>
<EXP0>23.0000</EXP0>
<EXPCMD>23.0000</EXPCMD>
<EXP1>1.88135</EXP1>
<EXP2>2.02490</EXP2>
<EXP3>2.19189</EXP3>
<TELESCOP>SOHO</TELESCOP>
<INSTRUME>LASCO</INSTRUME>
<DETECTOR>C2</DETECTOR>
<READPORT>C</READPORT>
<SUMROW>0</SUMROW>
<SUMCOL>0</SUMCOL>
<LEBXSUM>1</LEBXSUM>
<LEBYSUM>1</LEBYSUM>
<SHUTTR>0</SHUTTR>
<LAMP>0</LAMP>
<FILTER>Orange</FILTER>
<POLAR>Clear</POLAR>
<LP_NUM>Normal</LP_NUM>
<OS_NUM>4179</OS_NUM>
<IMGCTR>1632</IMGCTR>
<IMGSEQ>0</IMGSEQ>
<COMPRSSN>XZ%</COMPRSSN>
<HCOMP_SF>64</HCOMP_SF>
<FP_WL_UP>0.00000</FP_WL_UP>
<FP_WL_CM>0.00000</FP_WL_CM>
<WAVELENG>0.00000</WAVELENG>
<FP_ORDER>0</FP_ORDER>
<M1_PZ1>0</M1_PZ1>
<M1_PZ2>0</M1_PZ2>
<M1_PZ3>0</M1_PZ3>
<MID_DATE>60113</MID_DATE>
<MID_TIME>2179.99</MID_TIME>
<PLATESCL>11.9000</PLATESCL>
<OFFSET>0</OFFSET>
<IMAGE_CT>1632</IMAGE_CT>
<SEQ_NUM>0</SEQ_NUM>
<OBT_TIME>2.06574e+09</OBT_TIME>
<R1COL>20</R1COL>
<R1ROW>1</R1ROW>
<R2COL>1043</R2COL>
<R2ROW>1024</R2ROW>
<BUNIT>0</BUNIT>
<EFFPORT>C</EFFPORT>
<RECTIFY>TRUE</RECTIFY>
<DATAMAX>12764.0</DATAMAX>
<DATAMIN>654.000</DATAMIN>
<DATAZER>0</DATAZER>
<DATASAT>0</DATASAT>
<DSATVAL>0.00000</DSATVAL>
<DSATMIN>0.00000</DSATMIN>
<NSATMIN>0</NSATMIN>
<DATAAVG>2482.54</DATAAVG>
<DATASIG>1137.72</DATASIG>
<DATAP01>732.000</DATAP01>
<DATAP10>1229.00</DATAP10>
<DATAP25>1868.00</DATAP25>
<DATAP50>0.00000</DATAP50>
<DATAP75>3008.00</DATAP75>
<DATAP90>3465.00</DATAP90>
<DATAP95>3784.00</DATAP95>
<DATAP98>4755.00</DATAP98>
<DATAP99>7398.00</DATAP99>
<CRPIX1>511.200</CRPIX1>
<CRPIX2>507.500</CRPIX2>
<CRVAL1>0.00000</CRVAL1>
<CRVAL2>0.00000</CRVAL2>
<CROTA>7.63103</CROTA>
<XCEN>0.00000</XCEN>
<YCEN>0.00000</YCEN>
<CROTA1>7.63103</CROTA1>
<CROTA2>7.63103</CROTA2>
<CTYPE1>SOLAR-X</CTYPE1>
<CTYPE2>SOLAR-Y</CTYPE2>
<CUNIT1>ARCSEC</CUNIT1>
<CUNIT2>ARCSEC</CUNIT2>
<CDELT1>11.9000</CDELT1>
<CDELT2>11.9000</CDELT2>
<SECTOR>0</SECTOR>
<RSUN>0.00000</RSUN>
<NMISSING>0</NMISSING>
<MISSLIST>0</MISSLIST>
<history>
offset_bias.pro(ASCII character value=9)1.32, 09/01/11, 649.463
V15 18 Jun 1997 MAKE_FITS_HDR
3
</history>
<comment>
</comment>
</fits>
<helioviewer>
<HV_OBSERVATORY>SOHO</HV_OBSERVATORY>
<HV_INSTRUMENT>LASCO</HV_INSTRUMENT>
<HV_DETECTOR>C2</HV_DETECTOR>
<HV_MEASUREMENT>white-light</HV_MEASUREMENT>
<HV_ROCC_INNER>2.30000</HV_ROCC_INNER>
<HV_ROCC_OUTER>8.00000</HV_ROCC_OUTER>
<HV_SOURCE_PROGRAM>HV_LAS_C2_WRITE_HVS2</HV_SOURCE_PROGRAM>
<HV_QUICKLOOK>TRUE</HV_QUICKLOOK>
<HV_COMMENT>JP2 file created locally at NASA-GSFC using HV_WRITE_JP2_LWG at Sat Jun 17 20:51:08 2023.(ASCII character value=10)Contact Helioviewer Project (webmaster@helioviewer.org) for more details/questions/comments regarding this JP2 file.(ASCII character value=10)HVS (Helioviewer setup) file used to create this JP2 file: hvs_highbitrate_lasco_c2.pro (version 1.0).(ASCII character value=10)FITS to JP2 source code provided by ESA/NASA Helioviewer Project [contact the Helioviewer Project at webmaster@helioviewer.org][NASA-GSFC] and is available for download at https://launchpad.net/jp2gen.(ASCII character value=10)Please contact the source code providers if you suspect an error in the source code.(ASCII character value=10)Full source code for the entire Helioviewer Project can be found at https://launchpad.net/helioviewer.</HV_COMMENT>
<HV_SUPPORTED>TRUE</HV_SUPPORTED>
<HV_REVERSIBLE>0</HV_REVERSIBLE><HV_QUICKLOOK>TRUE</HV_QUICKLOOK>
<HV_ROCC_INNER>2.3</HV_ROCC_INNER>
<HV_ROCC_OUTER>8</HV_ROCC_OUTER>
</helioviewer>
</meta>
```

BUNIT is set to 0 and in this PR I set it to be `u.dimensionless_unscaled` instead.

### CODE REVIEW

**Comment by wtbarnes** [comment]
Needs a changelog but otherwise looks good to me.

Do we have a way to store and use header-only JPEG2000 test files in the same way we do with FITS headers?

**Comment by alasdairwilson** [comment]
Does anyone have the original fits. I.e. is this a helioviewer bug too where they are erasing that key.

**Comment by nabobalis** [comment]
Good point, the FITS headers we have in the repo for it also have this issue. So I assume actually this is a data provider issue. 

But I need to double check that first.

**Comment by wtbarnes** [comment]
> > Needs a changelog but otherwise looks good to me.
> > Do we have a way to store and use header-only JPEG2000 test files in the same way we do with FITS headers?
> 
> No (I got the wrong header file).
> 
> What we can do is take the fits header in the JP file and create a map that way but not directly from an xml header of the JP file. A new feature I would say.

I only asked because I wasn't sure if our test LASCO data also had this pathology. Since it does and we can test it, I think that is sufficient.

**Review by alasdairwilson — APPROVED** [review]

**Pull request merged**
