### PR TITLE
Cleanup sample data example

### PR DESCRIPTION
**Pull request by dstansby**
Once #3103 has gone in, this is a little cleanup of the sample data example that cuts out some of the un-needed plotting lines.

### CODE REVIEW

**Comment by ehsteve** [comment]
would you be willing to expand the scope of this PR and remove all uses of `peek()` in the example gallery :)

**Comment by dstansby** [comment]
I'm confused, I've changed everything here to use `.peek()`, not get rid of it!

**Comment by ehsteve** [comment]
Sorry! We just had a discussion during the dev meeting and it was general consensus that we should not be using `peek()` in the gallery at all since it is not really how scientists should learn to interact with sunpy and plotting. Would you be willing to remove peek() from all examples instead of adding it?

**Comment by dstansby** [comment]
Here's some, I got bored so if anyone else wants to do the rest feel free to force push (otherwise I'll finish it off in the future)

**Comment by dstansby** [comment]
I think that's everything 🎉

**Comment by nabobalis** [comment]
Thanks @dstansby

**Pull request merged**
