### PR TITLE
small typo fix in pull request template

### PR DESCRIPTION
**Pull request by iamrajiv**
### Description

Fix typo mistake in the pull request template file.

### CODE REVIEW

**Comment by Cadair** [comment]
thanks @iamrajiv :tada:

**Comment by iamrajiv** [comment]
thank you @Cadair for merging but I didn't add the changelog file. I was waiting for the PR index number to be generated. I was adding but it got merged.

**Comment by iamrajiv** [comment]
thank you @Cadair for merging but I didn't add the changelog file. I was waiting for the PR index number to be generated.

**Comment by Cadair** [comment]
It's ok, changes to infrastructure things don't normally need a changelog entry as they don't have effects on the package we release. :smile:

**Comment by iamrajiv** [comment]
@Cadair got it thanks :+1:

**Pull request merged**
