### PR TITLE
updated sample data files

### PR DESCRIPTION
**Pull request by nabobalis**
Needs https://github.com/sunpy/sample-data/pull/31 merged in.

### CODE REVIEW

**Review by dstansby — CHANGES_REQUESTED** [review]
I updated the URL here to point to https://github.com/sunpy/sample-data/tree/test so we can check it's all working. Before this is merged this commit should be removed.

**Review by dstansby — CHANGES_REQUESTED** [review]
This has broken the full Sun map example, it looks like the AIA map isn't showing up now: https://sunpy--6221.org.readthedocs.build/en/6221/_images/sphx_glr_reprojection_aia_euvi_mosaic_002.png

**Comment by nabobalis** [comment]
Updated the sample data, lets see if that fixes the problem.

**Comment by nabobalis** [comment]
> This has broken the full Sun map example, it looks like the AIA map isn't showing up now: sphx_glr_reprojection_aia_euvi_mosaic_002

https://sunpy--6221.org.readthedocs.build/en/6221/generated/gallery/map_transformations/reprojection_aia_euvi_mosaic.html#sphx-glr-generated-gallery-map-transformations-reprojection-aia-euvi-mosaic-py

Looks fixed.

**Comment by dstansby** [comment]
👍 I merged the sample data - can you remove the last commit here? (I tried but don't have permssions to force push to your branch)

**Comment by nabobalis** [comment]
> 👍 I merged the sample data - can you remove the last commit here? (I tried but don't have permssions to force push to your branch)

I have done so.

**Review by dstansby — APPROVED** [review]

**Pull request merged**
