### PR TITLE
Fix LASCOMap

### PR DESCRIPTION
**Pull request by dstansby**
Suggested by @Cadair here: https://github.com/sunpy/sunpy/issues/2774#issuecomment-427869475 - fixes the problem locally for me. Maybe needs a test adding too?

### CODE REVIEW

**Comment by Cadair** [comment]
I would be interested in knowing what @wafels or someone else who has a little more idea of the LASCO data thinks about this. In general we should probably shouldn't assume the existence of critical headers anyway.

**Comment by Cadair** [comment]
FTR we assume arcsec later on anyway: https://github.com/sunpy/sunpy/blob/master/sunpy/map/mapbase.py#L693

**Comment by nabobalis** [comment]
Do we not have a test for each map source? 

@dstansby Just add a changelog entry and we can merge this.

**Comment by dstansby** [comment]
I think this might be wrong... Trying to draw the limb defaults to drawing it at ~950arsec (assuming an Earth based observer, which SOHO basically is right?), which is not where the disk is in the created LASCO maps after this fix.

**Comment by Cadair** [comment]
your lasco data is missing all the required metadata to calculate where the limb should be, see discussion in #2788

**Comment by dstansby** [comment]
Yes, but assuming the units are arsec is incorrect (as this PR does) - is there an option to just leave the data in "pixel number" and not physical units? Or to error instead if there isn't the right metadata? Either of those options would be much preferred to silently doing the wrong thing.

**Comment by Cadair** [comment]
As I mentioned further up, we are already assuming arcsec in `GenericMap` anyway. So if we are going to change that then it's bigger than this PR.

It's also worth noting that Map is designed to support images *with WCS* metadata. While I agree with your comment on matrix that we should probably throw a better error, I am really not sure we want to support a completely metadata-less Map.

**Comment by dstansby** [comment]
@sunpy/sunpy-developers - can someone revert this? It's definitely the wrong thing to do (https://github.com/sunpy/sunpy/pull/2775#issuecomment-428933507) ...

**Comment by nabobalis** [comment]
It doesn't work? Should it be set to no units?

**Comment by dstansby** [comment]
The LASCO maps that I am downloading and reading do not have units of 'arcsec' (I don't know what units they do have...), so at the very least it shouldn't silently assume 'arcsec'.

**Pull request merged**
