### PR TITLE
Skip figure tests if hash file not present

### PR DESCRIPTION
**Pull request by dstansby**
Currently only python 2.7 and 3.5 has figure hashes, so this skips doing the figure tests if testing on e.g. python 3.6.

As a side note, shouldn't the hashes depend on the Matplotlib version as well as the python version?

### CODE REVIEW

**Comment by ayshih** [comment]
Er, this approach actually breaks the creation of a new hash library in the event that that is what you are trying to do.

**Comment by dstansby** [comment]
No, I wasn't, but I see what you mean. I can mark it as expected to fail instead of skipping the test, so the tests still get run.

**Comment by nabobalis** [comment]
@ayshih, what did you mean it breaks the creation of a new hash library? 

I thought the decorator  isn't used to create the hashes, just to check them?

**Comment by dstansby** [comment]
https://github.com/sunpy/sunpy/pull/2446/files#diff-6bea753fefc424759f9a20e9ee25bdc1R86 is the line that adds the has to a new hash library, so skipping the test would mean that line never gets run.

**Comment by nabobalis** [comment]
I see, but how/when does they get saved?

**Pull request merged**
