### PR TITLE
[WIP] Test new parfive release

### PR DESCRIPTION
**Pull request by Cadair**
**DO NOT MERGE**

Created to verify the new parfive release against our CI.

### CODE REVIEW

**Comment by Cadair** [comment]
Whoops I opened this too soon, it hasn't actually uploaded yet :man_facepalming:

**Comment by Cadair** [comment]
Well that doesn't seem to have gone well.

**Comment by nabobalis** [comment]
Looks like files failed to download?

**Comment by Cadair** [comment]
yeah

**Pull request closed without merging**
