### PR TITLE
Fix "Prefer `format()` over string interpolation operator" issue

### PR DESCRIPTION
**Pull request by dpshelio**
This pull request automatically fixes all occurrences of the following issue:

Issue type: [Prefer `format()` over string interpolation operator](https://www.quantifiedcode.com/app/issue_class/4ACGxFj1)
Issue details: [https://www.quantifiedcode.com/app/project/gh:sunpy:sunpy?groups=code_patterns/%3A4ACGxFj1](https://www.quantifiedcode.com/app/project/gh:sunpy:sunpy?groups=code_patterns/%3A4ACGxFj1)

To adjust the commit message or the actual code changes, just [rebase](https://git-scm.com/docs/git-rebase) or [cherry-pick](https://git-scm.com/docs/git-cherry-pick) the commits.
For questions or feedback reach out to cody@quantifiedcode.com.

Legal note: We won't claim any copyrights on the code changes.

Cheers,
[Cody - Your code quality bot](https://www.quantifiedcode.com/cody)

### CODE REVIEW

**Comment by Cadair** [comment]
@dpshelio you have the robots coding for you now?!

**Comment by dpshelio** [comment]
Yeah! @Cadair!! You like it? :)

Imagine how the future will look with mycroft!!!

**Comment by Cadair** [comment]
@dpshelio I am not a fan of it creating branches on the sunpy/sunpy repo, but the concept is nice.

**Comment by dpshelio** [comment]
Ooohh! it created a branch in here!!! I didn't realised I allowed that :( - I will have to see whether it's possible to do it from my fork.

**Pull request closed without merging**
