### PR TITLE
Updated Fermi pointing file FTP site

### PR DESCRIPTION
**Pull request by aringlis**
This is a new PR, replacing a previous one (#1655) - this fixes the FTP location that is used to download Fermi weekly pointing files, which are used in the tools in /instr/fermi.

Had merge conflicts before so made a new PR here.

### CODE REVIEW

**Comment by aringlis** [comment]
Oh dear, this is not python 3 compatible? :-(

**Comment by Cadair** [comment]
Indeed, it is not. You will need to import the urllib and urllib2 functions from the six wrapper.

```python
from sunpy.extern.six.moves import urllib
```
e.g.
https://github.com/sunpy/sunpy/blob/master/sunpy%2Fnet%2Fdownload.py#L19

and see for reference:
https://pythonhosted.org/six/#module-six.moves

**Comment by aringlis** [comment]
Ok it passes travis now.

**Comment by Cadair** [comment]
:+1:

**Comment by wafels** [comment]
+1

**Pull request merged**
