### PR TITLE
Doctest fix II

### PR DESCRIPTION
**Pull request by bsipocz**
This PR is to make doctest to pick up the examples by adding ``>>>``, and fix the ones that are failing.

### CODE REVIEW

**Comment by bsipocz** [comment]
Could someone please restart the doctest travis build? It halted before the build finished, and I wanted to double check the output (having some network problems locally, thus the local test runs are everything but reliable).

**Comment by ehsteve** [comment]
@bsipocz restarted.

**Comment by ehsteve** [comment]
@bsipocz i've restarted a number of times and it keeps halting it seems.

**Comment by bsipocz** [comment]
It's very strange as only rst doc files are changed in this PR.

**Comment by bsipocz** [comment]
As I see the first halt was merged into master in https://travis-ci.org/sunpy/sunpy/builds/71420170. But I can't see any suspicious in that PR either.

**Comment by bsipocz** [comment]
I've played a bit with the travis settings but it didn't solve anything (tried to opt in to the container, hoping that would change the halting).

**Comment by Cadair** [comment]
@bsipocz the travis build seems to be completing ok, where is the issue?

**Comment by bsipocz** [comment]
@Cadair - The doctest one doesn't start properly but halt in one of the ``gcc`` commands. That run is allowed to fail, thus the green light.
Anyway, running doctest locally on the files in this PR passes without any fail.

**Comment by Cadair** [comment]
@bsipocz I looked at a build this morning where the doctests had definitely run. Maybe I am going mad...

**Comment by bsipocz** [comment]
Indeed, now it run. Very weird.
There are a few fails, most of them are related to the database docs, that somehow generates a different results/output on OSX than on linux. So it passes locally, but fails on travis. I'm not sure what to do with them.

**Comment by Cadair** [comment]
Might be easiest to skip the table printing tests for now.

**Comment by bsipocz** [comment]
Yes, skipping might be a workaround for now. Attaching one more commit for that, and opening an issue to remember that a fix may be needed for that in the database modul.

**Comment by ehsteve** [comment]
:+1:

**Comment by Cadair** [comment]
:+1:

**Comment by Cadair** [comment]
oh noes it brokes.

**Comment by bsipocz** [comment]
A simple rebase seemed to solve it.

**Comment by Cadair** [comment]
looks like we are nearly there. Just 6 failing ones

I would skip the ones that save mpl animations because they need mencoder or similar.

**Comment by bsipocz** [comment]
Done. Not sure how those got missed in the previous batch.

**Comment by ayshih** [comment]
I seem to still get a number of non-database-related failures when running locally, but maybe that's just on my side.  I'm going to go ahead and merge this in, and we can resolve any lingering failures in a subsequent PR.

**Comment by ayshih** [comment]
:+1:

**Comment by bsipocz** [comment]
Thanks @ayshih. Not sure why the travis build keeps halting again, but it's quite annoying.

**Pull request merged**
