### PR TITLE
Reformatted Colour Tables to use emuns instead of functions

### LINKED ISSUE #3885: Reformatting Colour Tables
The code (https://github.com/sunpy/sunpy/tree/master/sunpy/visualization/colormaps) that deals with our color tables needs some reformatting to be cleaner.

Ideally we need to do:

* Change the color tables into a series of enums to allow someone to access the array's directly without the use of a function. 
* This means deprecation of most of the functions in those files.
* Move the arrays into their own file whether it be python or a plain text file.

### PR DESCRIPTION
**Pull request by jeffreypaul15**
### Description

Fixes #3885. Enums are being used instead of functions, although documentation and the fact that length of each line is > 100 needs some changes.

### CODE REVIEW

**Comment by nabobalis** [comment]
So how does someone use the new enum classes?

**Comment by jeffreypaul15** [comment]
The Colors class in `color_tables.py` has a few dictionaries that are can be accessed. `Colors.aia_wave_dict.values` or whichever dictionary that is required accordingly which replaces the functions that exists as of now

**Comment by nabobalis** [comment]
Having had a quick glance over it, I am not sure just moving everything into an enum makes any sense. 

I wonder if we just keep the tidy up you'be done but remove the enum entirely.

**Comment by jeffreypaul15** [comment]
I was also confused as to why the functions were to be converted to enums but I went ahead with it anyway because it was mentioned as an issue

**Comment by jeffreypaul15** [comment]
Do I close this PR instead?

**Comment by nabobalis** [comment]
No just undo the enum changes.

**Comment by jeffreypaul15** [comment]
But those are the only changes I've made

**Comment by nabobalis** [comment]
Fair point.

**Pull request closed without merging**
