### PR TITLE
Tox our CI

### PR DESCRIPTION
**Pull request by nabobalis**
We now use Tox for run all our CI.

It also allow us to pre-define and generate the same conda environment as the CI locally so we can debug issues this way now. 

```bash
$ tox -al
py37-offline
py36-offline
py37-online
py37-astropydev
py37-numpydev
py37-build_docs
py36-online
py36-astropydev
py36-numpydev
py36-build_docs
figure
```

The old ways are still supported. **FOR NOW**

### CODE REVIEW

**Comment by nabobalis** [comment]
IT ALL PASSED

**Comment by Cadair** [comment]
@nabobalis This looks ok to me, but giles and codecov haven't reported on it?

**Comment by Cadair** [comment]
Ah I think that's because it has built from your fork. I am going to merge and we can see what the damage is.

**Comment by drdavella** [comment]
🎆

**Pull request merged**
