### PR TITLE
Rename `get_contours` to `find_contours`

### LINKED ISSUE #7910: Map contour naming convention
The naming of `GenericMap.get_contours` came up in a separate thread. I think a better name might be `compute_contours`, as they aren't intrinsic to the map to be "gotten." This is basically just a matter of personal preference, but it might be worth considering a name change.

---
_original comment_

any method starting with `get_` makes me sad. is there a better verb? maybe, `compute_contours` ?

_Originally posted by @settwi in https://github.com/sunpy/sunpy/issues/7420#issuecomment-2524946923_

### PR DESCRIPTION
**Pull request by settwi**
As discussed in #7910, this PR changes `GenericMap.get_contours` to `GenericMap.find_contours`

Fixes #7910

### CODE REVIEW

**Review by nabobalis — APPROVED** [review]

**Comment by settwi** [comment]
@nabobalis do you want to delete the changelog?

**Comment by nabobalis** [comment]
Yeah if you don't mind, did we not have a changelog talking about "get_contours" being added?

**Comment by settwi** [comment]
I think there is one

**Comment by settwi** [comment]
@nabobalis #7760 got a changelog so i deleted the one this had. should be good to go as long as the checks pass

**Comment by nabobalis** [comment]
Thanks @settwi 

My approval plus the comment from Albert in the issue counts as two approvals.

**Pull request merged**
