### PR TITLE
Use default MPL colour cycle when plotting XRS data

### PR DESCRIPTION
**Pull request by dstansby**
This looks much better in my opinion, and will also respect any custom MPL colour cycles people have going on in their themes.

### CODE REVIEW

**Comment by ayshih** [comment]
The discussion to be had is whether the plotting should strive to match the standard GOES/XRS plots we've been looking at for decades.  After all, for Maps we copy the colormaps that each instrument uses.

**Comment by dstansby** [comment]
Sorry, that's my ignorance 😄 . Perhaps a good halfway house would be to use `tab:red` and `tab:blue` (ie. the red/blue in the default MPL colour cycle)? Happy to keep it as is though and I can add a comment to stop other punters coming along with a version of this PR in the future.

**Comment by ayshih** [comment]
> Perhaps a good halfway house would be to use `tab:red` and `tab:blue` (ie. the red/blue in the default MPL colour cycle)?

That'd be similar to what you did with the RHESSI colors (#4330).  However, the GOES/XRS colors are far more broadly known that there may be far more resistance to change.

Even if we do stick with the traditional colors, it'd be good to make it easier for users to use different colors.

**Comment by dstansby** [comment]
I'm going to close this since I think https://github.com/sunpy/sunpy/pull/5680#issuecomment-962169521 is a good argument to leave them as is.

**Pull request closed without merging**
