### PR TITLE
Add a draw_rectangle helper to GenericMap.

### PR DESCRIPTION
**Pull request by Cadair**
Does what it says on the tin.

### CODE REVIEW

**Comment by wafels** [comment]
What is the use case?

What if you want multiple rectangles?

**Comment by Cadair** [comment]
use case is this: http://docs.sunpy.org/en/latest/guide/plotting.html#plotting-maps-with-wcsaxes or https://gist.github.com/Cadair/cc23d737f1124470e57d

if you want multiple rectangles you can call the method multiple times.

**Comment by dpshelio** [comment]
Looks nice.  One of the use cases for me would be to see how is it done in case I wan to make a triangle instead of a square :)

:+1:

**Comment by Cadair** [comment]
@dpshelio the fact that users might want to draw other patches drawn on the map crossed my mind, but it would be near impossible to wrap them all.

**Comment by dpshelio** [comment]
@Cadair yes I know, what I meant is not that we should have them all, but by having one I could then look into it and learn how to make my own  (with all the wcsaxis craziness -  in the good way :-P )

**Comment by Cadair** [comment]
yes ;)

**Comment by wafels** [comment]
+1

**Comment by Cadair** [comment]
needs changelog

**Comment by ehsteve** [comment]
This should eventually be expanded to draw a region-of-interest object. This is a good start.

**Pull request merged**
