### PR TITLE
Backport #5770 to 3.0

### PR DESCRIPTION
**Pull request by dstansby**
Please let the CI do a full run to check this makes the CI work on v3.1.x!

### CODE REVIEW

**Comment by nabobalis** [comment]
Looks like some warning issues on py37 builds.

**Comment by nabobalis** [comment]
Didn't seem to work?

**Comment by ConorMacBride** [comment]
Not sure why. The astropy warning class is still being registered before it in py37 even though it works elsewhere. Easiest fix might be to just remove the specific astropy class from `setup.cfg` in this branch.

**Comment by nabobalis** [comment]
We could just ignore the warnings and move on for 3.0?

**Comment by ConorMacBride** [comment]
I updated the branch but GitHub hasn't updated the PR?

**Comment by nabobalis** [comment]
Github having issues?

**Review by nabobalis — APPROVED** [review]

**Pull request merged**
