### PR TITLE
Remove old webhook config

### PR DESCRIPTION
**Pull request by Cadair**
I have added the new config in the web UI

### CODE REVIEW

**Comment by Cadair** [comment]
The test will be if Giles posts the figure test summaries.

**Review by dstansby — APPROVED** [review]

**Comment by Cadair** [comment]
Grr why has this not worked.

**Comment by nabobalis** [comment]
Did it not? I see the figure reports?

**Comment by Cadair** [comment]
oh yeah, I see them now on my laptop. Couldn't see them on my phone.

**Pull request merged**
