### PR TITLE
Add python 3.12 support

### PR DESCRIPTION
**Pull request by dstansby**
Lets see how badly the CI goes...

### CODE REVIEW

**Comment by braingram** [comment]
I don't believe aiohttp has yet released a non-pre version that supports python 3.12. You might try installing `aiohttp==3.9.0b0` as it adds python 3.12 support. See https://github.com/aio-libs/aiohttp/issues/7675 for some more details.

**Comment by nabobalis** [comment]
Did I miss why this was closed?

**Comment by dstansby** [comment]
I just don't have time to work on it at the moment.

**Comment by nabobalis** [comment]
Do you mind if I take over?

**Comment by dstansby** [comment]
Yeah definitely feel free to copy the branch and finish it off!

**Pull request closed without merging**
