### PR TITLE
Add a client to Fido which can discover the synoptic AIA series

### PR DESCRIPTION
**Pull request by GillySpace27**
## PR Description

This PR addresses Issue #7828 by adding a new client into the dataretriever module

Some discussion should be had regarding the best way to call for this Series since it isn't managed by JSOC in the usual way. For the moment if a.Instrument is either "AIA" or "AIASynoptic" the client will be called. a.Resolution == "Synoptic" will also trigger alongside a.Instrument == "AIA". That said, I'm not sure the average user would like to have to start specifying a resolution like that in order to not be served with this series, so I'm thinking the unique instrument might be the way to go.

### CODE REVIEW

**Comment by nabobalis** [comment]
It might be tricky but can you undo all of the code formatting changes? There have been discussions around auto formatting the code but they have not been accepted yet

**Comment by GillySpace27** [comment]
Sorry about that!  Of course I set up the formatter to run on save, so I'm not always seeing what changes it makes. How do you think I should go about it? Are there standard approaches?

**Comment by nabobalis** [comment]
Err, honestly I don't know what would be best. It might be simplest to just start again from a clean branch and add just the new client and attr code.

**Comment by nabobalis** [comment]
Replaced by https://github.com/sunpy/sunpy/pull/7842

**Pull request closed without merging**
