### PR TITLE
Fixes for sunpy.sun.sun

### PR DESCRIPTION
**Pull request by ayshih**
- `sun.print_params()` was broken and nobody noticed.  Fixed and added a simple test
- Docstring tweaks, particularly to functions that don't use our coordinates framework

### CODE REVIEW

**Comment by nabobalis** [comment]
Thanks @ayshih!

**Comment by nabobalis** [comment]
Backported to 1.0

**Comment by Cadair** [comment]
@ayshih with regards to "this function dosen't use the coordinates framework" messages should we be thinking about deprecating / removing these functions?

**Comment by ayshih** [comment]
> @ayshih with regards to "this function dosen't use the coordinates framework" messages should we be thinking about deprecating / removing these functions?

I plan to re-implement them using the coordinates framework, and I've started doing so, but it's not a 1.0 thing.  The notion would be to not change the outward API, so that would presumably mean not deprecating or removing these functions.

**Pull request merged**
