### PR TITLE
Add support for old EIT Maps with bad date-obs

### LINKED ISSUE #6604: Old EIT Maps are unable to have their date parsed correctly.
### Describe the bug

EIT fits files have the date-obs field in the form '01-Jan-96' which means they cannot be parsed by astropy.time.

They have an alternative date_obs which has the datetime in the correct format.

### To Reproduce

```
from sunpy.map import Map
import wget

wget('https://soho.nascom.nasa.gov/data/summary/eit/1996/12/seit_00171_fd_19961211_1900.fts')

Map('seit_00171_fd_19961211_1900.fts')
```

`ValueError: Input values did not match any of the formats where the format keyword is optional: {'datetime': TypeError('Input values for datetime class must be datetime objects'), 'ymdhms': ValueError('input must be dict or table-like'), 'iso': ValueError('Time 11-DEC-96 does not match iso format'), 'isot': ValueError('Time 11-DEC-96 does not match isot format'), 'yday': ValueError('Time 11-DEC-96 does not match yday format'), 'datetime64': TypeError('Input values for datetime64 class must be datetime64 objects'), 'fits': ValueError('Time 11-DEC-96 does not match fits format'), 'byear_str': ValueError('Time 11-DEC-96 does not match byear_str format'), 'jyear_str': ValueError('Time 11-DEC-96 does not match jyear_str format'), 'astropy_time': TypeError('Input values for astropy_time class must all be same astropy Time type.')}`

### Screenshots

_No response_

### System Details

_No response_

### Installation method

_No response_

### PR DESCRIPTION
**Pull request by alasdairwilson**
## PR Description

Fixes #6604 

This changes EITMap to first check for date_obs before falling back to date-obs, in old data date-obs was in a format that cannot be parsed by `parse_time`

### CODE REVIEW

**Comment by nabobalis** [comment]
Possible to add a test?

**Comment by nabobalis** [comment]
Can we use the header instead of having a binary file?

**Review by wtbarnes — CHANGES_REQUESTED** [review]

**Comment by nabobalis** [comment]
The pre-commit is not happy.

**Review by nabobalis — APPROVED** [review]

**Review by Cadair — APPROVED** [review]

**Comment by Cadair** [comment]
pre-commit.ci autofix

**Pull request merged**
