### PR TITLE
Fixed typos of Heliocentric instead of Heliographic

### PR DESCRIPTION
**Pull request by ayshih**
Typos spotted by @dpshelio (https://github.com/sunpy/sunpy/pull/3782#discussion_r391261951)

### CODE REVIEW

**Comment by Cadair** [comment]
@ayshih backport to 1.0?

**Comment by ayshih** [comment]
> @ayshih backport to 1.0?

No, that table doesn't exist in 1.0

**Comment by Cadair** [comment]
Just 1.1 then?

**Comment by Cadair** [comment]
(┛◉Д◉)┛彡┻━┻

**Comment by ayshih** [comment]
That's odd... I created a backport branch locally because I thought the cherry-pick might fail, but it succeeded for me, so I thought the bot could handle it.

**Pull request merged**
