### PR TITLE
Remove nesting of AttrAnd and AttrOr in Attr base

### PR DESCRIPTION
**Pull request by Cadair**
This changes the base Attr class so doing `and_(Attr, AttrAnd)` doe sresult in nested AttrAnd or AttrOr objects.

ping @derdon @segfaulthunter @dpshelio

### CODE REVIEW

**Comment by Cadair** [comment]
An example:

before:
```python:
>>> attr.and_(attrs.Level(0), attr.AttrAnd((attrs.Instrument('EVE'), attrs.Time("2012/1/1", "2012/01/02"))))
<AttrAnd([<Level(0)>, <AttrAnd([<Instrument('EVE')>, <Time(datetime.datetime(2012, 1, 1, 0, 0), datetime.datetime(2012, 1, 2, 0, 0), None)>])>])>
```

after:
```python
>>> attr.and_(attrs.Level(0), attr.AttrAnd((attrs.Instrument('EVE'), attrs.Time("2012/1/1", "2012/01/02"))))
<AttrAnd([<Level(0)>, <Instrument('EVE')>, <Time(datetime.datetime(2012, 1, 1, 0, 0), datetime.datetime(2012, 1, 2, 0, 0), None)>])>
```

**Comment by Cadair** [comment]
this by the way closes #1828 ping @abit2

**Comment by dpshelio** [comment]
This could be improved by one test for `And` and another for `Or`, don't you think?

**Comment by Cadair** [comment]
@dpshelio tests added.

@sunpy/sunpy-developers review please.

**Comment by wafels** [comment]
+1

**Pull request merged**
