### PR TITLE
Use to_dataframe() in goes.py

### PR DESCRIPTION
**Pull request by dstansby**
Catching a few more instances where using `.data` is now discouraged/throws a warning, and converting them to using `to_dataframe()`.

### CODE REVIEW

**Comment by wtbarnes** [comment]
I have absolutely no problem with this change, but I wonder how we should handle development on the `instr` subpackage moving forward. Most of this functionality has been moved to [sunpy/sunkit-instruments](https://github.com/sunpy/sunkit-instruments).

Should development happen in both places? Can we automatically mirror PRs on this subpackage to that repo or *vice-versa*? Should we freeze development here and move all development over to `sunkit-instruments`?

**Comment by dstansby** [comment]
Oh, if that's the case shouldn't we deprecate all this stuff in sunpy core (like with aiapy?)

**Comment by wtbarnes** [comment]
I'm not sure how the interaction between core and `sunkit-instruments` should look like. We briefly discussed this at the coordination meeting I think, but I don't remember if we came up with a concrete solution. This should be a topic at the next telecon.

**Comment by wtbarnes** [comment]
Oops meant to approve that first 🤷 

Didn't think that discussion should block this being merged. I've added a point to the agenda for the next meeting that essentially encapsulates my above point.

**Pull request merged**
