### PR TITLE
Speeding up travis

### PR DESCRIPTION
**Pull request by bsipocz**
So the main idea behind the removals here is that numpy and python should be well tested with each other, so no need to run all combinations.
E.g. python 3.6 test is run with coverage, no need to run one without it. python 3.4 is run with numpy 1.10, no need to run it again with numy 1.11.

Also, numpy dev and astropy dev can be tested together. This may need to be split up again if there will be many failures with the numpy dev (it was allowed to fail, but was passing recently).

Also no need to run the doctests as apparently noone is trying to fix those while they are allowed to fail. However I think that could be a menial but super useful GSoC project (or part of one) to get the doctests up and running. @dpshelio @Cadair what do you think?

Still things to do: 
* [x] fix the egg_builds
* [x] optimize the cron build

(Note: I run this on my fork and the total time was 1h25min+~6-7min for the cancelled osx run)

### CODE REVIEW

**Comment by ayshih** [comment]
I have previously asked for the removal of `setup_requires` (#1396), but at least at some point that didn't seem to be possible (see #1551).  Comments?

**Comment by bsipocz** [comment]
@ayshih - We don't have it for any of the astropy/affiliates we maintain, and in fact the eggs should be able to built without any dependencies being installed (at least that's my understanding).

Anyway the tests seem to pass, I just made one more tweak. Also pending some improvement in ``ci-helpers``, I think that the egg builds should be able to finish within 30-40 sec in the future if ``language: python`` is used.

**Comment by bsipocz** [comment]
btw appveyor is failing due to a totally unrelated reason, I'm about to report it upstream.

**Comment by Cadair** [comment]
I would like to run a job independent of the online/coverage build for python 3.6 as that build loves to die due to changes out of our control.

What are the changes you have made to the language variables how do they interact with ci helpers and conda?

**Comment by bsipocz** [comment]
Sure, I can add back the build, though I still think that having two linux jobs + the osx should be enough for py3.6 (one is the astropy dev+numpy dev, the other is the online+coverage).
Changing the language is actually doesn't improve much yet, but I plan to do some improvements in ci-helpers, so using the native python shipped by travis would save few minutes on the egg builds. 
(We only use c as language in the package template as there is no native python shipped with osx. I'll propose there to use a setup more similar to this change here.)

**Comment by Cadair** [comment]
Actually yeah, the OS/X job should cover the online one. I just wanted to make sure it was obvious if it was the python 3.6 build that was broken over the online one.

I didn't realise you could use the travis python version specifications to tell ci-helpers what version to install (https://github.com/astropy/ci-helpers/blob/master/travis/setup_dependencies_common.sh#L77), so that's neat.

I am not sure if it's best to have the numpy & astropy dev build allowed to fail or not, numpy dev occasionally likes to break on us. I suppose it's more important that it doesn't go unnoticed. I know there was some discussion on astropy about having it allowed fail and then notifying people if it starts failing, did that go anywhere?

Thanks a lot @bsipocz this is really great.

**Comment by bsipocz** [comment]
@Cadair - Yes, that was the original setup, to use travis python, then we started to encourage packages to have at least one osx job and switching the language for the whole setup seemed the most trivial solution. However as I said I'm considering to use this other approach as it could save us ~5mins/build with the eggs, and that could add up with a large organization like astropy where we can have travis queues of a few hours at peak times.

Sadly we still don't have a way to get notifications when an allowed to fail build fails.

So, you suggest to have the osx build to be the online one, but keep the coverage at its current job, right?

**Comment by Cadair** [comment]
No, I mean to keep it as it is. I just meant the OS/X job would indicate if the online fail is because of online stuff. The coverage needs to be the online job so that it has the largest number ;)

**Comment by bsipocz** [comment]
Great. Then this is good to go I think.

**Comment by bsipocz** [comment]
Maybe bring up the online one, as it runs the longest?

**Comment by Cadair** [comment]
yeah that would be worth while, pop it at the top of the matrix.

**Comment by bsipocz** [comment]
Done.

**Comment by Cadair** [comment]
thanks a lot @bsipocz

**Pull request merged**
