### PR TITLE
Skips HEC and fixes last few online tests

### PR DESCRIPTION
**Pull request by nabobalis**
I introduced a bug in the oldest deps version which is now fixed as well.

This has been patched on the release branches.

### CODE REVIEW

**Comment by dstansby** [comment]
Just so there's a cross reference, https://github.com/sunpy/sunpy/issues/6917

**Review by dstansby — APPROVED** [review]
Should this not get backported? I backported the revert PR, so I'll mark this as needing a backport

**Review by Cadair — APPROVED** [review]
We need an actual solution to the HEC issue as this hides it from us forever.

**Comment by Cadair** [comment]
Well we broke the backport bot lol

**Pull request merged**
