### PR TITLE
remove powernorm from the code

### PR DESCRIPTION
**Pull request by Cadair**
I am leaving the mention in `maps.rst` as it is valid, as long as you have mpl 1.4 installed.

### CODE REVIEW

**Comment by Cadair** [comment]
closes #1484 
closes #1485

**Comment by Cadair** [comment]
hmmm

@ayshih or @ehsteve any ideas??

**Comment by ehsteve** [comment]
Why not remove it from maps.rst as it is really not necessary.

**Comment by Cadair** [comment]
@ehsteve but the sentence makes perfect sense with it in there, and it is not incorrect.

**Comment by Cadair** [comment]
@ehsteve I removed it

**Comment by ayshih** [comment]
:+1:

**Comment by Cadair** [comment]
GO GO READ THE DOCS!

**Comment by ayshih** [comment]
The moment of truth?

**Comment by ayshih** [comment]
"Server Too Busy"?  Bah.

**Comment by Cadair** [comment]
https://readthedocs.org/builds/sunpy/3082845/

**Comment by ayshih** [comment]
Yay!

**Comment by Cadair** [comment]
REJOICE!

**Comment by ehsteve** [comment]
:+1:

**Pull request merged**
