### PR TITLE
Gallery Cleanup and Standardisation

### PR DESCRIPTION
**Pull request by Cadair**
This mostly formats the import statements in a consistent way, but also changes lightcurve to timeseries in a couple of examples as well, and generally does a little bit of cleaning.

### CODE REVIEW

**Comment by nabobalis** [comment]
Issue is: 
```
WARNING: /home/travis/build/sunpy/sunpy/examples/AIA_limb_STEREO.py failed to execute correctly:Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 450, in execute_code_block
    exec(code_block, example_globals)
  File "<string>", line 4, in <module>
  File "<string>", line 2, in <dictcomp>
  File "/home/travis/build/sunpy/sunpy/build/lib.linux-x86_64-3.6/sunpy/map/mapbase.py", line 214, in __getitem__
    "The ability to index Map by physical"
NotImplementedError: The ability to index Map by physical coordinate is not yet implemented.
```

**Comment by Cadair** [comment]
Oh that happens in the example if VSO only returns one record instead of two.

**Comment by nabobalis** [comment]
That explains it, I only get one search result right now. Merging.

**Comment by nabobalis** [comment]
Looks like a whole host of servers or services are down.

**Pull request merged**
