### PR TITLE
Issue#2855

### PR DESCRIPTION
**Pull request by Naman9639**
### Description

Fixes #<Issue Number>

### CODE REVIEW

**Comment by Naman9639** [comment]
Why are all these commits in my new PR?

**Comment by nabobalis** [comment]
I assume you created the new branch off your helioviewer pull request.

**Comment by Naman9639** [comment]
So shall I close this pull request and create another one? Though as far as I remember I switched to master and then created a branch.

**Comment by nabobalis** [comment]
You should be able to update the git history and rebase this.

**Comment by Naman9639** [comment]
Can I close this PR and open another PR? I rebased and deleted the commits but I am still able to see them in my log

**Comment by nabobalis** [comment]
Sure

**Pull request closed without merging**
