### PR TITLE
Test concatenating two of the same TimeSeries

### PR DESCRIPTION
**Pull request by dstansby**
Will add a line of coverage!

### CODE REVIEW

**Comment by wtbarnes** [comment]
Looks good! Just needs a changelog

**Comment by dstansby** [comment]
Do I need to bother for such a small change?

**Comment by wtbarnes** [comment]
I will defer to @cadair on that. I’m not sure about the policy around what requires a change log entry and what doesn’t.

**Comment by nabobalis** [comment]
I recall him wanting everything to have a changelog just so we know. Personally I was not fussed about adding logs for basic changes. The choice is yours to make.

**Comment by hayesla** [comment]
can this now be merged? @Cadair  does it need a changelog?

**Comment by nabobalis** [comment]
Nah. Let's get this merge.

**Pull request merged**
