### PR TITLE
ran unify_section_headings.py

### PR DESCRIPTION
**Pull request by nabobalis**
Maybe?

### CODE REVIEW

**Comment by Cadair** [comment]
I approve of this in theory but can we customise the ordering it uses to minimize the changes? Also can it be a pre-commit hook?

**Comment by nabobalis** [comment]
We can create a copy of the script and change it?

**Comment by Cadair** [comment]
where is the script?

**Comment by nabobalis** [comment]
https://github.com/astropy/astropy-procedures/blob/master/discontinued_usage/unify_section_headings.py

**Comment by Cadair** [comment]
I feel like we haven't historically had `*` at the top level of our titles?

**Comment by nabobalis** [comment]
We used whatever? I'm not 100% what is the official ordering of headers (even if there is one)

**Comment by Cadair** [comment]
> We used whatever?

yeah but I think we had `=` as the top level more often than not? I do wonder how this interacts with the default heading levels in `automodapi`?

**Comment by nabobalis** [comment]
Badly since the doc build failed.

I can change the order to a version we can agree on?

**Comment by Cadair** [comment]
Well this ordering from astropy is likely to fit with the defaults where `automodapi` is used like how astropy uses it. If I had to guess I would say that we use `=` as our top level in most places so that might make it a smaller change?

**Pull request merged**
