### PR TITLE
Prioritise dateavg over dateobs in wcs_frame_mapping

### LINKED ISSUE #6994: `sunpy.coordinates.wcs_utils.solar_wcs_frame_mapping` only checks `dateobs` not `dateavg`
### Describe the bug

When looks for the obstime of a WCS the `solar_wcs_frame_mapping` function should prioritise `dateavg` as it's the more modern reference time for the WCS.

Note that the DKIST data doesn't have `DATE-OBS` so this just fails to extract a obstime at all for DKIST data.

### To Reproduce

_No response_

### Screenshots

_No response_

### System Details

_No response_

### Installation method

_No response_

### PR DESCRIPTION
**Pull request by Cadair**
fixes #6994

### CODE REVIEW

**Comment by Cadair** [comment]
Only question is if we should backport this very subtle and hidden behaviour change?

**Comment by nabobalis** [comment]
> Only question is if we should backport this very subtle and hidden behaviour change?

Let 4.0 and 4.1 rest.

**Comment by Cadair** [comment]
> > Only question is if we should backport this very subtle and hidden behaviour change?
> 
> Let 4.0 and 4.1 rest.

Well, if we decide it's worthy of a backport I would quite like to get it backported so the DKIST data works properly

**Comment by nabobalis** [comment]
> > > Only question is if we should backport this very subtle and hidden behaviour change?
> > 
> > 
> > Let 4.0 and 4.1 rest.
> 
> Well, if we decide it's worthy of a backport I would quite like to get it backported so the DKIST data works properly

Ah, I guess making dkist user tools use 5.0 only might be too soon.

In that case, lets do the full backport.

**Review by nabobalis — APPROVED** [review]

**Pull request merged**
