### PR TITLE
Tests for sunpy.net.hek2vso

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Cadair** [comment]
@rajul can you rebase please?

**Comment by rajul** [comment]
All tests passing locally for me...Damn Travis!! :(

**Comment by Cadair** [comment]
@rajul interesting, you seem to have triggered the errors that are fixed in #1246

**Comment by Cadair** [comment]
I do know why they have suddenly broken for non astropy-dev builds.

**Comment by rajul** [comment]
@Cadair Why do you think? Everywhere I look in the traceback, I just see 'UnitError'

**Comment by Cadair** [comment]
@rajul Merge #1246 into this PR, that should quieten down the build a lot, then we can see the wood from the trees.

**Pull request closed without merging**
