### PR TITLE
Fix sunpy.util tests under Python 3

### PR DESCRIPTION
**Pull request by Cadair**
Another set of tests.

@nabobalis @dpshelio @drewleonard42

### CODE REVIEW

**Comment by nabobalis** [comment]
:+1:

**Comment by Cadair** [comment]
@dpshelio @sunpy/sunpy-maintainers review please.

**Comment by ehsteve** [comment]
:+1: once tests pass.

**Comment by Cadair** [comment]
test fail is travis falling over rather than a real fail.

**Pull request merged**
