### PR TITLE
Fixed the colour of mask

### LINKED ISSUE #3007: "Masking the solar disk" gallery example does not have a black mask
### Description
In the "Masking the solar disk" example, the mask is incorrectly colored. The mask is explicitly set to be black
```python
palette = aia.plot_settings['cmap']
palette.set_bad('black')
```
but it appears white in the generated gallery example. I suspect this is due to a change in the way matplotlib treats NaNs in imshow.

### Steps to Reproduce
See example gallery in docs.

### PR DESCRIPTION
**Pull request by ankursikarwar**
### Description

Fixes #3007

### CODE REVIEW

**Comment by nabobalis** [comment]
Thanks @ankursikarwar, this only fixes the example and not what seems to be an issue with setting the `palette`?

**Comment by ankursikarwar** [comment]
@nabobalis  But the original image itself has the same brightness around the edges. 

sphx_glr_aia_example_001

**Comment by nabobalis** [comment]
Sure. But the aim of the example as I see it is to mask out the middle and brighten the edges. Which is what the normalisation aims to do. So I don't think we can set it to None.

**Comment by nabobalis** [comment]
Sorry @ankursikarwar, I don't think we can go ahead and use this fix for the issue. 

If you want to make more changes or try a different issue, you can either reopen this or make a new PR.

**Pull request closed without merging**
