### PR TITLE
Remove warnings for custom attributes set on WCS

### PR DESCRIPTION
**Pull request by dstansby**
I think just ignoring them is fine now, but open to erroring if we detect these attributes instead now?

### CODE REVIEW

**Review by Cadair — CHANGES_REQUESTED** [review]
I am a little conflicted on this one. I need to have a think about it so this is a request to not merge it until I have had time to do so.

**Comment by dstansby** [comment]
Decision from weekly meeting:
- Error in 3.1/4.0
- Remove code altogether (including error) in 4.1

**Review by Cadair — APPROVED** [review]

**Comment by Cadair** [comment]
looks good but the figure tests have exploded.

**Comment by dstansby** [comment]
See https://github.com/sunpy/sunpy/issues/5372 and associated rabbit hole re. figure tests

**Review by nabobalis — APPROVED** [review]

**Pull request merged**
