### PR TITLE
Remove stored logos

### PR DESCRIPTION
**Pull request by nabobalis**
Uses theme icons directly also, enabled the parallel doc build for tox.

### CODE REVIEW

**Comment by nabobalis** [comment]
Does mean the image is a bit low res since it uses the png, I might have to add a new item for the SVG.

**Comment by nabobalis** [comment]
I have added a `svg_icon = os.path.join(html_static_path[0], "img", "sunpy_icon.svg")` to the next release.

**Comment by nabobalis** [comment]
Gallery won't use the icon. I am trying to figure it out

**Review by Cadair — APPROVED** [review]

**Comment by nabobalis** [comment]
Online
```
SKIPPED [1] ../../.tox/py38-online/lib/python3.8/site-packages/pytest_doctestplus/plugin.py:187: unable to import module local('/home/vsts/work/1/s/.tox/py38-online/lib/python3.8/site-packages/sunpy/io/setup_package.py')
FAILED ../../.tox/py38-online/lib/python3.8/site-packages/sunpy/net/jsoc/tests/test_jsoc.py::test_post_wavelength - urllib.error.HTTPError: HTTP Error 500: Internal Server Error
FAILED ../../.tox/py38-online/lib/python3.8/site-packages/sunpy/net/jsoc/tests/test_jsoc.py::test_get_request - urllib.error.HTTPError: HTTP Error 500: Internal Server Error
FAILED ../../.tox/py38-online/lib/python3.8/site-packages/sunpy/net/jsoc/tests/test_jsoc.py::test_get_request_tar - urllib.error.HTTPError: HTTP Error 500: Internal Server Error
FAILED ../../.tox/py38-online/lib/python3.8/site-packages/sunpy/net/jsoc/tests/test_jsoc.py::test_request_data_protocol - urllib.error.HTTPError: HTTP Error 500: Internal Server...
FAILED ../../.tox/py38-online/lib/python3.8/site-packages/sunpy/net/jsoc/tests/test_jsoc.py::test_request_data_method - urllib.error.HTTPError: HTTP Error 500: Internal Server E...
FAILED ../../.tox/py38-online/lib/python3.8/site-packages/sunpy/net/jsoc/tests/test_jsoc.py::test_check_request - urllib.error.HTTPError: HTTP Error 500: Internal Server Error
FAILED ../../.tox/py38-online/lib/python3.8/site-packages/sunpy/net/jsoc/tests/test_jsoc.py::test_results_filenames_as_is - urllib.error.HTTPError: HTTP Error 500: Internal Serv...
FAILED ../../.tox/py38-online/lib/python3.8/site-packages/sunpy/net/jsoc/tests/test_jsoc.py::test_max_parallel_connections - urllib.error.HTTPError: HTTP Error 500: Internal Ser...
FAILED ../../.tox/py38-online/lib/python3.8/site-packages/sunpy/net/jsoc/tests/test_jsoc.py::test_results_filenames - urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

hypothesis
```
============================================================================= short test summary info ==============================================================================
SKIPPED [1] ../../.tox/py38-hypothesis/lib/python3.8/site-packages/pytest_doctestplus/plugin.py:187: unable to import module local('/home/vsts/work/1/s/.tox/py38-hypothesis/lib/python3.8/site-packages/sunpy/io/setup_package.py')
FAILED ../../.tox/py38-hypothesis/lib/python3.8/site-packages/sunpy/coordinates/tests/test_ephemeris.py::test_consistency_with_horizons - hypothesis.errors.Flaky: Hypothesis fou...

```

**Pull request merged**
