### PR TITLE
Remove some warnings from timeseries tests

### PR DESCRIPTION
**Pull request by dstansby**
More warning removal, this time for timeseries tests.

### CODE REVIEW

**Comment by nabobalis** [comment]
Thanks @dstansby, just looks like you need to import `SunpyUserWarning` in the test file.

**Comment by nabobalis** [comment]
It seems to error now that no warning is raised. Removing the flag raises the warning but with it, it seems to fail the test? It seems odd to me.

**Comment by dstansby** [comment]
I can reproduce this behaviour with the standard `setup.cfg`. Might be something to do with custom warnings not playing nicely with the way pytest filters warnings/how the `no-warnings` command line option works?

**Comment by nabobalis** [comment]
Yeah that is a good point, I am not sure how pytest handles custom warnings. We probably want to look into or ignore those warnings for now.

**Pull request merged**
