### PR TITLE
Run figure tests with astropy v5.1.0

### PR DESCRIPTION
**Pull request by ConorMacBride**
Astropy versions before v5.1 are not compatible with numpy v1.23.0 (released yesterday). So the figure tests, which are pinned to astropy v4.2.1, are failing: https://app.circleci.com/pipelines/github/sunpy/sunpy/18426/workflows/04755d06-2562-4ef4-b1cf-2d6b41d79fdf/jobs/79538

Astropy v4.2.1 was released in April 2021 so probably a good time for an upgrade anyway, and pinning numpy instead seems counterproductive.

- [x] Review and update hashes

### CODE REVIEW

**Comment by nabobalis** [comment]
UPDATE ALL THE HASHES

**Comment by ConorMacBride** [comment]
We have one visible difference which seems fine and 6 with just hashes different. What's very strange is we have two tests where the hashes match but the images differ!!! That should be impossible, so I guess the baseline update workflow isn't working?

**Comment by ConorMacBride** [comment]
It's configured to not update any baselines if either `figure` or `figure-devdeps` fails. Is that what we want?

**Comment by nabobalis** [comment]
It should update the successful ones regardless of if the other one fails, can we update it?

**Comment by ConorMacBride** [comment]
That should work

**Comment by nabobalis** [comment]
Oh we should also update the images: https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034

**Comment by nabobalis** [comment]
Oh those new images might be a problem now:

```
ERROR: InterpreterNotFound: python3.9
```

**Comment by nabobalis** [comment]
Maybe we should just make them both use the same python version.

**Review by nabobalis — APPROVED** [review]

**Comment by ConorMacBride** [comment]
The dev figures have an upstream matplotlib bug

**Comment by nabobalis** [comment]
> The dev figures have an upstream matplotlib bug

Not anymore.

**Pull request merged**
