### PR TITLE
Allow padding in submap when bounding coordinates exceed original map boundaries

### PR DESCRIPTION
**Pull request by wtbarnes**
This PR makes a change to `submap` that pads maps when the coordinates that define the bounding box are outside of the boundaries of the original map. In other words, maps can expand in either dimension. The current behavior for submap is to clip the boundaries within the existing bounds of the map, i.e. maps cannot expand, they can only shrink.

This also adds a keyword `missing` (similar to that in `rotate`) that is used to fill in any of the expanded pixels.

This PR also fixes an inconsistency in `_parse_submap_input` where the order of the corners returned was not consistent over return types. See #6706.

## TODOs

- [ ] Discuss whether this is a good idea. This is a fairly significant change in behavior for `submap`.
- [ ] Understand why current tests are failing
- [ ] Add tests (including updates to existing ones)
- [ ] Changelog
- [ ] Update docstring to make it clear submap allows for this.
- [ ] Example?

## Example

As an example, the following code snippet creates a new map with the bottom left corner at the center of the original map and a width and height that expands far outside the original FOV,

```python
import sunpy.data.sample
import sunpy.map
import astropy.units as u

m = sunpy.map.Map(sunpy.data.sample.AIA_171_IMAGE)
m_expand = m.submap(m.wcs.world_to_pixel(m.center)*u.pix, 
                                         width=1000*u.pix,
                                         height=1000*u.pix,
                                         missing=m.data.min())
m_expand.peek()
```
image

Similarly, you can expand in all directions,

```python
margin = 1000 * u.pix
m_expand = m.submap(u.Quantity([-margin,-margin]),
                    top_right=u.Quantity([m.dimensions.x-1*u.pix+margin, m.dimensions.y-1*u.pix+margin]),
                    missing=m.data.min())
m_expand.peek()
```
image

Or just in one

```python
m_expand = m.submap(m.wcs.world_to_pixel(m.center)*u.pix,
                    width=1000*u.pix,
                    height=200*u.pix,
                    missing=m.data.min())
m_expand.peek()
```
image

Note that this also has the "fun" consequence that, for a map with even a slightly non-diagonal PCij (e.g. a level 1 AIA image), cropping the image to its bottom left and top right *world* coord results in an expanded map (see #4896),

```python
>>> m_new = m.submap(m.bottom_left_coord, top_right=m.top_right_coord)
>>> print(m_new.dimensions)
PixelPair(x=<Quantity 1028. pix>, y=<Quantity 1024. pix>)
>>> print(m.dimensions)
PixelPair(x=<Quantity 1024. pix>, y=<Quantity 1024. pix>)
```

### CODE REVIEW

**Comment by alasdairwilson** [comment]
Is there an example of a use case?

If this is controlled by a keyword that defaults to False, so is not a breaking change, then this conceptually seems fine to me.

**Comment by nabobalis** [comment]
I would like to use this in aiapy to pad de-rotated level 1.5 images to be the full 4K by 4K.

**Comment by dstansby** [comment]
At a high level I'm 👍 to this new functionality, but 👎 to putting it under `submap`. "sub" implies that you're getting less of the map back, not more. Now, having said that I don't have a better suggestion 😄 for a name of a method that both crops and expands a map, so perhaps a good way to go would be leave `submap` alone, and have a new `expandmap` or similar method for doing the expanding?

**Comment by wtbarnes** [comment]
I think I've decided that this is not a good idea so I'm closing this. If you really want this kind of functionality, you should just reproject to the appropriate FOV. If someone disagrees and wants to revive this effort, feel free to reopen.

**Pull request closed without merging**
