### PR TITLE
Revert the removal of SOHO/STEREO

### PR DESCRIPTION
**Pull request by nabobalis**
This reverts the removal of the extra SOHO and STEREO commits from UNIDOWN.

This is so these can be cleaned up at a later date for UNIDOWN.

### CODE REVIEW

**Comment by dpshelio** [comment]
What was the reason to separate all this from unidown?

**Comment by Cadair** [comment]
@dpshelio It was not integrated with Fido, there were a lot of arguments to `_get_url_for_timerange` which did not have corresponding attrs.

**Comment by dpshelio** [comment]
Thanks @Cadair - just to know what was exactly needed to do :)

**Comment by nabobalis** [comment]
Is this is got a reason to exist? 

Also I deleted my branch.

**Comment by Cadair** [comment]
This effectively contains the code in a whole GSOC project. It should be a todo for unidown somewhere / somehow.

**Pull request closed without merging**
