### PR TITLE
Remove un-used csvfile and fitsfile kwargs from _remove_lytaf_events

### PR DESCRIPTION
**Pull request by dstansby**
These are un-tested and un-used keyword arguments for a private function, so remove them and their corresponding code paths. If someone has a good reason to keep them, they should be made public and tested by adding them to the public `remove_lytaf_events`.

### CODE REVIEW

**Comment by wtbarnes** [comment]
This looks good to me. However, I find it odd that this function is documented as if it is part of the public-facing API, i.e. it has a fairly extensive example in the docstring that makes it look as if it is supposed to be used directly.

**Comment by dstansby** [comment]
> This looks good to me. However, I find it odd that this function is documented as if it is part of the public-facing API, i.e. it has a fairly extensive example in the docstring that makes it look as if it is supposed to be used directly.

Yes, I did think this - maybe a rummage in the git blame could explain this?

**Comment by wtbarnes** [comment]
Looks like @DanRyanIrish is the one who originally wrote this. Perhaps he can give some insight as to whether this is meant to be a user-facing function or not?

**Comment by nabobalis** [comment]
Isn't this technically an API change? Won't be need to add a warning  in 1.0?

**Comment by dstansby** [comment]
No, because it's changing the API for a non-public (ie. underscored) function.

**Comment by nabobalis** [comment]
> No, because it's changing the API for a non-public (ie. underscored) function.

Good point, I glossed over the `_`

**Pull request merged**
