### PR TITLE
[unidown]: fixing for type error during setup.py test

### PR DESCRIPTION
**Pull request by ankitkmr**

### CODE REVIEW

**Comment by Cadair** [comment]
Thanks @ankitkmr.
The downside of solving it this way is that the URL is defined twice in the class. It would be better if it were only defined once, then if it changes there is only one place to change it.

There are a couple of ways to solve it, one is to make the default URL an attribute of the class, rather than a method and then just return that attribute from the troublesome functions.

**Comment by ankitkmr** [comment]
@Cadair default urls made class attributes !!

**Comment by Cadair** [comment]
looks good! Thanks.

**Comment by ankitkmr** [comment]
Closing Down. Has been Included in #1476

**Pull request closed without merging**
