### PR TITLE
show_colormaps() should check how much display room is available #1781

### PR DESCRIPTION
**Pull request by abit2**
generate plots which are larger than the screen so cannot see all of the colormaps

### CODE REVIEW

**Comment by dpshelio** [comment]
:+1:

**Comment by dpshelio** [comment]
@abit2 I've seen you have a few commits for this change, I wonder wether you could squash them into only one, so we don't get these commit messages and changes that were not happening.

**Comment by abit2** [comment]
@dpshelio 
git rebase -i origin/master 
gives me http://pastebin.com/g3aPiWXi
help me

**Comment by dpshelio** [comment]
@abit2 - you should look in detail how to work with branches.. it's not a good practice to work in your `master` as - in principle - that's the one you keep up to date with `upstream`. So, my recommendation is:
```bash
cd sunpy
git remote add upstream git@github.com:sunpy/sunpy.git # if you've got it already will say so
git fetch upstream
git checkout -b dpi upstream/master # this creates a new branch from master
git cherry-pick e89a02b35766446b89  # this copy the changes you made, that you want to suggest
git push origin dpi # that creates a new branch in your github repository

### then if you want to update your master
git branch -D master
git checkout -b master upstream/master
git push -f origin master # that makes a *force* push to your github repository, so it forgets what it was there before.
```
ping us in the IRC if you have troubles.

Once you've done that, then you can open a new pull request from your `dpi` branch to sunpy's `master` branch, and close this one.

**Pull request closed without merging**
