### PR TITLE
Remove aiaprep and associated tests

### LINKED ISSUE #3282: Remove sunpy.instr.aia.aiaprep
The `aiaprep` function should be removed from the `sunpy.instr` subpackage. Any AIA specific functionality should transition to the new [`aiapy` package](https://gitlab.com/LMSAL_HUB/aia_hub/aiapy).

This is part of the broader goal of moving instrument-specific functionality out of the core sunpy package and into affiliated packages.

### PR DESCRIPTION
**Pull request by wtbarnes**
Resolves #3282. According to our deprecation policy, `aiaprep` can be removed in 2.1.

### CODE REVIEW

**Review by nabobalis — APPROVED** [review]

**Comment by wtbarnes** [comment]
This is technically a breaking change from 2.0->2.1, but I guess we have the deprecation in 2.0 this is ok?

**Comment by dstansby** [comment]
Where is the deprecation policy stored? I tried searching https://docs.sunpy.org/en/latest/dev_guide/index.html but to no avail 😢

**Comment by wtbarnes** [comment]
> Where is the deprecation policy/breaking change policy stored? I tried searching https://docs.sunpy.org/en/latest/dev_guide/index.html but to no avail 😢

It is in [SEP-009](https://github.com/sunpy/sunpy-SEP/blob/master/SEP-0009.md#deprecations-and-documentation)

**Review by dstansby — APPROVED** [review]

**Comment by dstansby** [comment]
I think breaking changes are fine (there's at least a couple already)

**Review by dstansby — CHANGES_REQUESTED** [review]
Actually, doc build fails are real: 
```
Handler <function process_automodsumm_generation at 0x7f5ea5ba44c0> for event 'builder-inited' threw an exception (exception: No module named 'sunpy.instr.aia')
```

**Comment by Cadair** [comment]
To be pedantic:

A "breaking change" is a change which breaks code *without a deprecation warning*. A removal of code after the established deprecation period (one LTS release) is not a breaking change (at least per the changelog / removal rules).

**Review by Cadair — APPROVED** [review]
lgtm pending doc fix :)

**Comment by wtbarnes** [comment]
> To be pedantic:
> 
> A "breaking change" is a change which breaks code _without a deprecation warning_. A removal of code after the established deprecation period (one LTS release) is not a breaking change (at least per the changelog / removal rules).

I'm very ok with pedantry in this case 😄

**Comment by wtbarnes** [comment]
Hopefully the docs should now pass 🤞

**Comment by dstansby** [comment]
1 `instr` sub-module down, 5 to go...

**Review by dstansby — APPROVED** [review]
Test failure is unrelated

**Pull request merged**
