### PR TITLE
Fix file names when downloading multiple files using database.download

### LINKED ISSUE #1164: database.fetch() downloads files all with the same name.
```python
import sunpy.database
db = sunpy.database.Database('sqlite:///')

db.fetch(vso.attrs.Time('2011/9/12T20:30:00', '2011/9/12T21:00:00'),
              vso.attrs.Wave(171,171), vso.attrs.Instrument('AIA'),
              vso.attrs.Sample(300))
```

gets me the following files in my default download dir:

```
-rw-r--r-- 1 stuart stuart 33M Aug 28 18:43 /home/stuart/sunpy/data/aia_lev1_171a_2011_09_12t20_35_00_34z_image_lev1_fits
-rw-r--r-- 1 stuart stuart 33M Aug 28 18:45 /home/stuart/sunpy/data/aia_lev1_171a_2011_09_12t20_35_00_34z_image_lev1_fits.0
-rw-r--r-- 1 stuart stuart 33M Aug 28 18:45 /home/stuart/sunpy/data/aia_lev1_171a_2011_09_12t20_35_00_34z_image_lev1_fits.0.0
-rw-r--r-- 1 stuart stuart 33M Aug 28 18:47 /home/stuart/sunpy/data/aia_lev1_171a_2011_09_12t20_35_00_34z_image_lev1_fits.0.0.0
-rw-r--r-- 1 stuart stuart 33M Aug 28 18:47 /home/stuart/sunpy/data/aia_lev1_171a_2011_09_12t20_35_00_34z_image_lev1_fits.0.0.0.0
-rw-r--r-- 1 stuart stuart 33M Aug 28 18:48 /home/stuart/sunpy/data/aia_lev1_171a_2011_09_12t20_35_00_34z_image_lev1_fits.0.0.0.0.0
```

As you can see all the files have the same name.

### PR DESCRIPTION
**Pull request by Cadair**
This fixes the outstanding problem in #1336 for speedy 0.6 merge.

closes #1336 

closes #1164

### CODE REVIEW

**Comment by Cadair** [comment]
ping @ayshih @ehsteve

**Comment by ayshih** [comment]
:+1:

**Comment by Cadair** [comment]
@sunpy/sunpy-maintainers someone else please review this.

**Comment by dpshelio** [comment]
:+1:

**Comment by rajul** [comment]
@Cadair thanks!! :+1:

**Pull request merged**
