### PR TITLE
Update to _Range object

### PR DESCRIPTION
**Pull request by ehsteve**
### Description

This change allows for the following
```python
from sunpy.net import attrs as a
171 * u.mm in a.Wavelength(100 * u.mm, 200 * u.mm)
```

Fixes NA

### CODE REVIEW

**Comment by Cadair** [comment]
Looks good, changelog entry and tests please!

**Comment by ehsteve** [comment]
@Cadair I hope you understand that this part of my master plan to have the attrs sent to the clients. ;)

**Comment by Cadair** [comment]
You mean instead of the kwargs for `_get_url_for_timerange`?

**Comment by ehsteve** [comment]
Just pass it as a list to an attr keyword. Then a client could just check what was in the list and not need to figure out how attrs are related to keywords and what gets passed in. Presumably they would already have some familiarity with attrs as a user.

**Comment by Cadair** [comment]
Yeah, I think in general it makes sense to use the attrs as dev api as well. This probably isn't the right place for this discussion though :laughing:

**Comment by ehsteve** [comment]
Just my quick idea anyway

**Comment by wafels** [comment]
could do the same for a.Time ?

**Pull request merged**
