### PR TITLE
Remove sunpy.image.coalignment

### PR DESCRIPTION
**Pull request by dstansby**

### CODE REVIEW

**Comment by nabobalis** [comment]
I assume it just needs a changelog?

**Comment by nabobalis** [comment]
The decision was made to remove all deprecated code closer to the release of 4.1 incase we need to backport any bug fixes as it will make it harder.

**Comment by wtbarnes** [comment]
Why not just leave this in draft until then? I don't see a need to close it.

**Comment by nabobalis** [comment]
If we aren't planning to merge a PR for a long period of time, I don't see why it should stay open.

**Comment by dstansby** [comment]
👍 I'll make sure not to delete the branch

**Pull request closed without merging**
