### PR TITLE
Fix bug in convert_data_to_pixel

### LINKED ISSUE #1763: convert_data_to_pixel issue
This line in convert_data_to_pixel:
  pixelx = (x - crval[0]) / cdelt[0] + (crpix[1] - 1)
should be:
  pixelx = (x - crval[0]) / cdelt[0] + (crpix[0] - 1)

I found the problem using 0.6.3, but looking at the source, it persists in 0.6.4.

### PR DESCRIPTION
**Pull request by Cadair**
closes #1763

### CODE REVIEW

**Comment by wafels** [comment]
+1

**Comment by dpshelio** [comment]
This is a great opportunity to add a test for this :)

**Comment by Cadair** [comment]
@dpshelio nah, it's going to be deprecated in 0.8 anyway, I have better things to do ;)

**Comment by dpshelio** [comment]
:+1:  - because @Cadair has better things to do...

**Pull request merged**
