### PR TITLE
Test docs build with sphinx-automodapi fork that fixes the inheritance-diagram links

### PR DESCRIPTION
**Pull request by ayshih**
See #2097 for context

DO NOT MERGE

### CODE REVIEW

**Comment by ConorMacBride** [comment]
This has now broken the links in the [coordinates page](https://sunpy--6267.org.readthedocs.build/en/6267/code_ref/coordinates/index.html#class-inheritance-diagram), which was working before (but for some unknown reason is now also broken on latest). I haven't looked at your fix in detail, but I think the difference in the number of directories between the current page and the api page needs to be calculated for each inheritance diagram to decide how many directories to move up.

**Comment by ayshih** [comment]
> This has now broken the links in the [coordinates page](https://sunpy--6267.org.readthedocs.build/en/6267/code_ref/coordinates/index.html#class-inheritance-diagram), which was working before

It was actually never truly working.  The links were wrong, but the RTD build for our PRs happens to map wrong links at a certain level back to correct links.  That doesn't happen on our actual docs site.

**Comment by ayshih** [comment]
To illustrate what I mean:

Correct URL: https://sunpy--6267.org.readthedocs.build/en/6267/generated/api/sunpy.coordinates.SunPyBaseCoordinateFrame.html
Incorrect URL and fails: https://sunpy--6267.org.readthedocs.build/en/generated/api/sunpy.coordinates.SunPyBaseCoordinateFrame.html
More incorrect URL but works on PR RTD build: https://sunpy--6267.org.readthedocs.build/generated/api/sunpy.coordinates.SunPyBaseCoordinateFrame.html

**Comment by ayshih** [comment]
The above discussion applied to an earlier, attempted fix via `sphinx_automodapi`.  This PR now shows that my pending PR to `sphinx` itself (sphinx-doc/sphinx#10576) fixes the links in all inheritance diagrams.

**Comment by Cadair** [comment]
This still hasn't fixed references which are external (intersphinx) I guess that's a separate bug.

**Comment by ConorMacBride** [comment]
> This still hasn't fixed references which are external (intersphinx) I guess that's a separate bug.

There's a feature request from over 10 years ago: https://github.com/sphinx-doc/sphinx/issues/865 Maybe you can see a quick fix for this @ayshih since working on this bug? 😃

**Comment by Cadair** [comment]
I hacked a solution to this once by detecting if the URL starts with https: and treating it differently in the code Albert fixed in sphinx.

**Comment by ayshih** [comment]
Hmm, seems especially finicky that intersphinx is not finding some of these references, so not sure what's going on there.  But, when it works, it works.

**Comment by ConorMacBride** [comment]
Do you mean, for example, `NDData` in [this diagram](https://sunpy--6267.org.readthedocs.build/en/6267/code_ref/map.html#class-inheritance-diagram)? The link is present [here in the docs](https://sunpy--6267.org.readthedocs.build/en/6267/generated/api/sunpy.map.GenericMap.html#sunpy.map.GenericMap) but not in the diagram.

**Comment by ayshih** [comment]
Yeah.  Some of the other Astropy boxes work, so _something_ is working.  I've seen Python boxes work too.  But many boxes that should work do not for some reason that I need to figure out.

**Comment by ayshih** [comment]
Investigation update:

The sticking point is when a class is not documented where it actually lives in code space.  For example, `BaseCoordinateFrame` is defined in `astropy.coordinates.baseframe.py`, but is documented only one level up as `astropy.coordinates.BaseCoordinateFrame`.  Thus, `astropy.coordinates.baseframe.BaseCoordinateFrame` does not show up in the inventory.

When `inheritance_diagram` wants to have a box for `astropy.coordinates.baseframe.BaseCoordinateFrame`, it creates a fake intersphinx reference to get `intersphinx` to figure out the associated URL.  `intersphinx` figures out that the reference ought to be rewritten to `astropy.coordinates.BaseCoordinateFrame` (i.e., drops the `baseframe`) and correctly finds the appropriate URL.  The problem is that when `inheritance_diagram` goes back through the now-resolved fake references, it can't find one for `astropy.coordinates.baseframe.BaseCoordinateFrame` – because it didn't know about the rewriting – and so thinks there is no URL to use.

**Comment by ayshih** [comment]
Sweet, my latest change to my Sphinx fork fixes all of the external boxes in the inheritance diagrams.  Try it out!  It may be a bit too non-trivial a fix to combine with my open PR, though.

**Comment by ayshih** [comment]
I've put up a new PR to Sphinx with all of these fixes: sphinx-doc/sphinx#10614

**Comment by nabobalis** [comment]
I assume there has been no movement upstream?

**Comment by ayshih** [comment]
<shrug>  There's been no response at all on the Sphinx repo

**Comment by ayshih** [comment]
There's been back and forth on the Sphinx PR (sphinx-doc/sphinx#10614), but it hasn't been merged yet.

**Comment by nabobalis** [comment]
As stale bot has come for this and there has been no upstream movement, I will close for this for now. Hopefully when sphinx merge the PR, we can re-run this to make sure it works.

**Comment by ayshih** [comment]
sphinx-doc/sphinx#10614 has now been merged, so I'm going to use this PR to now test my sphinx-automodapi PR (astropy/sphinx-automodapi#172)

**Comment by pllim** [comment]
Is the doc build supposed to take this long?

**Comment by nabobalis** [comment]
> Is the doc build supposed to take this long?

Our RTD build? No, we have been having a problem with RTD all day.

**Comment by ayshih** [comment]
Yay, the RTD build actually completed on the latest re-run instead of stalling out!

At last, fully functional inheritance diagrams, e.g.:
https://sunpy--6267.org.readthedocs.build/en/6267/reference/coordinates/index.html#class-inheritance-diagram
https://sunpy--6267.org.readthedocs.build/en/6267/reference/net.html#id10

**Comment by pllim** [comment]
The diagrams do look fixed but maybe you want to rebase to pick up the new theme, just in case?

https://docs.sunpy.org/en/latest/reference/coordinates/index.html#class-inheritance-diagram

vs

https://sunpy--6267.org.readthedocs.build/en/6267/reference/coordinates/index.html#class-inheritance-diagram

**Comment by ayshih** [comment]
Unfortunately, our theme (`sunpy-sphinx-theme`) pins to Sphinx<6, which means we can't make use of sphinx-doc/sphinx#10614.  That's why I ripped out our normal theme for this test PR.

**Comment by pllim** [comment]
That's unfortunate, but I think this proves the point for sphinx-astropy PR, so I'll go over there and merge that one. Thanks!

**Comment by ayshih** [comment]
No longer of use

**Pull request closed without merging**
