### PR TITLE
Fix scraper file timerange

### PR DESCRIPTION
**Pull request by dstansby**
Fixes https://github.com/sunpy/sunpy/issues/5217, by making sure that the code determining the timerange a given file represents extends across the smallest interval specified in the filename.

### CODE REVIEW

**Comment by nabobalis** [comment]
Or is this a bugfix?

**Comment by dstansby** [comment]
I'm not sure - since this behaviour wasn't clearly previously documented, I'd say we shouldn't backport this and brand it as a new feature?

**Review by nabobalis — APPROVED** [review]

**Review by samaloney — COMMENTED** [review]
Nice, perhaps an offline test for `_check_timerange` function could be a useful addition?

**Review by samaloney — APPROVED** [review]

**Review by Cadair — APPROVED** [review]

**Comment by dstansby** [comment]
I've check the test failures and they look unrelated, so merging

**Pull request merged**
