### PR TITLE
Add pyerfa as core dep and fix imports (fixes devdeps)

### PR DESCRIPTION
**Pull request by nabobalis**
Import has now changed.

### CODE REVIEW

**Comment by ayshih** [comment]
("long overdue" because we could have "fixed" those imports once Astropy 4.2 became the minimum dependency)

**Comment by nabobalis** [comment]
Done.

**Review by dstansby — CHANGES_REQUESTED** [review]
The new dependency should get a changelog entry. Also I'm not sure about backporting a new dependency... can we just ignore the warning on 5.x?

**Comment by nabobalis** [comment]
> The new dependency should get a changelog entry. Also I'm not sure about backporting a new dependency... can we just ignore the warning on 5.x?

Hmm, I would say that since pyefra has been a core dependency of astropy for years now, the fact we are adding to ours I don't think changes anything. 

I can add the ignore warning to those releases. 

I will leave this choice up to you and Albert.

**Comment by ayshih** [comment]
While `pyerfa` would become a new *direct* dependency, it has been an indirect dependency since our minimum `astropy` dependency became 4.2 (i.e., `sunpy` 3.1, over two years ago).  That is, making an indirect dependency a direct dependency has zero effect on anyone with a valid installation of `sunpy` 3.1+, since their environment is "guaranteed" to have `pyerfa` present.

My inclination is to go ahead with the backport, because it cleans up the code, but I do think there should be a changelog (`trivial`), primarily to alert anyone who might have a bizarrely inconsistent environment.

**Comment by nabobalis** [comment]
Rebaesd and added changelog.

**Review by ayshih — APPROVED** [review]
Can you do me a favor and add it to `sunpy-dev-env.yml` as well?

**Comment by nabobalis** [comment]
Ah I forgot!

**Review by dstansby — APPROVED** [review]

**Pull request merged**
