### PR TITLE
Deprecate `GenericMap.draw_rectangle()` in favor of `GenericMap.draw_quadrangle()`

### LINKED ISSUE #5230: Deprecate `GenericMap.draw_rectangle()`
Deprecate `GenericMap.draw_rectangle()` in favor or `GenericMap.draw_quadrangle()` (cf. https://github.com/sunpy/sunpy/pull/4809#pullrequestreview-594269716)

### PR DESCRIPTION
**Pull request by ayshih**
Closes #5230

### CODE REVIEW

**Comment by ayshih** [comment]
Oops.  I just realized that there is one thing that `draw_rectangle()` does that `draw_quadrangle()` does not do: draw rectangles on non-WCSAxes maps.  Is that something we still want to support?  Maybe we can put this deprecation in and see whether anyone reacts?

**Comment by Cadair** [comment]
Perhaps now is the time to just deprecate non-wcsaxes plotting completely??

**Comment by ayshih** [comment]
> Perhaps now is the time to just deprecate non-wcsaxes plotting completely??

I just discovered that `draw_contours()` currently gives the wrong result on a non-WCSAxes plot.  +1 to getting rid of non-WCSAxes plotting.

**Comment by nabobalis** [comment]
> > Perhaps now is the time to just deprecate non-wcsaxes plotting completely??
> 
> I just discovered that `draw_contours()` currently gives the wrong result on a non-WCSAxes plot. +1 to getting rid of non-WCSAxes plotting.

I guess the question is, this PR or another PR?

**Comment by Cadair** [comment]
> I guess the question is, this PR or another PR?

A different one.

**Review by dstansby — APPROVED** [review]

**Pull request merged**
