### PR TITLE
Issue #7478: fixes inaccuracies in sunny.map.maputils.py using SkyCoord() function instead of Cartesian approximation

### PR DESCRIPTION
**Pull request by simoneferretti**
## PR Description
pre-commit.ci autofix

### CODE REVIEW

**Comment by simoneferretti** [comment]
pre-commit.ci autofix

**Comment by nabobalis** [comment]
Thank you for the PR @simoneferretti.

Unfortunately, the tests are failing on the CI, can you debug and fix them please?

**Comment by ayshih** [comment]
Please don't use `SkyCoord.separation()` because it is too complex and too slow for this (special) case.  The correct equation is straightforward for those who remember trigonometry.

Also, be careful when working with quantities.  You've multiplied a quantity which already has units of arcseconds by `u.deg`.

**Comment by ayshih** [comment]
Thank you for attempting to fix the issue!  However, since the straightforward solution is much simpler than the approach you took, I have submitted #7512 and am closing this PR.

**Pull request closed without merging**
