### PR TITLE
Fido indexing fixes and improvements

### LINKED ISSUE #2140: Fido UnifiedResponse is still not indexing properly
```python
from sunpy.net import Fido, attrs as a
res = Fido.search(a.Time("2016-06-07", "2016-06-08"), a.Instrument('eve') | a.Instrument('goes'))
res[0]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 15472, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 3634, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/sunpy/net/fido_factory.py", line 67, in __getitem__
    return type(self)(ret)
  File "/usr/lib/python3.6/site-packages/sunpy/net/fido_factory.py", line 57, in __init__
    raise Exception("{} is not a valid input to UnifiedResponse.".format(type(lst)))
Exception: <class 'sunpy.net.vso.vso.QueryResponse'> is not a valid input to UnifiedResponse.
```
ping @DanRyanIrish @dpshelio

### LINKED ISSUE #2157: UnifiedResponse should support slicing the results objects it contains
If you have 5 clients, you should be able to sub-select the results from client 1 and ignore the others then pass to `Fido.fetch`.

@SolarDrew go!

### PR DESCRIPTION
**Pull request by Cadair**
This fixes #2140 and proposes a solution to close #2157.

The proposed solution to #2157 is to support two dimensional indexing for `UnifiedResponse` (the things that `Fido.search` returns) objects. The first index is for the client (must always be present) and the second index is for the records that client responded.

See example:
```python
In [8]: from sunpy.net import Fido, attrs as a

In [9]: uresp = Fido.search(a.Time("2012/1/1", "2012/1/2"),
                            a.Instrument("lyra") | a.Instrument("eve"))

In [10]: uresp[0]
```
```
Out[10]: 
<sunpy.net.fido_factory.UnifiedResponse object at 0x7f1ba8650cf8>
Results from the LYRAClient:
<class 'sunpy.net.dataretriever.client.QueryResponse'><Table length=2>
     Start Time           End Time      Source Instrument Wavelength
       str19               str19         str6     str4       str3   
------------------- ------------------- ------ ---------- ----------
2012-01-01 00:00:00 2012-01-02 00:00:00 Proba2       lyra        nan
2012-01-01 00:00:00 2012-01-02 00:00:00 Proba2       lyra        nan
```
```python
In [11]: uresp[1, ::5]
```
```
Out[11]: 
<sunpy.net.fido_factory.UnifiedResponse object at 0x7f1ba8490668>
Results from the VSOClient:
<QTable length=11>
   Start Time [1]       End Time [1]    Source Instrument   Type   Wavelength [2]
                                                                      Angstrom   
       str19               str19         str3     str3      str8      float64    
------------------- ------------------- ------ ---------- -------- --------------
2012-01-01 00:00:00 2012-01-02 00:00:00    SDO        EVE FULLDISK   1.0 .. 304.0
2012-01-01 03:00:00 2012-01-01 04:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 08:00:00 2012-01-01 09:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 13:00:00 2012-01-01 14:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 18:00:00 2012-01-01 19:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 23:00:00 2012-01-02 00:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 03:00:00 2012-01-01 04:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 08:00:00 2012-01-01 09:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 13:00:00 2012-01-01 14:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 18:00:00 2012-01-01 19:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 23:00:00 2012-01-02 00:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
```

The new slicing behaviour still needs tests, but I wanted to get some feedback on the idea first.

### CODE REVIEW

**Comment by dpshelio** [comment]
Cool!! so then we can fetch these results we want?? Brilliant!! Thanks!!!!

**Comment by dpshelio** [comment]
This is such a beauty!! I will defend it till death if needed!!

**Comment by ehsteve** [comment]
@Cadair though I think this capability is neat I would vote that at this point we continue to provide a flat time-ordered list that can be indexed with one index (like VSO client currently does). I suggest that we add filtering (by provider or otherwise) in the future and add it this capability while not removing simple indexing.

**Comment by Cadair** [comment]
@ehsteve I (obviously?) disagree, for both practical and philosophical reasons.

## Philosophical

Yes, the current (two) clients, VSO and JSOC, return a time-ordered list of results (order decided by server I think), however, `Fido` is explicitly a single interface to multiple clients, we should make this apparent to users so they know what to expect. It's an easy concept to wrap your head around, and will prevent surprises later.

Also, providing a "filter" mechanism would be completely redundant, we have an arbitrarily complex search system (just chain attrs together) so why bother filtering the results of a query when you can just refine the search?

## Practical

This could really be summed up as "if you want that you do it". What you are proposing would be *hard*. Each client can (and does) have it's own `QueryResponse` object, and each of these query response objects holds the client used for the query (which is then used for the download). To provide an interface to the results which was contiguous over clients would be much less powerful, either restrictive on the results a `query` method could return or challenging to maintain a translation layer in `UnifiedResponse`.

I propose this solution after some serious consideration. While I agree it is not the *simplest* possible answer I think it strikes the optimum balance between power and ease of use. The user has to realise one thing, `Fido` queries multiple places and then I think it's easy enough to understand what's going on assuming you are familiar with numpy indexing.

**Comment by ehsteve** [comment]
Why should users care where their data comes from? The point of Fido search is that they don't need to.  The search is now the same for all providers. Why should a user need to care once the results come in? It's not consistent.

**Comment by ehsteve** [comment]
If this is the easiest to implement at this point then I am fine with that but being that we are becoming more mature we need to be more deliberate on defining API. We shouldn't provide API (that the user has to learn) unless we are close to sure we won't change it because then the user will have to unlearn it and learn a new API.

**Comment by Cadair** [comment]
@ehsteve 

> Why should users care where their data comes from? [...] The search is now the same for all providers. 

The search is the same yes, however the data returned from the searches need not be. For instance JSOC supports queries by things that are not time (I.e. HARPNUM) and services like HEK return a whole host of metadata.

The reason therefore that users need to know where the data came *from* is because the form of the return and the source of the data are coupled together in a very important manner. One of which would be expectionaly challenging to uncouple in an API layer.

**Comment by Cadair** [comment]
We discussed this at the meeting today (now without @ehsteve rather than without me). @ayshih proposed something like the following.

If anyone would like to propose an alternative API to this, which addresses the technical requirements of implementing it *before* the 24th July I will be very happy to put the proposals out to a wider audience for feedback.

Given, however, the limited time left in the 0.8 cycle and the fact that the objections to this PR (list of clients as a response object) have been in the `unidown` branch since the original implementation sometime in 2014 I am unwilling to devote a large amount of developer time to this, we have more urgent work to hit our SPD deadline.

**Comment by ehsteve** [comment]
Sorry for missing the meeting! @ayshih met (without @Cadair) ;) and I think we can deal with most of my discomfort here by providing good introspection so that a user can easily figure out how to work with a response object. Here are some recommendations

```python
In [8]: from sunpy.net import Fido, attrs as a

In [9]: uresp = Fido.search(a.Time("2012/1/1", "2012/1/2"), a.Instrument("lyra")|a.Instrument("eve"))

In [10]: uresp
<sunpy.net.fido_factory.UnifiedResponse object at 0x7f1ba8650cf8>
Number of data providers <2>
Results from the LYRAClient <2 files>
Results from the VSOClient <11 files>
NOTE: For a list of files, index the object.

In [11]: len(uresp)
2
```

```python
# get all of the files from all of the providers
In [12]: Fido.fetch(usresp)

# get all of the files from the first provider
In [13]: Fido.fetch(usresp[0])

# get every other file from the second provider
In [14]: Fido.fetch(uresp[1, ::2])
```

**Comment by SolarDrew** [comment]
Personally I think this API is decent, but it came out of a conversation Cadair and I had, so take that opinion for what it's worth. We talked about it for some time and and came up with several other options but none of them were as clean or intuitive while actually solving #2140 and not introducing a load of other unsuitable behaviour.

I think this method of indexing is fairly straightforward to use and learn (and unlearn) once you accept the premise that indexing a UnifiedWossname returns a UnifiedWossname, which should be made clear in the docs anyway if that's going to continue to be the case. Also, I suspect that changing this API to something else in the future if necessary is likely to cause less hassle than when Map changed from being an array to not being an array, for instance.

**Comment by Cadair** [comment]
I have now updated the `str` and `repr` functions so the output looks like this:

```python
>>> from sunpy.net import Fido, attrs as a
>>> Fido.search(a.Time("2012/1/1", "2012/1/2"), a.Instrument("lyra") | a.Instrument("eve"))
```
```
<sunpy.net.fido_factory.UnifiedResponse object at 0x7f0c77be8c88>
Query Returned Results from 2 Providers:

2 Results from the LYRAClient:
     Start Time           End Time      Source Instrument Wavelength
       str19               str19         str6     str4       str3   
------------------- ------------------- ------ ---------- ----------
2012-01-01 00:00:00 2012-01-02 00:00:00 Proba2       lyra        nan
2012-01-01 00:00:00 2012-01-02 00:00:00 Proba2       lyra        nan

54 Results from the VSOClient:
   Start Time [1]       End Time [1]    Source Instrument   Type   Wavelength [2]
                                                                      Angstrom   
       str19               str19         str3     str3      str8      float64    
------------------- ------------------- ------ ---------- -------- --------------
2012-01-01 00:00:00 2012-01-02 00:00:00    SDO        EVE FULLDISK   1.0 .. 304.0
2012-01-02 00:00:00 2012-01-03 00:00:00    SDO        EVE FULLDISK   1.0 .. 304.0
2012-01-01 00:00:00 2012-01-01 01:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 01:00:00 2012-01-01 02:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 02:00:00 2012-01-01 03:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 03:00:00 2012-01-01 04:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 04:00:00 2012-01-01 05:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 05:00:00 2012-01-01 06:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 06:00:00 2012-01-01 07:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 07:00:00 2012-01-01 08:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 08:00:00 2012-01-01 09:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 09:00:00 2012-01-01 10:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 10:00:00 2012-01-01 11:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 11:00:00 2012-01-01 12:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 12:00:00 2012-01-01 13:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 13:00:00 2012-01-01 14:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 14:00:00 2012-01-01 15:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 15:00:00 2012-01-01 16:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 16:00:00 2012-01-01 17:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 17:00:00 2012-01-01 18:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 18:00:00 2012-01-01 19:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 19:00:00 2012-01-01 20:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 20:00:00 2012-01-01 21:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 21:00:00 2012-01-01 22:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 22:00:00 2012-01-01 23:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
                ...                 ...    ...        ...      ...            ...
2012-01-01 02:00:00 2012-01-01 03:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 03:00:00 2012-01-01 04:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 04:00:00 2012-01-01 05:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 05:00:00 2012-01-01 06:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 06:00:00 2012-01-01 07:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 07:00:00 2012-01-01 08:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 08:00:00 2012-01-01 09:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 09:00:00 2012-01-01 10:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 10:00:00 2012-01-01 11:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 11:00:00 2012-01-01 12:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 12:00:00 2012-01-01 13:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 13:00:00 2012-01-01 14:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 14:00:00 2012-01-01 15:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 15:00:00 2012-01-01 16:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 16:00:00 2012-01-01 17:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 17:00:00 2012-01-01 18:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 18:00:00 2012-01-01 19:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 19:00:00 2012-01-01 20:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 20:00:00 2012-01-01 21:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 21:00:00 2012-01-01 22:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 22:00:00 2012-01-01 23:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 23:00:00 2012-01-02 00:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-02 00:00:00 2012-01-02 01:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 00:00:00 2012-01-02 00:00:00    SDO        EVE FULLDISK  1.0 .. 1050.0
2012-01-02 00:00:00 2012-01-03 00:00:00    SDO        EVE FULLDISK  1.0 .. 1050.0
```

**Comment by Cadair** [comment]
The html repr looks like this:
screenshot from 2017-07-16 17-40-14

**Comment by Cadair** [comment]
```
In [1]: from sunpy.net import Fido, attrs as a; uresp = Fido.search(a.Time("2012/1/1", "2012/1/2"), a.Instrument("lyra") | a.Instrument("eve"))

In [2]: uresp
Out[2]: 
<sunpy.net.fido_factory.UnifiedResponse object at 0x7f9416712be0>
Results from 2 Providers:

2 Results from the LYRAClient:
     Start Time           End Time      Source Instrument Wavelength
       str19               str19         str6     str4       str3   
------------------- ------------------- ------ ---------- ----------
2012-01-01 00:00:00 2012-01-02 00:00:00 Proba2       lyra        nan
2012-01-01 00:00:00 2012-01-02 00:00:00 Proba2       lyra        nan

54 Results from the VSOClient:
   Start Time [1]       End Time [1]    Source Instrument   Type   Wavelength [2]
                                                                      Angstrom   
       str19               str19         str3     str3      str8      float64    
------------------- ------------------- ------ ---------- -------- --------------
2012-01-01 00:00:00 2012-01-02 00:00:00    SDO        EVE FULLDISK   1.0 .. 304.0
2012-01-02 00:00:00 2012-01-03 00:00:00    SDO        EVE FULLDISK   1.0 .. 304.0
2012-01-01 00:00:00 2012-01-01 01:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 01:00:00 2012-01-01 02:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 02:00:00 2012-01-01 03:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 03:00:00 2012-01-01 04:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 04:00:00 2012-01-01 05:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 05:00:00 2012-01-01 06:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 06:00:00 2012-01-01 07:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 07:00:00 2012-01-01 08:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 08:00:00 2012-01-01 09:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 09:00:00 2012-01-01 10:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 10:00:00 2012-01-01 11:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 11:00:00 2012-01-01 12:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 12:00:00 2012-01-01 13:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 13:00:00 2012-01-01 14:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 14:00:00 2012-01-01 15:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 15:00:00 2012-01-01 16:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 16:00:00 2012-01-01 17:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 17:00:00 2012-01-01 18:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 18:00:00 2012-01-01 19:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 19:00:00 2012-01-01 20:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 20:00:00 2012-01-01 21:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 21:00:00 2012-01-01 22:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 22:00:00 2012-01-01 23:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
                ...                 ...    ...        ...      ...            ...
2012-01-01 02:00:00 2012-01-01 03:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 03:00:00 2012-01-01 04:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 04:00:00 2012-01-01 05:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 05:00:00 2012-01-01 06:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 06:00:00 2012-01-01 07:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 07:00:00 2012-01-01 08:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 08:00:00 2012-01-01 09:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 09:00:00 2012-01-01 10:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 10:00:00 2012-01-01 11:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 11:00:00 2012-01-01 12:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 12:00:00 2012-01-01 13:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 13:00:00 2012-01-01 14:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 14:00:00 2012-01-01 15:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 15:00:00 2012-01-01 16:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 16:00:00 2012-01-01 17:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 17:00:00 2012-01-01 18:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 18:00:00 2012-01-01 19:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 19:00:00 2012-01-01 20:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 20:00:00 2012-01-01 21:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 21:00:00 2012-01-01 22:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 22:00:00 2012-01-01 23:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 23:00:00 2012-01-02 00:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-02 00:00:00 2012-01-02 01:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 00:00:00 2012-01-02 00:00:00    SDO        EVE FULLDISK  1.0 .. 1050.0
2012-01-02 00:00:00 2012-01-03 00:00:00    SDO        EVE FULLDISK  1.0 .. 1050.0


In [3]: uresp[0]
Out[3]: 
<sunpy.net.fido_factory.UnifiedResponse object at 0x7f944ad03b00>
Results from 1 Provider:

2 Results from the LYRAClient:
     Start Time           End Time      Source Instrument Wavelength
       str19               str19         str6     str4       str3   
------------------- ------------------- ------ ---------- ----------
2012-01-01 00:00:00 2012-01-02 00:00:00 Proba2       lyra        nan
2012-01-01 00:00:00 2012-01-02 00:00:00 Proba2       lyra        nan


In [4]: uresp[1, ::10]
Out[4]: 
<sunpy.net.fido_factory.UnifiedResponse object at 0x7f9413659c88>
Results from 1 Provider:

6 Results from the VSOClient:
   Start Time [1]       End Time [1]    Source Instrument   Type   Wavelength [2]
                                                                      Angstrom   
       str19               str19         str3     str3      str8      float64    
------------------- ------------------- ------ ---------- -------- --------------
2012-01-01 00:00:00 2012-01-02 00:00:00    SDO        EVE FULLDISK   1.0 .. 304.0
2012-01-01 08:00:00 2012-01-01 09:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 18:00:00 2012-01-01 19:00:00    SDO        EVE FULLDISK 93.0 .. 1033.0
2012-01-01 03:00:00 2012-01-01 04:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 13:00:00 2012-01-01 14:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0
2012-01-01 23:00:00 2012-01-02 00:00:00    SDO        EVE FULLDISK 60.0 .. 1060.0


In [5]: Fido.fetch(uresp[0,1], uresp[1,::10])
[========================================]
[========================================]
Out[5]: 
['/home/stuart/sunpy/data/lyra_20120102-000000_lev2_std.fits',
 '/home/stuart/sunpy/data/esp_l1_2012001_005.fit',
 '/home/stuart/sunpy/data/evl_l2_2012001_08_006_01_fit.gz',
 '/home/stuart/sunpy/data/evl_l2_2012001_18_006_01_fit.gz',
 '/home/stuart/sunpy/data/evs_l2_2012001_03_006_01_fit.gz',
 '/home/stuart/sunpy/data/evs_l2_2012001_13_006_01_fit.gz',
 '/home/stuart/sunpy/data/evs_l2_2012001_23_006_01_fit.gz']
```

**Comment by Cadair** [comment]
@dpshelio @ehsteve @ayshih Reviews / comments?

**Comment by Cadair** [comment]
@Punyaslok The idea is that the docs for this will be done seperately, @SolarDrew has already started working on them in #2211. A test for step indexing is a great idea.

**Comment by Cadair** [comment]
@ayshih or @ehsteve  Would you like to review this? I would like to get it merged asap, we have a deadline to hit afterall.

**Pull request merged**
