### PR TITLE
Stale Bot

### PR DESCRIPTION
**Pull request by nabobalis**
Probot is a bot that is run via GitHub integrations, and probot-stale is a specific plugin that will comment on issues or pull requests that are inactive for a certain amount of time, and add a 'stale' label. If an issue or pull request is stale for more than a certain amount of time, then the issue or pull request is closed.

This PR adds the configuration to run this bot on SunPy for just pull requests, considering a PR as 'inactive' after **9** months and closing the PR **2** months after the warning.

If we decide to go ahead with this, we need to install the probot-stale integration for the sunpy organization (easy to do, but needs to be done before this works).

WHICH I CAN NOT DO.

### CODE REVIEW

**Comment by Cadair** [comment]
So personally 6 months seems like a long time, as does two months for the close. I would suggest maybe 5 months and 1 month (for a total of 6).

**Comment by nabobalis** [comment]
I like the 6 month total. Either that or 4 month total.

**Comment by Cadair** [comment]
I think your astropy_helpers change has broken the docs.

**Comment by nabobalis** [comment]
I will revert

**Comment by nabobalis** [comment]
Can I approve my own PR? I THINK I CAN.

**Comment by Cadair** [comment]
No you can review it not approve it.

**Pull request merged**
