### PR TITLE
Ignore out-of-range years for an SRS query

### PR DESCRIPTION
**Pull request by dstansby**
Fixes https://github.com/sunpy/sunpy/issues/4390.

### CODE REVIEW

**Comment by Cadair** [comment]
Easiest way to check for no results is running the `SRSClient.search` method directly, that should return an object with `len() == 0`.

**Review by Cadair — CHANGES_REQUESTED** [review]
This should probably wait for #4321

**Comment by dstansby** [comment]
Just given this an update, and it's all required.

**Review by nabobalis — APPROVED** [review]

**Comment by dstansby** [comment]
Maybe we want to backport this?

**Pull request merged**
