### PR TITLE
Update time.py Removed extract_time

### PR DESCRIPTION
**Pull request by prateekiiest**
@dpshelio , added a deprecated decorator.
The function should now issue a warning if invoked.

issue #2024

### CODE REVIEW

**Comment by prateekiiest** [comment]
Or is it required to totally remove the `extract_time` function??

ping @Cadair @dpshelio

**Comment by m-charlton** [comment]
Cheers

**Comment by Cadair** [comment]
The test is going to need to be removed and it's going to need a changelog.

**Comment by prateekiiest** [comment]
@m-charlton , it is still giving some error.

**Comment by prateekiiest** [comment]
So all the tests including
`test_extract_time_illegal_args():
`
` test_extract_time_best_effort()`
must be removed , since they use extract_time().

Am I right?

**Comment by Cadair** [comment]
yes, anything that calls extract time will need removing.

**Comment by prateekiiest** [comment]
Done @Cadair

**Comment by prateekiiest** [comment]
Done removing the tests that call extract_time.

**Comment by Cadair** [comment]
Needs a change log due to the API change :)

**Comment by prateekiiest** [comment]
OK, on the way.

**Comment by prateekiiest** [comment]
@Cadair 
Is it ok, now?

**Comment by Cadair** [comment]
The tests have failed. I am going to guess you haven't removed extract_time from the `__all__` list somewhere. Check the build logs and run the tests locally before you push.

**Pull request merged**
