### PR TITLE
do not specify a sphinx version in travis.yml

### PR DESCRIPTION
**Pull request by Cadair**
This is an attempt to fix the intermittent sphinx fails.

### CODE REVIEW

**Comment by Cadair** [comment]
This may or may not actually fix the problem. but it contains the astropy_helpers update and should be merged anyway.

**Comment by Cadair** [comment]
@sunpy/sunpy-maintainers review please.

**Comment by Cadair** [comment]
@bsipocz I managed to make the doctest build actually run! @astrofrog pointed out that the `-w` flag captures all the output to check for warnings, which was making travis time it out.

**Comment by Cadair** [comment]
Quite why the doctest build is returning the successful error code I do not know.

**Comment by ayshih** [comment]
:+1:

**Comment by bsipocz** [comment]
@Cadair - Ohh, ok that's good to know, even though it's a bit weird as the astropy and affiliates run with ``-w`` without the getting the timeout.

**Pull request merged**
