### PR TITLE
Achieving full python3 compatibility

### PR DESCRIPTION
**Pull request by bsipocz**
As the title says. Hopefully travis thinks it, too.

ping @Cadair.

### CODE REVIEW

**Comment by Cadair** [comment]
You are a legend. :D

**Comment by bsipocz** [comment]
Final victory!

(though I couldn't hack around the openjpeg stuff  to be in the travis.yml, yaml is just too stupid to understand a simple bash line (or it's me). Anyway I gave up and kept the original version.)

**Comment by Cadair** [comment]
:+1: 

Thank you very much! 

@sunpy/sunpy-maintainers review this please! Soon!

**Comment by dpshelio** [comment]
am I awake???? Oh @bsipocz this is awesome!!! Thanks so much!! :)
:+1:  I just got lost on the `__hash__` int the tables, but the rest seems ok (with a quick look)

**Comment by Cadair** [comment]
ok, I can not contain myself.

**Comment by Cadair** [comment]
BOOM!

**Comment by Cadair** [comment]
Interestingly there seems to be issues on the AppVeyor Python 3 build https://ci.appveyor.com/project/sunpy/sunpy/build/0.7.1608/job/bjsou0mqj6m5y87n#L88

**Comment by bsipocz** [comment]
@dpshelio - re ``__hash__``, the key is in the commit message:

In py3 __hash__ needs to be defined if a class overrides the subclass's __eq__.  https://docs.python.org/3/reference/datamodel.html#object.__hash__

Now I've just added the same behaviour it had with py2, to inherit it from the superclass. However this may be bug prone, as the latter here is definitely not true and x and y are different instances, etc: "x == y implies both that x is y and hash(x) == hash(y)"

**Comment by bsipocz** [comment]
@Cadair - It seems that there is no py3.5+np111 astropy build for windows?

**Comment by dpshelio** [comment]
Thanks @bsipocz for the explanation.. I had thought it had to do with the database, not with python itself.

**Comment by Cadair** [comment]
Ping @derdon regarding `__hash__`

What's the best fix for the CI? Build the package or change the numpy version?

**Comment by bsipocz** [comment]
@Cadair - Either way, but if you want a quick green, then go with py34 (as it's not just astropy, but looks like other packages as well).

However if I run ``conda search --platform win-64 astropy | grep 35``, then there are several versions for py35, so it's not clear why appveyor thinks there isn't any (https://ci.appveyor.com/project/sunpy/sunpy/build/0.7.1608/job/bjsou0mqj6m5y87n#L90 )

```
                             1.0.4                np19py35_0  defaults        
                             1.0.5                np19py35_1  defaults        
                             1.0.5               np110py35_1  defaults        
                             1.0.6               np110py35_0  defaults        
                             1.1                 np110py35_0  defaults        
                             1.1.1               np110py35_0  defaults        
                             1.1.2               np111py35_0  defaults        
                             1.1.2               np110py35_0  defaults        
```

**Comment by bsipocz** [comment]
> @Cadair - Either way, but if you want a quick green, then go with py34 (as it's not just astropy, but looks like other packages as well).

I can also play around with it in the new PR.

**Comment by Cadair** [comment]
@bsipocz going 3.4 under windows seems reasonable to me.

**Comment by bsipocz** [comment]
(@Cadair - glymur was the the source of the problem, now appveyor is full green, too. The conda package is hosted in the sunpy channel, but I think it not a critical package build time wise, thus it's perfectly fine to install it via pip.)

**Pull request merged**
