### PR TITLE
[0.9] RHESSI get_obssum_filename will now download datafile for final day in input timerange

### PR DESCRIPTION
**Pull request by aringlis**
See #2672  - previously, this function did not return the datafile from the final day of the request. This showed up in FIDO queries for RHESSI data as well, which rely on this function.

### CODE REVIEW

**Comment by wafels** [comment]
This had a weird recursive error that looks like it was nothing to do with the PR.  Recommend that this be restarted.

**Comment by Cadair** [comment]
Ok this has legitimately broken many a test.

**Comment by aringlis** [comment]
Oh dear.

I'll take a look.

**Comment by Cadair** [comment]
@aringlis This looks like a real fail not just an aberration? https://travis-ci.org/sunpy/sunpy/jobs/430224268#L3193

**Comment by aringlis** [comment]
@Cadair, yeah it's a doctest failure - I'll fix it.

**Comment by nabobalis** [comment]
Apparently the CI for 0.9 was kind of broken. Hopefully its more fixed now.

**Pull request merged**
