### PR TITLE
Fix the representation of observers in frame repr

### PR DESCRIPTION
**Pull request by Cadair**
This fixes the issue raised by @tiagopereira in #2706 that the observer representation is very verbose when a more useful representation is "earth". This fixes that.

### CODE REVIEW

**Comment by Cadair** [comment]
This is what this does btw:

```python
from astropy.coordinates import SkyCoord
from sunpy.coordinates import frames
import astropy.units as u
```


```python
sc = SkyCoord(0*u.deg, 0*u.deg, frame=frames.Helioprojective, obstime="2011-01-01")
```


```python
sc
```




    <SkyCoord (Helioprojective: obstime=2011-01-01 00:00:00, rsun=695508.0 km, observer=earth): (Tx, Ty) in arcsec
        (0., 0.)>




```python
sc.observer
```




    <HeliographicStonyhurst Coordinate (obstime=2011-01-01 00:00:00): (lon, lat, radius) in (deg, deg, AU)
        (0., -2.97718014, 0.98335587)>




```python
print(sc.observer)
```

    earth



```python
sc.observer._observer_body
```




    'earth'

**Comment by Cadair** [comment]
> I removed the bugfix label because I don't feel that it is appropriate for this PR.

I was also debating this.

> Am I just weird here? 

yeah I don't like it either. 

> I don't know if there's an easy way around this behavior.

Not to achieve the objective. The `repr` for `BaseCoordinateFrame` and `SkyCoord` call `str()` on all the frame attributes. So if we want them to display like that in that context this is the upshot.

> I think you should also overload `__repr__()` to report the observer string.

I deliberately didn't do this to mitigate the issues with `print`. The `repr` should just be the normal coordinate object to me, as that is, after all, what the class is. The changing of `__str__` is really just a hack.

**Comment by Cadair** [comment]
> I don't know if there's an easy way around this behavior.

So the only way around this would be to go into Astropy and poke at [this](https://github.com/astropy/astropy/blob/master/astropy/coordinates/baseframe.py#L1338) method to call out to a `_attribute_repr` method if it is present rather than `__str__`.

**Comment by ayshih** [comment]
There's no strong reason why the `repr` needs to say only `observer=earth` except for the parallelism with the input.  What if instead the `str()` call returned `<HeliographicStonyhurst coordinate of Earth>`?  It's longer, of course, but I think it adds even more clarity while avoiding the confusion of just returning `earth`.

**Comment by ayshih** [comment]
In fact, we should just generalize this beyond just observers.  It'd be a handy way to name coordinates, regardless of whether they are used as observers.  If the coordinate has a name attribute, it'd just stick it into the `str()`-ed version, e.g.:
```
<HeliographicStonyhurst Coordinate of Crab Nebula>
<HeliocentricCoordinate of RHESSI>
```
What do you think?

**Comment by Cadair** [comment]
@ayshih Take a look now :)

**Comment by Cadair** [comment]
preview:

image

**Comment by ayshih** [comment]
Sweet, I like it!

**Comment by wafels** [comment]
The docs will need updating to reflect this.

**Comment by Cadair** [comment]
@ayshih changelog updated.

**Comment by tiagopereira** [comment]
Am I missing something or this no longer works? With sunpy 0.9.6 and astropy 3.1.2:

``` python
from astropy.coordinates import SkyCoord
from sunpy.coordinates import frames
import astropy.units as u

sc = SkyCoord(0*u.deg, 0*u.deg, frame=frames.Helioprojective, obstime="2011-01-01", observer="earth")
```

```python
>>> sc
<SkyCoord (Helioprojective: obstime=2011-01-01 00:00:00, rsun=695508.0 km, observer=<HeliographicStonyhurst Coordinate (obstime=2011-01-01 00:00:00): (lon, lat, radius) in (deg, deg, AU)
    (0., -2.97718014, 0.98335587)>): (Tx, Ty) in arcsec
    (0., 0.)>
```

```python
>>> print(sc.observer)
<HeliographicStonyhurst Coordinate (obstime=2011-01-01 00:00:00): (lon, lat, radius) in (deg, deg, AU)
    (0., -2.97718014, 0.98335587)>
```

```python
>>> sc.observer.object_name
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-074b3cd3b55e> in <module>
----> 1 sc.observer._observer_body

~/miniconda/lib/python3.6/site-packages/astropy/coordinates/baseframe.py in __getattr__(self, attr)
   1517         # Prevent infinite recursion here.
   1518         if attr.startswith('_'):
-> 1519             return self.__getattribute__(attr)  # Raise AttributeError.
   1520
   1521         repr_names = self.representation_component_names

AttributeError: 'HeliographicStonyhurst' object has no attribute 'object_name'
```

**Comment by Cadair** [comment]
@tiagopereira This wasn't classed as a bugfix so hasn't been released in the 0.9.z series of releases. It will be included in the next release (1.0).

(I decided to consider `__repr__` changes as API changes because it's very easy for them to cause peoples doctests to fail, numpy did this on a previous release and it caused us chaos).

**Comment by tiagopereira** [comment]
@Cadair thanks for the clarification.

**Pull request merged**
