### PR TITLE
[0.6] RHESSI Summary Light Curve Fix

### PR DESCRIPTION
**Pull request by ayshih**
Fix of #1600, which is a backport of #1595

### CODE REVIEW

**Comment by Cadair** [comment]
Interesting I think we are missing a patch... think it's #1581 which needs backporting.

**Comment by Cadair** [comment]
also @ayshih @ehsteve changelog entry please!

**Comment by ayshih** [comment]
> also @ayshih @ehsteve changelog entry please!

Heh, @ehsteve needs to do this, because I actually just used his branch when creating this PR.

**Comment by ehsteve** [comment]
@Cadair @ayshih done.

**Comment by ehsteve** [comment]
@Cadair rebased.

**Comment by Cadair** [comment]
Merged manually.

**Pull request closed without merging**
