### PR TITLE
Fixes a regression bug on masked map data plotting

### PR DESCRIPTION
**Pull request by wafels**
Somehow the fix #1392 regressed in master, so I'm putting it back.  The fix makes map.plot respect masked data.

### CODE REVIEW

**Comment by ayshih** [comment]
It looks like the regression was part of d8f6a2c, and given all of the PRs that are in the works for plotting, folks should be watchful for potential regressions now or very soon.

For this particular case, can you add a test?  I think that a figure test (via #1277) would be perfectly appropriate here.

**Comment by Cadair** [comment]
sorry, my bad!

**Comment by Cadair** [comment]
:+1:

**Comment by ayshih** [comment]
:+1:

**Pull request merged**
