### PR TITLE
Cleaned up existing ASV tests and added new ones

### PR DESCRIPTION
**Pull request by ayshih**
I haven't managed to get ASV working locally.  Can someone give this a try?

### CODE REVIEW

**Comment by dstansby** [comment]
Is this ready to be reviewed?

**Comment by ayshih** [comment]
Yay, I finally got `asv` running locally.  This table is neat:
```
============== ========== ============ ========== ========= ========== ==========
--                                           order
-------------- ------------------------------------------------------------------
    method         0           1           2          3         4          5
============== ========== ============ ========== ========= ========== ==========
    scipy       234±3ms     292±10ms    384±20ms   421±7ms   533±10ms   606±9ms
 scikit-image   676±9ms     308±8ms     638±8ms    336±9ms   874±20ms   996±30ms
    opencv      91.1±1ms   95.5±0.9ms     n/a      106±5ms     n/a        n/a
============== ========== ============ ========== ========= ========== ==========

**Comment by ayshih** [comment]
Added some coordinate-transformation benchmarks (it's a shame that it doesn't get rendered in the text output as a table because it is too large):
```
===== ====== =============
 src   dest
----- ------ -------------
 HGS   HGS        n/a
 HGS   HGC     13.3±0.5ms
 HGS   HPC     3.72±0.4ms
 HGS   HCI     4.68±0.1ms
 HGS   HEE     9.52±0.2ms
 HGS   GSE     10.6±0.3ms
 HGS   GEI     8.31±0.3ms
 HGC   HGS     12.9±0.6ms
 HGC   HGC        n/a
 HGC   HPC     17.2±0.5ms
 HGC   HCI      18.8±1ms
 HGC   HEE      23.0±1ms
 HGC   GSE      23.8±2ms
 HGC   GEI     21.9±0.9ms
 HPC   HGS     3.06±0.2ms
 HPC   HGC     16.2±0.3ms
 HPC   HPC        n/a
 HPC   HCI     7.70±0.2ms
 HPC   HEE     13.5±0.7ms
 HPC   GSE      15.0±2ms
 HPC   GEI     11.9±0.3ms
 HCI   HGS     4.63±0.3ms
 HCI   HGC     18.3±0.6ms
 HCI   HPC     8.78±0.6ms
 HCI   HCI        n/a
 HCI   HEE     14.2±0.6ms
 HCI   GSE      16.6±1ms
 HCI   GEI     13.5±0.9ms
 HEE   HGS     9.14±0.7ms
 HEE   HGC      23.3±3ms
 HEE   HPC      13.7±1ms
 HEE   HCI     14.2±0.9ms
 HEE   HEE        n/a
 HEE   GSE    1.32±0.06ms
 HEE   GEI     10.7±0.5ms
 GSE   HGS     11.3±0.5ms
 GSE   HGC      26.1±2ms
 GSE   HPC     15.3±0.3ms
 GSE   HCI      17.0±1ms
 GSE   HEE    1.35±0.03ms
 GSE   GSE        n/a
 GSE   GEI     12.7±0.2ms
 GEI   HGS     7.53±0.1ms
 GEI   HGC     21.0±0.7ms
 GEI   HPC     12.7±0.8ms
 GEI   HCI     12.7±0.9ms
 GEI   HEE     11.0±0.5ms
 GEI   GSE     12.4±0.6ms
 GEI   GEI        n/a
===== ====== =============
```

**Comment by nabobalis** [comment]
You want to merge this and see what the CI benchmark run does?

**Comment by ayshih** [comment]
Yeah, I'm interested in seeing how long it takes our CI to run all of the ASV benchmarks.

I don't think ASV stuff merits a changelog entry yet.  It doesn't seem like something we'd want to publicize, even to developers, until we actually show that it has sufficient value to keep around.  Plus, there's still the concern that ASV does not appear to be actively developed...

**Review by Cadair — APPROVED** [review]

**Comment by nabobalis** [comment]
I manually started one run here: https://github.com/sunpy/sunpy/actions/runs/4284672834 

We will follow it with great interest.

**Pull request merged**
