### PR TITLE
changing spelling of plotting in timeseries (#3426)

### LINKED ISSUE #3426: Bad spelling in time series method name
Not a bug as such because nothing is breaking (as far as I can tell), but the bad spelling of the method below makes the code harder to maintain.  The fix is to spell the method correctly.

### Description

In the time series code the method `_validate_data_for_ploting` appears in several places.

### Expected behavior

I expected "ploting" to be spelled as "plotting".

### System Details

  - SunPy Version: master

The fix is super-easy - fix the spelling.

### PR DESCRIPTION
**Pull request by neerajkulk**
I changed 'ploting' to 'plotting' in timeseries. 

### Description

Fixes #3426

### CODE REVIEW

**Comment by Cadair** [comment]
@neerajkulk If you could add an "trivial" changelog entry that would be awesome.

(side note: I want to have almost everything that gets backported to have a changelog as an ongoing thing)

**Comment by neerajkulk** [comment]
sure,I've added a changelog entry

**Comment by nabobalis** [comment]
Can you add it to this PR please?

**Comment by neerajkulk** [comment]
how do I do that?

**Comment by nabobalis** [comment]
Its fine. We can merge both PRs.

**Comment by nabobalis** [comment]
Thanks again @neerajkulk

**Pull request merged**
