### PR TITLE
Document variables (e.g. Map, Fido, TimeSeries...)

### PR DESCRIPTION
**Pull request by dstansby**
Fixes https://github.com/sunpy/sunpy/issues/3865. Because `sunpy.data.{manager,cache}` are variables, they need an extra option to make `automodapi` document them.

### CODE REVIEW

**Comment by dstansby** [comment]
See https://48805-2165383-gh.circle-artifacts.com/0/docs/_build/html/code_ref/data.html for the variables showing up in the docs.

**Comment by Cadair** [comment]
ooo, nice! Can we do this for `Fido`, `Map` and `Timeseries` as well?

**Comment by Cadair** [comment]
(whoops wrong button)

**Comment by dstansby** [comment]
I presume so? Shall I do it here?

**Comment by Cadair** [comment]
This is awesome, so glad you found the answer to this :smile: 

Can you update this section of the dev docs as well: https://github.com/sunpy/sunpy/blob/master/docs/dev_guide/documentation.rst#sunpy-specific-rules as it presumably doesn't matter any more.

**Comment by ayshih** [comment]
It's not the fault of this PR, but we should revise the docstrings with actual cross-linking because they all are dead-ends:

- https://48905-2165383-gh.circle-artifacts.com/0/docs/_build/html/api/sunpy.map.Map.html
- https://48905-2165383-gh.circle-artifacts.com/0/docs/_build/html/api/sunpy.net.Fido.html (has basically no content)
- https://48905-2165383-gh.circle-artifacts.com/0/docs/_build/html/api/sunpy.timeseries.TimeSeries.html

**Comment by Cadair** [comment]
The Map and Timeseries ones look about as I would expect them to. What are you suggesting @ayshih ?

**Comment by ayshih** [comment]
I mean "dead ends" in the sense that it's not clear where to go to find out more about what comes out of these entities.  For example, Map should provide a description of what it actually returns and an intersphinx link to `GenericMap` to be able to jump to methods and attributes.  I think TimeSeries tries to do that, but it just links to itself.  It wasn't so a problem before since these used to be embedded in surrounding text, but now these can be pulled up in isolation.

**Comment by Cadair** [comment]
I will re-write the docstrings and push.

**Pull request merged**
