### PR TITLE
Fix Matplotlib colormap deprecation

### PR DESCRIPTION
**Pull request by dstansby**
This should fix circleCI devedeps. See https://github.com/matplotlib/matplotlib/pull/23668 for the change in Matplotlib `main` that this adapts to.

### CODE REVIEW

**Review by nabobalis — APPROVED** [review]

**Comment by nabobalis** [comment]
Looks like there are other places still raising the warning?

**Comment by dstansby** [comment]
Hmm, not sure what's going on. Seems to work locally for me, but on circleCI the `ModuleNotFoundError` must be triggered that then calls `mplcm.get_cmap`...

**Review by nabobalis — APPROVED** [review]

**Comment by ConorMacBride** [comment]
This deprecation warning is now failing the devdeps on main and 4.0 https://github.com/sunpy/sunpy/runs/8151142091?check_suite_focus=true. The following references to `get_cmap` probably need updated to use the new helper function. Should the examples be updated to the 3.6 API yet?
```
./examples/plotting/sunpy_matplotlib_colormap.py:17:sdoaia171 = plt.get_cmap('sdoaia171')
./examples/plotting/map_editcolormap.py:25:aiamap.plot_settings['cmap'] = plt.get_cmap('Greys_r')
./examples/example_template/example_template.py:47:plt.imshow(z, cmap=plt.cm.get_cmap('hot'))
./examples/example_template/example_template.py:49:plt.imshow(z, cmap=plt.cm.get_cmap('Spectral'), interpolation='none')
./sunpy/visualization/colormaps/color_tables.py:309:    >>> hmi.plot_settings['cmap'] = plt.get_cmap('hmimag')  # doctest: +SKIP
./sunpy/visualization/colormaps/color_tables.py:317:    >>> plt.imshow(np.clip(hmi.data, -1500.0, 1500.0), cmap=plt.get_cmap('hmimag'), origin='lower')  # doctest: +SKIP
./sunpy/visualization/colormaps/color_tables.py:325:    >>> hmir.plot_settings['cmap'] = plt.get_cmap('hmimag')  # doctest: +SKIP
./sunpy/visualization/colormaps/cm.py:183:# Register the colormaps with matplotlib so plt.get_cmap('sdoaia171') works
./sunpy/visualization/colormaps/tests/test_cm.py:14:        assert cm.cmlist[cmap] == plt.get_cmap(cmap)
./sunpy/map/tests/test_mapbase.py:264:    assert generic_map.cmap == plt.get_cmap('gray')
./sunpy/map/mapbase.py:360:        cmap = copy.copy(cm.get_cmap('gray'))
./sunpy/map/mapbase.py:2113:            cmap = plt.get_cmap(cmap)
```

**Comment by dstansby** [comment]
The new API for selecting colormaps was introduced in Matplotlib 3.5, so in the example gallery we should just use that API (we don't need to support old versions of MPL in the examples). All the other internal bits should be fixed to use the new helper functions.

**Pull request merged**
