### PR TITLE
[2.0] remove warning

### PR DESCRIPTION
**Pull request by nabobalis**

### CODE REVIEW

**Comment by dstansby** [comment]
Which PR is this a backport of?

**Comment by nabobalis** [comment]
It isn't. It removing an added dep warning.

**Comment by dstansby** [comment]
As in it's undoing a backport that shouldn't have ended up in the 2.0.x branch?

**Comment by nabobalis** [comment]
> As in it's undoing a backport that shouldn't have ended up in the 2.0.x branch?

No just undoing the warnings from a backport.

**Comment by Cadair** [comment]
Yeah when the functionality for the new json was added we added a deprecation warning. but we shouldn't backport new dep warnings, even though we need to backport the changes.

**Pull request merged**
