### PR TITLE
[1.0] v1.0.2 backporks

### PR DESCRIPTION
**Pull request by nabobalis**
Backports #3199 #3235 #3243 #3237 #3227 #3225 #3231 #3230 #3229 #3228 #3219 #3220 #3223 #3218 #3217 #3203 #3221 #3216 #3240 #3246 #3245 #3236

todo:

### CODE REVIEW

**Comment by nabobalis** [comment]
The 32bit bug is back?! I might have backported incorrectly?

**Comment by Cadair** [comment]
omg so many backports.

**Comment by nabobalis** [comment]
Its going to be a large bugfix release.

**Comment by nabobalis** [comment]
All the backports should be in place now.

**Pull request merged**
