### PR TITLE
Add a coordinate type check when plotting the wcsaxes grid

### LINKED ISSUE #1478: EIT data fails with wcsaxes
The wcs information in the EIT header is not being identified as celestial axes by wcslib (inside astropy.wcs). This means that wcs is not detecting them as angular axes properly so therefore the set to arcsecond formatting is failing.

### PR DESCRIPTION
**Pull request by Cadair**
This will fix #1478 as long as you have a version of wcsaxes that has the patch from astrofrog/wcsaxes#171.

### CODE REVIEW

**Comment by Cadair** [comment]
ping @astrofrog I assume there is no better way of doing this?

**Comment by ehsteve** [comment]
:+1:

**Comment by wafels** [comment]
+1

**Comment by astrofrog** [comment]
:+1:, don't think there is a better way

**Pull request merged**
