### PR TITLE
Use `--mpl-results-always`

### PR DESCRIPTION
**Pull request by ConorMacBride**
### Description
Uses the new `--mpl-results-always` option of pytest-mpl so all tests (including passing tests) are shown in the HTML output during figure tests.

The pytest-mpl git repository is installed as the new option is not in a release yet.

### CODE REVIEW

**Comment by ConorMacBride** [comment]
The Matplotlib comparison code doesn't save the diff image if the diff is zero, so this is expected. The URL of the diff image is still included in the HTML though. I have a fix for that in a PR I'll open soon.

**Comment by Cadair** [comment]
Ok, I suspected that was the case, all good then. If we can merge #5789 I can re-test the comparison status here again.

**Comment by Cadair** [comment]
ok, giles works again and the pytest-mpl patch seems to work fine, so I will make a release of pytest-mpl when I get 5.

**Comment by dstansby** [comment]
What's the status here? Is it still waiting on something else upstream?

**Comment by ConorMacBride** [comment]
Yes, waiting for the interactive HTML to be merged. Better to not merge this yet as in the current HTML report the tests are sorted by the order collected by pytest, so failing tests can be buried below passing tests.

**Comment by ConorMacBride** [comment]
With the Scipy deprecation warning during test collection the run fails (as expected) and the report is empty (as expected): https://74589-2165383-gh.circle-artifacts.com/0/.tmp/py38-figure/figure_test_images/fig_comparison.html

**Comment by ConorMacBride** [comment]
@Cadair rc is working here

**Pull request closed without merging**
