### PR TITLE
3D map plotting

### PR DESCRIPTION
**Pull request by dstansby**
This is a very very rough draft of code to enable 3D plots to be made with `Map`. This works by:

1. Calculating the coordinates of all the corners of the pixels in a map
2. Converting these to `HeliocentricInertial` coordinates (an arbitrary, but fixed choice of coordinate frame).
3. Using the x, y, z coordinate values in these cooridnates to define the corners of mesh quadrilaterals
4. Creating a `pyvista` (a python interface to VTK) mesh from these mesh coordinates
5. Plotting in `pyvista`

This is super useful when combining visualisation of multiple objects (e.g. adding magnetic field lines, or adding a LASCO map and an AIA map as in https://github.com/sunpy/sunpy/issues/3997#issuecomment-627959946)

If you checkout this branch and run `test.py` hopefully you should get something like:
aia_3d

All feedback welcome!

### CODE REVIEW

**Comment by Cadair** [comment]
Maybe this would be better as a submodule in `sunpy.visualization`?

**Comment by hayesla** [comment]
This is super cool 🌞

**Comment by dstansby** [comment]
😢 readthedocs doesn't support a headless display, so I don't think pyvista examples will run on RTD (https://github.com/readthedocs/readthedocs.org/issues/1951#issuecomment-486453150)

**Comment by nabobalis** [comment]
> 😢 readthedocs doesn't support a headless display, so I don't think pyvista examples will run on RTD ([readthedocs/readthedocs.org#1951 (comment)](https://github.com/readthedocs/readthedocs.org/issues/1951#issuecomment-486453150))

Given this, what about skipping the example just so people know it's possible? 
We can leave a note saying why its static.

**Comment by dstansby** [comment]
Yep, that's what I was planning. Could also possibly embed a .gif or a .png with the output run locally.

**Comment by Cadair** [comment]
It is technically possible to compile VTK in headless mode so it doesn't need an X server...

**Comment by Cadair** [comment]
Another (easier idea) is maybe to spin this up in the conf.py: https://pypi.org/project/xvfbwrapper/

**Comment by Cadair** [comment]
> It is technically possible to compile VTK in headless mode so it doesn't need an X server...

There is supposed to be a conda-forge vtk variant which is compiled with osmesa (off screen mesa GL), but it seems to have been disabled for the newest builds (despite me seemingly being able to use it with a rc of vtk 9.0) so it's possible there is a decent solution to this not that far away.

**Comment by dstansby** [comment]
> Another (easier idea) is maybe to spin this up in the conf.py: https://pypi.org/project/xvfbwrapper/

Hmm, I gave this a go, but VTK doesn't seem to be detecting/using the xvfb wrapper and is just spinning up it's own window for me locally.

**Comment by dstansby** [comment]
I'm wondering about spinning this off into a separate package, so I can more rapidly develop and test it without putting it all in what would be a mega PR. I think there's enough things different (needing pyvista/vtk installed, and really need a way to do image comparison tests with pyvista, which is possible, but I think worth trialing elsewhere first) to warrant this.

**Pull request closed without merging**
