### PR TITLE
Better binder gallery links

### PR DESCRIPTION
**Pull request by StanczakDominik**
The hacky follow up to #3256

### CODE REVIEW

**Comment by StanczakDominik** [comment]
I started taking this upstream with the Sphinx-Gallery folk https://github.com/sphinx-gallery/sphinx-gallery/pull/514, if we can get an upstream resolution for this soon - awesome, if not, I'll keep hacking away at this the hard way :)

**Comment by wtbarnes** [comment]
@StanczakDominik do you have an update on the upstream fix you mentioned above?

**Comment by StanczakDominik** [comment]
Not really; I haven't been following the issue closely, and I'm on vacation
right now. I can probably look into it by the end of the week.

**Comment by wtbarnes** [comment]
No rush. Just wanted to see if there were any updates 😄

**Comment by nabobalis** [comment]
I will close this for now. If anything changes upstream, please reopen this!

**Pull request closed without merging**
