### PR TITLE
[0.6] Helioviewer tests only check API when online.

### PR DESCRIPTION
**Pull request by Cadair**
backport of #1742

### CODE REVIEW

**Comment by nabobalis** [comment]
:+1:

**Comment by dpshelio** [comment]
@cadair, this is different to the current one, right?

**Comment by Cadair** [comment]
well it is now yeah. You can backport your patch if you want, otherwise we can have the nice code in 0.7 and my hack in 0.6.

**Comment by dpshelio** [comment]
well.. leave it as it is. Not that we have to fight and maintain that for long... right? :-P

**Pull request merged**
