### PR TITLE
Use GenericMap.pixel_to_data for center property.

### LINKED ISSUE #1855: Calling `.resample()` on HMI submap reverses sign on x- and y-axis
I don't know whether this is a bug or I am just not understanding what is going on here. 

I understand that HMI data is rotated 180 deg. (relative to say, AIA) (per #1847). When a submap is created, the results are expected, with just the direction of the axes reversed. However, when the same submap is resampled, the x and y axes change signs though the ROI is the same. See example below.

## MWE
```Python
from sunpy.net import vso
from sunpy.map import Map
client = vso.VSOClient()
result_hmi = client.query(
   vso.attrs.Time((2011, 2, 14, 20, 34, 0), (2011, 2, 14, 21, 0, 0)), 
   vso.attrs.Instrument('HMI'),              
   vso.attrs.Physobs('LOS_magnetic_field'),  
   vso.attrs.Sample(4000 * u.s)
 )
data_hmi = client.get(result_hmi, methods=('URL-FILE_Rice', 'URL-FILE')).wait()
hmi_map = sunpy.map.Map(data_hmi[0])
hmi_submap = hmi_map.submap(u.Quantity([50,300]*u.arcsec),u.Quantity([-350,-100]*u.arcsec))
hmi_submap_resampled = hmi_submap.resample(u.Quantity([20,20]*u.pixel),method='linear')
hmi_map.peek()
hmi_submap.peek()
him_submap_resampled.peek()
```
image
image
image

### PR DESCRIPTION
**Pull request by Cadair**
This should fix #1855

### CODE REVIEW

**Comment by Cadair** [comment]
Add regression test.

**Comment by wafels** [comment]
The test failure is due to the fact that the center of the submap differs using the new definition of the center.  The original map center was at Pair(x=<Quantity 196.89613179014896 arcsec>, y=<Quantity 252.25299880518082 arcsec>), and the new center is at Pair(x=<Longitude 206.40012630346973 arcsec>, y=<Latitude 261.91603278665616 arcsec>).   The de-rotation algorithm relies on the position of the submap to calculate how much to shift the maps.

**Comment by Cadair** [comment]
@wafels does this mean this is wrong or just more accurate now that it was before? (also did you expect there to be numbers in that commentt?)

**Comment by wafels** [comment]
I fixed the "no-numbers" in the comment (it was due to less-than and more-than signs being interpreted as formatting, not text).  I am assuming that the new calculation is a better calculation than the previous one, although the new calculation does shift the location of the center quite a lot compared to the previous calculation.  In the solar rotation test, I extract a submap

_aia171_test_map.submap((0, 400)*u.arcsec, (0, 500)*u.arcsec)_

so I would naively expect the center to be at (200, 250)*u.arcsec.  The scale in the test map is 19.183648 arcsec/pixel, so the difference from the naive expectation is still less than a pixel.

**Comment by wafels** [comment]
+1 pending fig fixes.

**Comment by Cadair** [comment]
test fails are known online issues. Merging.

**Pull request merged**
