### PR TITLE
CI config from 6.0

### PR DESCRIPTION
**Pull request by nabobalis**
This is what I did to make it work on release.

### CODE REVIEW

**Comment by Cadair** [comment]
Only testing ana on all the wheels isn't ideal, but I guess if it works it works.

So as well as failing on the nightly uploads, the previous config also failed on actual upload to PyPI? What was the error?

**Review by Cadair — APPROVED** [review]
If it works it works, but can we open an issue to keep track of running the whole test suite.

**Comment by nabobalis** [comment]
The issue is the upload of the wheels. Having both upload jobs breaks on the CI and I can't work it out.

**Comment by nabobalis** [comment]
The error is 

```
Downloading and Extracting Packages: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Using Anaconda API: https://api.anaconda.org/
Using "scientific-python-nightly-wheels" as upload username
Processing "dist/sunpy-6.1.dev20+gde776f10e-cp310-abi3-macosx_10_9_x86_64.whl"
Detecting file type...
File type is "Standard Python"
Extracting standard python attributes for upload
Creating package "sunpy"
Creating release "6.1.dev20+gde776f10e"
Uploading file "scientific-python-nightly-wheels/sunpy/6.1.dev20+gde776f10e/sunpy-6.1.dev20+gde776f10e-cp310-abi3-macosx_10_9_x86_64.whl"

  0%|          | 0.00/3.82M [00:00<?, ?B/s]
  0%|          | 16.0k/3.82M [00:00<00:37, 105kB/s]
  3%|▎         | 128k/3.82M [00:00<00:07, 504kB/s] 
 15%|█▍        | 576k/3.82M [00:00<00:01, 1.72MB/s]
 39%|███▉      | 1.50M/3.82M [00:00<00:00, 3.76MB/s]
3.82MB [00:00, 4.42MB/s]                            
Upload complete

Processing "dist/sunpy-6.1.dev20+gde776f10e-cp310-abi3-macosx_11_0_arm64.whl"
Detecting file type...
File type is "Standard Python"
Extracting standard python attributes for upload
Creating package "sunpy"
Creating release "6.1.dev20+gde776f10e"
Uploading file "scientific-python-nightly-wheels/sunpy/6.1.dev20+gde776f10e/sunpy-6.1.dev20+gde776f10e-cp310-abi3-macosx_11_0_arm64.whl"

  0%|          | 0.00/3.82M [00:00<?, ?B/s]
  0%|          | 16.0k/3.82M [00:00<00:36, 109kB/s]
  4%|▍         | 160k/3.82M [00:00<00:05, 646kB/s] 
 13%|█▎        | 496k/3.82M [00:00<00:02, 1.45MB/s]
 21%|██▏       | 832k/3.82M [00:00<00:01, 1.84MB/s]
 49%|████▊     | 1.86M/3.82M [00:00<00:00, 3.96MB/s]
3.82MB [00:00, 4.34MB/s]                            
Upload complete

Processing "dist/sunpy-6.1.dev20+gde776f10e-cp310-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl"
Detecting file type...
File type is "Standard Python"
Extracting standard python attributes for upload
Error:  Trouble reading metadata from "dist/sunpy-6.1.dev20+gde776f10e-cp310-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl". Is this a valid standard python package?
standard python located at:
  https://anaconda.org/scientific-python-nightly-wheels/sunpy

standard python located at:
  https://anaconda.org/scientific-python-nightly-wheels/sunpy

Error:  Trouble reading metadata from "dist/sunpy-6.1.dev20+gde776f10e-cp310-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl". Is this a valid standard python package?
Error: Process completed with exit code 1.
```

**Pull request merged**
