### PR TITLE
Clarify top_left and bottom_right docs

### LINKED ISSUE #2908: Tighter definition of the bottom left and top right coordinate map properties required?
### Description

Map provides the bottom left and top right coordinates as properties. The issue is that the meaning of the positions described by these coordinates is not obvious.

### Expected behavior

The expected behavior is that the meaning of these coordinates is consistent.

### Actual behavior

It appears that map.bottom_left_coord is the position of the lower left hand vertex of that pixel, and map.top_right_coord is the position of the upper right hand vertex of that pixel.  Therefore the positions that these coordinates refer to are different relative to the pixel.  This is not explicit to the user.  There may be an implicit assumption that these positions define the extent of the map in the world.

### Steps to Reproduce

```
import numpy as np
import sunpy.data.test 
import sunpy.map
import os
import astropy.units as u

testpath = sunpy.data.test.rootdir

m = sunpy.map.Map((os.path.join(testpath, 'aia_171_level1.fits')))
m_bl = m.bottom_left_coord
m_tr = m.top_right_coord

x, y = np.meshgrid(*[np.arange(v.value) for v in m.dimensions]) * u.pix
ac = m.pixel_to_world(x, y)

ac_bl = np.nanmin(ac.Tx.value), np.nanmin(ac.Ty.value)
ac_tr = np.nanmax(ac.Tx.value), np.nanmax(ac.Ty.value)

print(m_bl, ac_bl)
print(m_tr, ac_tr)
```

### System Details

==========================================================
 SunPy Installation Information

==========================================================

###########
 General
###########
System : Darwin
Processor : i386
Arch : 64bit
SunPy : 1.0.0.dev10506
SunPy_git : 10a1729ebc2c9acce33c849fe531e547a359b5fe
OS: Mac OS X 10.13.6 (i386)

###########
 Required Libraries 
###########
Python: 3.6.8
NumPy: 1.15.4
SciPy: 1.1.0
matplotlib: 3.0.2
Astropy: 3.1.1
Pandas: 0.23.4

###########
 Recommended Libraries 
###########
beautifulsoup: 4.6.3
PyQt: NOT INSTALLED
Zeep: NOT INSTALLED
Sqlalchemy: 1.2.15

### PR DESCRIPTION
**Pull request by dstansby**
Hopefully fixes #2908 - what do you think @wafels?

### CODE REVIEW

**Comment by nabobalis** [comment]
Backport this further?

**Comment by dstansby** [comment]
Is `1.0.x` still maintained?

**Comment by nabobalis** [comment]
> Is `1.0.x` still maintained?

I thought so?

**Comment by nabobalis** [comment]
Online fail not due to PR.

**Comment by Cadair** [comment]
We are maintaining 1.0.x until the release of 2.0

**Pull request merged**
