### PR TITLE
Modified Installation Guide and Developer's Guide

### PR DESCRIPTION
**Pull request by hemantkhatri27**

### CODE REVIEW

**Comment by ayshih** [comment]
This PR currently also contains your commits from #1707 about free disk space.  Please create a clean PR with just the documentation changes.  You can use `git-cherry-pick` to isolate the appropriate commits, and you should also use `git-rebase` to combine those commits into a single commit.

**Comment by hemantkhatri27** [comment]
Done. @ayshih

**Comment by hemantkhatri27** [comment]
@Cadair  @derdon please review

**Comment by Cadair** [comment]
closing due to Python 3 support being merged.

**Pull request closed without merging**
