### PR TITLE
Fix mistake in plotting example

### PR DESCRIPTION
**Pull request by nabobalis**
Since we don't run this block, we never caught this error.

I also made the note part, a proper note.

### CODE REVIEW

**Review by wtbarnes — APPROVED** [review]

**Comment by wtbarnes** [comment]
Our user guide needs some TLC 😅

**Comment by nabobalis** [comment]
> Our user guide needs some TLC 😅

Yeah, it really does.

**Comment by ayshih** [comment]
As a coding pattern, I prefer `.to_value(u.deg)` to `.to(u.deg).value` to avoid the creation of an intermediate object.

**Comment by nabobalis** [comment]
> As a coding pattern, I prefer `.to_value(u.deg)` to `.to(u.deg).value` to avoid the creation of an intermediate object.

I had no idea that was possible. I will make that change.

**Comment by nabobalis** [comment]
> As a coding pattern, I prefer `.to_value(u.deg)` to `.to(u.deg).value` to avoid the creation of an intermediate object.

Addressed by https://github.com/sunpy/sunpy/pull/6206

**Pull request merged**
