### PR TITLE
Fixes the failing Scraper FTP test

### PR DESCRIPTION
**Pull request by Raahul-Singh**
Fixes the one test failing in #4020

### CODE REVIEW

**Comment by Raahul-Singh** [comment]
I don't understand the Azure fails.

Further, the CI failed because
```
The authenticity of host 'github.com (140.82.114.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? 
Too long with no output (exceeded 10m0s): context deadline exceeded
```

**Comment by dstansby** [comment]
Circle seems to be working now, I'll restart all the tests

**Comment by Raahul-Singh** [comment]
Some azure tests are failing but it shows all passed. 🤔

**Comment by nabobalis** [comment]
I see some warnings but on the azure page they all passed.

**Pull request merged**
