### PR TITLE
Update .test_package_pins.txt

### PR DESCRIPTION
**Pull request by nabobalis**
Asdf pins it now.

### CODE REVIEW

**Review by ConorMacBride — APPROVED** [review]
Great! We should probably update the tox config to use the URL rather than the file in this PR (and also backport)? https://github.com/sunpy/ndcube/blob/485a0551b35f1113398ceb9b0fcd38807288b488/tox.ini#L13

**Comment by nabobalis** [comment]
I made the tox file on 4.0 point to the file on main. So no need to backport.

**Comment by nabobalis** [comment]
Do we need to change the one for main to point to the URL, the file is in the repo and I think would be useful to point to that.

**Comment by ConorMacBride** [comment]
I missed the update to 4.0. That should be fine then. A benefit of updating the main branch to the url would be so people don't have to pull to their local sunpy repo to get the latest tox pins, but that's an unlikely issue.

**Comment by nabobalis** [comment]
> I missed the update to 4.0. That should be fine then. A benefit of updating the main branch to the url would be so people don't have to pull to their local sunpy repo to get the latest tox pins, but that's an unlikely issue.

This is fair, I think if wanto make sure it works on a PR tho to main, we would need it to point to the local file.

**Pull request merged**
