### PR TITLE
File to Disable Internet Access

### PR DESCRIPTION
**Pull request by souravsingh**
Added file to Prevent Internet Access to Offline Tests

### CODE REVIEW

**Comment by Cadair** [comment]
@souravsingh Thanks for adding this. This needs to be hooked into the test build somehow. I am not sure how to do that off the top of my head, but you could have a look in astropy. Let me know if you can't work it out.

**Comment by souravsingh** [comment]
Thanks @Cadair I have got some idea from AstroPy and currently working on it.

**Comment by souravsingh** [comment]
I have noticed that AstroPy has a test_socketblocker and a script for pytest_plugin using the disable_internet script.

**Comment by Cadair** [comment]
@souravsingh That sounds like the stuff.

**Comment by goelakash** [comment]
@souravsingh  Is there a PR that hooks this in the test suite now?

**Comment by Cadair** [comment]
@souravsingh I am going to close this, feel free to reopen it when you update it.

**Pull request closed without merging**
