### PR TITLE
Remove two gallery examples that use mpl-animators

### PR DESCRIPTION
**Pull request by nabobalis**
I think these belong in the mpl-animators gallery.

TODO
- [x] Create gallery: See https://github.com/sunpy/mpl-animators/pull/37

### CODE REVIEW

**Comment by wtbarnes** [comment]
I agree in theory, but I object until there is an mpl-animators gallery

**Comment by nabobalis** [comment]
I will do that only after people are ok with this in principle. 
IF so, I will work on the gallery.

**Comment by nabobalis** [comment]
Gallery is DONE

**Review by wtbarnes — APPROVED** [review]
Cool, looks good to me. I'm onboard for anything that makes the sunpy gallery more manageable.

**Pull request merged**
