### PR TITLE
Use astropy time for julian_day conversion.

### PR DESCRIPTION
**Pull request by Cadair**
We seemed to have this pretty accurate, but we should use astropy anyway.

### CODE REVIEW

**Comment by Cadair** [comment]
@wafels ping

**Comment by wafels** [comment]
+1

**Comment by dpshelio** [comment]
:+1:

**Comment by wafels** [comment]
Editing https://github.com/sunpy/sunpy/blob/master/sunpy/time/julian.py to
include microseconds induces the same test fails.  Since astropy time
respects microseconds, I believe the root causes of the test fails are due
to astropy time more accurately storing the given time in the SunPy maps.

**Comment by Cadair** [comment]
@wafels so the correct thing to do here would be to update the failing tests, as they are now more accurate?

**Comment by wafels** [comment]
Yep, I am doing that right now.  Will be making a PR to your branch in a
minute or two.

**Comment by Cadair** [comment]
sweet! I don't even have to write code!

**Comment by wafels** [comment]
Travis complains in this PR and in others...

Hint: the following packages conflict with each other:

  - numpy 1.9.3*

  - matplotlib >=1.5.1

**Comment by Cadair** [comment]
@wafels yes that's a known problem at the moment. I think I will remove that build, it can be fixed once #1629 is in.

**Comment by dpshelio** [comment]
no pressure... eh?? :-P

**Comment by Cadair** [comment]
none at all @dpshelio

**Comment by Cadair** [comment]
@wafels if you merge master in to this, it should pass the build.

**Comment by Cadair** [comment]
SOLD!

**Pull request merged**
