### PR TITLE
VSO time attribute to return Astropy time object

### PR DESCRIPTION
**Pull request by tannmay**
Re-opening PR #2260 with previous changes

### CODE REVIEW

**Comment by nabobalis** [comment]
Are you planning to make more changes?

**Comment by nabobalis** [comment]
I forgot to mention, you didn't create the fork correctly. You seem to have not gotten the commit history from that PR.

**Comment by tannmay** [comment]
I opened a new PR and made the changes that were there in #2260 with some changes that were suggested in the comments by @dpshelio. That's why there is no commit history from that PR. All the changes are done with only one commit.

**Comment by nabobalis** [comment]
Well I would personally prefer that the original one commit is in this PR.

**Comment by nabobalis** [comment]
I'm going to close it. If you make any more changes, you can reopen it with no problems.

**Pull request closed without merging**
