### PR TITLE
Remove coordinate test warnings

### PR DESCRIPTION
**Pull request by dstansby**
These are just warnings because the time is very in the future.

### CODE REVIEW

**Comment by nabobalis** [comment]
Thanks again @dstansby

**Comment by dstansby** [comment]
slowly I will beat the warnings

**Comment by nabobalis** [comment]
You know you can tackle more interesting problems!

**Comment by dstansby** [comment]
but these are easy wins 😛

**Comment by Cadair** [comment]
These warnings are the bane of my life in the DKIST package (where I use dates generated like 40 years into the future).

**Pull request merged**
