### PR TITLE
Fix init issue for JP2 HMI images from helioveiwer

### PR DESCRIPTION
**Pull request by nabobalis**
Fixes https://github.com/sunpy/sunpy/issues/6709

Does not scale the images correctly:

Figure_1

### CODE REVIEW

**Review by alasdairwilson — APPROVED** [review]
Approved (with changelog) I can't see the need for unit test but someone else might.

**Review by dstansby — DISMISSED** [review]
A figure test with a jp2 image would be worth adding here, to make sure we keep the scaling correct in the future.

**Comment by nabobalis** [comment]
> A figure test with a jp2 image would be worth adding here, to make sure we keep the scaling correct in the future.

I have added a test and a figure test: The hash will need to be updated due to my inability to generate it on WSL2. 

The big problem is that I don't know how to create a test JP2 file, so its just the file direct from Helioviewer which is 1MB in side, similar to our AIA JP2 file.

I don't think we should add a 1MB file. So I guess I have to see if I can downsample the JP2 File?

**Comment by nabobalis** [comment]
TODO: Rebase and check the hashes are ok.

**Comment by dstansby** [comment]
Yeah, not convinced we should add a 1MB file - how hard would it be to downsample this to something smaller but still reasonable (maybe 256squared?)

**Comment by nabobalis** [comment]
Resizes images and added the code I used to do it. 

I imagine some CI will break at least for any figure tests.

**Review by wtbarnes — APPROVED** [review]

**Comment by nabobalis** [comment]
Manually backported to 4.0

**Pull request merged**
