### PR TITLE
Update zenodo and mailmap for 5.0

### PR DESCRIPTION
**Pull request by dstansby**
👋 hello new contributors! I am updating the list of authors for the zenodo entry (see https://zenodo.org/record/3779284 for a previous example). I have mentioned you because you are a new contributor since sunpy 4.1.

If you would like, please leave a comment below with:

The preferred name you would like to be listed as
Your ORCID
Your affiliation

I will then manually add this to the information. Note that none of this is compulsory!

@exitflynn @Telomelonia @ryuusama09 @davnish @Jett-Code @Satan-Claws @aritrasinha108 @EdBehn @OussCHE @SuleimanFarah @Mihan786Chistie @jiaqing23 @ejm4567

### CODE REVIEW

**Comment by Satan-Claws** [comment]
Hi, 
My ORCID: https://orcid.org/0009-0005-8038-8301
My Affiliation: Chennai Mathematical Institute

**Comment by Jett-Code** [comment]
Hey @dstansby , 
My ORCID: https://orcid.org/0009-0004-7872-0419
My Affiliation: GEU

**Comment by davnish** [comment]
Hi @dstansby, here are my details

Name: Nischal Singh
ORCID: [https://orcid.org/
0009-0007-2165-052X](https://orcid.org/
0009-0007-2165-052X)
Affiliation: Madhav Institute of Technology and Science, Gwalior, India

**Comment by davnish** [comment]
Hi @dstansby, here are my details

Name: Nischal Singh
ORCID: https://orcid.org/0009-0007-2165-052X
Affiliation: Madhav Institute of Technology and Science, Gwalior, India

**Comment by SuleimanFarah** [comment]
Hello,

My details are:
ORCID: https://orcid.org/0009-0001-3304-2923
Affiliation: University of Toronto

Thank you,
Suleiman Farah

On 23/04/2023, at 3:41 PM, David Stansby ***@***.***> wrote:

﻿

👋 hello new contributors! I am updating the list of authors for the zenodo entry (see https://zenodo.org/record/3779284 for a previous example). I have mentioned you because you are a new contributor since sunpy 4.1.

If you would like, please leave a comment below with:

The preferred name you would like to be listed as
Your ORCID
Your affiliation

I will then manually add this to the information. Note that none of this is compulsory!

@exitflynn<https://github.com/exitflynn> @Telomelonia<https://github.com/Telomelonia> @ryuusama09<https://github.com/ryuusama09> @davnish<https://github.com/davnish> @Jett-Code<https://github.com/Jett-Code> @Satan-Claws<https://github.com/Satan-Claws> @aritrasinha108<https://github.com/aritrasinha108> @EdBehn<https://github.com/EdBehn> @OussCHE<https://github.com/OussCHE> @SuleimanFarah<https://github.com/SuleimanFarah> @Mihan786Chistie<https://github.com/Mihan786Chistie> @jiaqing23<https://github.com/jiaqing23> @ejm4567<https://github.com/ejm4567>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/sunpy/sunpy/pull/6953

Commit Summary

  *   c2621ef<https://github.com/sunpy/sunpy/pull/6953/commits/c2621ef12848202db2c0729b9bea928bb1936575> [skip ci] Update mailmap for 5.0
  *   80a8177<https://github.com/sunpy/sunpy/pull/6953/commits/80a817752e9eaf2ecff30e60f318b813b8c6605c> [skip ci] Update zenodo for 5.0

File Changes

(2 files<https://github.com/sunpy/sunpy/pull/6953/files>)

  *   M .mailmap<https://github.com/sunpy/sunpy/pull/6953/files#diff-cfe707d774682f3bbb07d3be5119da9938f80153b7d2cc168c02de9b8595cacc> (7)
  *   M .zenodo.json<https://github.com/sunpy/sunpy/pull/6953/files#diff-69450eccf330a9c709df151fad75b5a9c02976ac29bd5d251bb16eb367997892> (74)

Patch Links:

  *   https://github.com/sunpy/sunpy/pull/6953.patch
  *   https://github.com/sunpy/sunpy/pull/6953.diff

**Comment by Telomelonia** [comment]
Name: Aryan Shukla
ORCID: https://orcid.org/0009-0001-9467-4836
Affiliation: Indian Institute of Technology, Roorkee, India

**Comment by Mihan786Chistie** [comment]
Hi,
My ORCID: https://orcid.org/0009-0007-5883-2749
My Affiliation: Dayananda Sagar University, Bangalore

**Comment by exitflynn** [comment]
Hello 👋
Here's my Orcid: https://orcid.org/0009-0005-4804-9035
And my affiliation: Jaypee Institute of Information Technology, Noida, India

**Review by nabobalis — APPROVED** [review]
Going to approve this so this PR is not held up when we need to merge it later on.

**Comment by Jett-Code** [comment]
Is it updated on the website?

**Comment by nabobalis** [comment]
> Is it updated on the website?

Which website?

**Comment by Jett-Code** [comment]
> > Is it updated on the website?
> 
> Which website?

zenodo

**Comment by nabobalis** [comment]
> > > Is it updated on the website?
> > 
> > Which website?
> 
> zenodo
> 

My understanding is that it will not show up until the final 5.0.0 release. The release candidate isn't counted by zenodo.

**Pull request merged**
