### PR TITLE
Replaced figure.show() with plt.show() to solve instant disapperaing of timeseries plot

### PR DESCRIPTION
**Pull request by talsperre**
Solves issue #2352 

Replaced ```figure.show()``` with ```plt.show()``` in ```sunpy.timeseries.sources``` .  ```Timeseries.peek``` now holds the plot open.

### CODE REVIEW

**Comment by Cadair** [comment]
So I don't think this is the right solution. (Map [peek()](https://github.com/sunpy/sunpy/blob/master/sunpy/map/mapbase.py#L1603) uses `figure.show()` and it works, maybe because of the `toggle_pylab` decorator?

**Comment by talsperre** [comment]
I tried running ```map.peek()``` and face the same issue. The window closes immediately.  
File name: a.py
```
import numpy as np
import sunpy.map
import sunpy.data.sample
mymap = sunpy.map.Map(sunpy.data.sample.AIA_171_IMAGE)
mymap.peek()
```

```python a.py```
Is ```peek()``` function supposed to support only inline plotting?

**Comment by nabobalis** [comment]
peek seems to work if the script is run interactively.
I wonder what the intended behaviour we want is.

**Comment by nabobalis** [comment]
As it stands, we don't have a good idea of how we want peek to behave.

We do not want to use `plt.show()` either. So this solution is not what we are after.

**Pull request closed without merging**
