### PR TITLE
Added Units Parameter

### PR DESCRIPTION
**Pull request by agneet42**
unit="arcsec" added to the NDData parameter.

### CODE REVIEW

**Comment by larrymanley** [comment]
"arcsec" is a spatial unit, not a valid default.  FITS keyword "BUNIT" is a text field describing the physical units of data.  Most often "DN" for solar image data, except e.g. "m/s" for an HMI Dopplergram.  Question being is astropy.units.photon equivalent to "DN"?  And should a units parameter for the array be parsed, hard-coded per instrument/observation, or just left alone for the user to decide based on the context of their observation?

**Comment by wtbarnes** [comment]
I think the most appropriate Astropy units equivalent to DN is `u.count` (or `u.ct`). See [here](http://docs.astropy.org/en/stable/units/#module-astropy.units.astrophys) for more info. 

I think you need to know the details of the instrument, in particular the gain, in order to convert between counts (or DN) and photons. Note also that the units could be DN/pixel or possibly some other variant so Hardcoding it seems like a bad idea. It should probably be parsed from the FITS header in the factory for that particular instrument.

**Comment by agneet42** [comment]
So, to add the units parameter, the details of the instrument are to be known. Do I take it as an user input?

**Comment by Cadair** [comment]
I am going to close this, feel free to reopen it with a better solution.

**Comment by agneet42** [comment]
@Cadair okay.

**Pull request closed without merging**
