### PR TITLE
[0.6] Fixed error when running superpixel -0.6

### PR DESCRIPTION
**Pull request by SallyDa**
Same changes as #1575

### CODE REVIEW

**Comment by ehsteve** [comment]
Could you add the documentation that is in #1575 to this PR as well, please? Thanks.

**Comment by dpshelio** [comment]
@SallyDa I can help you with that, we just need to do as @Cadair told to @ehsteve in #1595

**Comment by Cadair** [comment]
@SallyDa @dpshelio yes, if following those instructions,  best to scrap this branch & PR first tho.

**Comment by SallyDa** [comment]
@Cadair done

**Comment by Cadair** [comment]
@SallyDa thanks! Did you get enough for the t-shirt?

**Comment by SallyDa** [comment]
yeah :)

**Comment by Cadair** [comment]
@SallyDa me too, think I cleared 30 though!

**Comment by SallyDa** [comment]
nice one!

**Comment by Cadair** [comment]
Seems to be some legitimate fails here, don't know why it is different to master.

**Pull request closed without merging**
