### PR TITLE
Add numfocus badge

### PR DESCRIPTION
**Pull request by dpshelio**
quick and simple.

### CODE REVIEW

**Comment by nabobalis** [comment]
Really wanted to run the CI?

**Comment by dpshelio** [comment]
I forgot our magic flags :(

**Comment by Cadair** [comment]
"powered by" is weird wording. Can't it say sponsored or something?

**Comment by nabobalis** [comment]
NumFocus, powers your day by providing all the essential vitamins and amino acids you need for your day!

**Comment by dpshelio** [comment]
@Cadair That's what they sent by email.... I agree with what you said. astropy has it as said in here.

**Comment by nabobalis** [comment]
How about, "Supported by NumFocus"?

**Comment by dpshelio** [comment]
Is it supported by NumFocus? they are not paying us. Besides, as I say, that was the "official" badge they sent.

**Comment by Cadair** [comment]
Support does not have to be financial. Also by the same argument how do they power us?

**Comment by nabobalis** [comment]
NumFocus Supported, NumFocus Sponsored, NumFocus Affiliated?

**Pull request merged**
