### PR TITLE
Fixing typos

### PR DESCRIPTION
**Pull request by bsipocz**
There you go @Cadair. This should fix most of the spelling typos (I don't dare to say all, but should be close) up to the recent master.

### CODE REVIEW

**Comment by bsipocz** [comment]
I've also remove a bunch of unused imports and some minor PEP8 changes (mainly the editor by auto removing trailing white spaces, etc).

**Comment by Cadair** [comment]
Thanks a lot! That's awesome!

That is a quite spectacular amount of typos!

**Comment by bsipocz** [comment]
Well, sunpy has a big codebase ;)

**Comment by Cadair** [comment]
:+1:

**Comment by wafels** [comment]
Great job!
:+1:

**Comment by ehsteve** [comment]
:+1: thanks though I am not looking forward to merging this with my PR

**Comment by bsipocz** [comment]
@ehsteve - it seems that the overlap is minimal, the rebase shouldn't be too painful.

**Pull request merged**
