### PR TITLE
Add some Python 3.8 builds to the CI

### LINKED ISSUE #3409: Add Python 3.8 to the CI Builds
We should update our builds to test with Python 3.8 now that it is released.

This needs the 3.8 builds to be available on Azure, so is blocked on https://github.com/microsoft/azure-pipelines-image-generation/issues/1317

### PR DESCRIPTION
**Pull request by Cadair**
fixes #3409

### CODE REVIEW

**Comment by nabobalis** [comment]
Are we dropping 3.6 testing?

**Comment by Cadair** [comment]
No, not yet. We still have the conda, and other astropy tests running on 3.6.

**Comment by nabobalis** [comment]
Ah yes I forgot about those.

**Comment by nabobalis** [comment]
Pressed the not green button.

**Comment by Cadair** [comment]
Don't know why pipelines hasn't run on this :man_facepalming: I can't seem to login to pipelines to check right now either.

**Comment by nabobalis** [comment]
Could be down.

**Comment by nabobalis** [comment]
Windows failure is a flaky test? Should be safe to ignore.

**Pull request merged**
