### PR TITLE
Hopefully fix doc inheritance issues for quantity_input

### PR DESCRIPTION
**Pull request by Cadair**

### CODE REVIEW

**Comment by Cadair** [comment]
@wafels Can you merge this into your diff rot PR and see if it fixes sphinx?

**Comment by wafels** [comment]
looks good.  the code is failing travis, but the fail is unrelated to the
sphinx doc failing.  The travis fail is due to the test for mapcube solar
derotation not keeping up with the refactoring I implemented last night
(next thing on the to do list).

thanks!

**Comment by Cadair** [comment]
@wafels Is that a long way of writing :+1: ?!

**Comment by wafels** [comment]
+1

**Pull request merged**
